FROM node:8-slim

RUN set -ex \
  \
  && apt-get update \
  \
  && apt-get update \
  && apt-get install -y \
    libpng-dev \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build
