# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

backend:
  image:
    repository: eu.gcr.io/itsmycargo-main/imc/api
    tag: latest
    pullPolicy: Always

frontend:
  image:
    repository: eu.gcr.io/itsmycargo-main/imc/client
    tag: latest
    pullPolicy: Always

service:
  enabled: true
  url:

ingress:
  enabled: true
  auth_url: "https://auth.flotilla.itsmycargo.tech"

credentialsName: services

postgresql:
  enabled: true
  image: eu.gcr.io/itsmycargo-main/postgres-review
  imageTag: latest
  imagePullPolicy: Always

  seed:
    gcs_bucket: itsmycargo-main-engineering-resources
    variant: full_anon
    credentialsName: services

  ## Create a database user
  ## Default: postgres
  postgresUser: postgres
  ## Default: random 10 character string
  postgresPassword: "postgres"
  ## Create a database
  ## Default: the postgres user
  postgresDatabase: "app"

  # Override default liveness & readiness probes
  probes:
    liveness:
      initialDelay: 60
      timeoutSeconds: 5
      failureThreshold: 6
    readiness:
      initialDelay: 60
      timeoutSeconds: 3
      periodSeconds: 5

  persistence:
    size: 10Gi
