# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

meta:
  pullRequestId:

backend:
  image:
    repository: eu.gcr.io/itsmycargo-main/apps/api
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      memory: 1000Mi
      cpu: 1000m
    limits:
      cpu: 1500m
      memory: 1200Mi

frontend:
  image:
    repository: eu.gcr.io/itsmycargo-main/apps/client
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      memory: 24Mi
      cpu: 100m

ingress:
  domain:

masterKey: ""
reviewName:
postgres:
  host:
  user:
  password:
  database:

nodeSelector: {}
tolerations: []
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cloud.google.com/gke-preemptible
          operator: Exists
