# frozen_string_literal: true

source "https://rubygems.org"

gemspec

eval_gemfile "Gemfile.runtime"

gem "shared-factory", path: "../../gems/shared-factory"

gem "quotations", path: "../quotations"
