# frozen_string_literal: true

required:
  - type: excel
    rows: "1:1"
    columns: "A:?"
    content:
      - WWA Member
      - Customer
    excluded_sheet_names:
      - "Kopfdaten"

columns:
  - header: service
    sanitizer: text
    validator: optional_string
    required: false
    type: :object
    alternative_keys:
      - service_level
    fallback: standard
    exclude_sheets:
      - Kopfdaten
  - header: carrier
    sanitizer: text
    validator: optional_string
    required: false
    type: :object
    fallback: "WWA"
    exclude_sheets:
      - Kopfdaten
  - header: carrier_code
    sanitizer: downcase
    validator: optional_string
    required: false
    type: :object
    fallback: "wwa"
    exclude_sheets:
      - Kopfdaten
  - header: customer
    sanitizer: text
    validator: string
    required: true
    type: :object
    exclude_sheets:
      - Kopfdaten
  - header: wwa_member
    sanitizer: text
    validator: string
    required: true
    type: :object
    exclude_sheets:
      - Kopfdaten
  - header: origin_region
    sanitizer: text
    validator: string
    required: true
    type: :object
    exclude_sheets:
      - Kopfdaten
  - header: origin_inland_cfs
    sanitizer: text
    validator: locode
    required: true
    type: :object
    exclude_sheets:
      - Kopfdaten
  - header: consol_cfs
    sanitizer: text
    validator: locode
    required: true
    type: :object
    exclude_sheets:
      - Kopfdaten
  - header: origin_locode
    sanitizer: text
    validator: locode
    required: true
    type: :object
    alternative_keys:
      - port_of_loading
    exclude_sheets:
      - Kopfdaten
  - header: transhipment_1
    sanitizer: text
    validator: optional_locode
    required: false
    type: :object
    exclude_sheets:
      - Kopfdaten
  - header: transhipment_2
    sanitizer: text
    validator: optional_locode
    required: false
    type: :object
    exclude_sheets:
      - Kopfdaten
  - header: transhipment_3
    sanitizer: text
    validator: optional_locode
    required: false
    type: :object
    exclude_sheets:
      - Kopfdaten
  - header: destination_region
    sanitizer: text
    validator: string
    required: true
    type: :object
    exclude_sheets:
      - Kopfdaten
  - header: destination_locode
    sanitizer: text
    validator: locode
    required: true
    type: :object
    alternative_keys:
    - port_of_discharge
    exclude_sheets:
      - Kopfdaten
  - header: deconsol_cfs
    sanitizer: text
    validator: locode
    required: true
    type: :object
    exclude_sheets:
      - Kopfdaten
  - header: destination_inland_cfs
    sanitizer: text
    validator: optional_locode
    required: false
    type: :object
    exclude_sheets:
      - Kopfdaten
  - header: quoting_region
    sanitizer: text
    validator: string
    required: true
    type: :object
    exclude_sheets:
      - Kopfdaten
  - header: group_id
    sanitizer: text
    validator: optional_string
    exclude_sheets:
      - Kopfdaten
  - header: group_name
    sanitizer: text
    validator: optional_string
    exclude_sheets:
      - Kopfdaten
  - header: cargo_class
    sanitizer: text
    validator: optional_string
    fallback: lcl
    exclude_sheets:
      - Kopfdaten
  - header: load_type
    sanitizer: text
    validator: optional_string
    fallback: cargo_item
    exclude_sheets:
      - Kopfdaten
  - header: mode_of_transport
    sanitizer: text
    validator: optional_string
    fallback: ocean
    exclude_sheets:
      - Kopfdaten
  - header: internal
    sanitizer: internal
    validator: boolean
    exclude_sheets:
      - Kopfdaten
  - header: range_min
    sanitizer: decimal
    validator: optional_numeric
    exclude_sheets:
      - Kopfdaten
  - header: range_max
    sanitizer: decimal
    validator: optional_numeric
    exclude_sheets:
      - Kopfdaten
  - header: base
    sanitizer: decimal
    validator: optional_numeric
    exclude_sheets:
      - Kopfdaten

framer: GrdbExcel

dynamic_columns:
  - excluding:
      - REMARKS
      - WM_RATIO
      - VM_RATIO
      - TRANSIT_TIME

operations:
  - type: Grdb
  - type: CountryCodeFromLocode
  - type: ExpandedDates

pipelines:
  - extractors:
      - type: OrganizationCarrier
      - type: RoutingCarrier
    formatter: RoutingCarrier
    importer:
      model: Routing::Carrier

  - extractors:
      - type: Carrier
    formatter: Carrier
    importer:
      model: Legacy::Carrier

  - validators:
      - type: Carrier
    extractors:
      - type: TenantVehicle
    formatter: TenantVehicle
    importer:
      model: Legacy::TenantVehicle
  - validators:
      - type: OriginHub
      - type: DestinationHub
    extractors:
      - type: Itinerary
    formatter: Itinerary
    importer:
      model: Legacy::Itinerary
  - validators:
      - type: PrimaryFeeCode
    extractors:
      - type: ChargeCategory
    formatter: ChargeCategory
    importer:
      model: Legacy::ChargeCategory

  - validators:
      - type: SequentialDates
      - type: Carrier
      - type: TenantVehicle
      - type: Itinerary
      - type: ChargeCategory
      - type: Group
      - type: GrdbRateBasis
      - type: RateBasis
      - type: ChargeFees
    extractors:
      - type: Pricing
    formatter: Pricing
    importer:
      model: Pricings::Pricing
      options:
        recursive: true
    conflicts:
      - model: Pricings::Pricing
        conflict_keys:
          - itinerary_id
          - cargo_class
          - organization_id
          - group_id
          - tenant_vehicle_id

