# frozen_string_literal: true

required:
  - rows: "1:4"
    columns: "A:?"
    content:
      - ZONE

columns:
  - header: "group_name"
    sanitizer: "text"
    validator: "optional_string"
    target_frame: "default"
    required: false

  - header: "group_id"
    sanitizer: "text"
    validator: "optional_string"
    target_frame: "default"
    required: false

  - header: "zone"
    sanitizer: "text"
    validator: "optional_string"
    required: false
    sheet_name: "Fees"
    target_frame: "fees"

  - header: "service"
    sanitizer: "text"
    validator: "optional_string"
    required: false
    alternative_keys:
      - "service_level"
    sheet_name: "Fees"
    target_frame: "fees"

  - header: "carrier"
    sanitizer: "text"
    validator: "optional_string"
    required: false
    sheet_name: "Fees"
    target_frame: "fees"

  - header: "carrier_code"
    sanitizer: "downcase"
    validator: "optional_string"
    required: false
    alternative_keys:
      - "carrier"
    sheet_name: "Fees"
    target_frame: "fees"

  - header: "direction"
    sanitizer: "downcase"
    validator: "direction"
    required: true
    sheet_name: "Fees"
    target_frame: "fees"

  - header: "truck_type"
    sanitizer: "downcase"
    validator: "truck_type"
    required: true
    sheet_name: "Fees"
    target_frame: "fees"

  - header: "cargo_class"
    sanitizer: "downcase"
    validator: "optional_cargo_class"
    required: false
    sheet_name: "Fees"
    target_frame: "fees"

  - header: "min"
    sanitizer: "decimal"
    validator: "optional_numeric"
    required: false
    alternative_keys:
      - "minimum"
    sheet_name: "Fees"
    target_frame: "fees"
  - header: "max"
    sanitizer: "decimal"
    validator: "optional_numeric"
    required: false
    alternative_keys:
      - "maximum"
    sheet_name: "Fees"
    target_frame: "fees"

  - header: "fee_name"
    sanitizer: "text"
    validator: "string"
    required: false
    alternative_keys:
      - "fee"
    sheet_name: "Fees"
    target_frame: "fees"

  - header: "fee_code"
    sanitizer: "downcase"
    validator: "string"
    required: false
    sheet_name: "Fees"
    target_frame: "fees"

  - header: "currency"
    sanitizer: "upcase"
    validator: "currency"
    required: true
    sheet_name: "Fees"
    target_frame: "fees"

  - header: "rate_basis"
    sanitizer: "upcase"
    validator: "string"
    required: false
    sheet_name: "Fees"
    target_frame: "fees"

  - header: "range_min"
    sanitizer: "decimal"
    validator: "optional_numeric"
    required: false
    sheet_name: "Fees"
    target_frame: "fees"

  - header: "range_max"
    sanitizer: "decimal"
    validator: "optional_numeric"
    required: false
    sheet_name: "Fees"
    target_frame: "fees"

  - header: "base"
    sanitizer: "decimal"
    validator: "optional_numeric"
    required: false
    sheet_name: "Fees"
    target_frame: "fees"

  - header: "ton"
    sanitizer: "decimal"
    validator: "optional_numeric"
    required: false
    sheet_name: "Fees"
    target_frame: "fees"

  - header: "cbm"
    sanitizer: "decimal"
    validator: "optional_numeric"
    required: false
    sheet_name: "Fees"
    target_frame: "fees"

  - header: "kg"
    sanitizer: "decimal"
    validator: "optional_numeric"
    required: false
    sheet_name: "Fees"
    target_frame: "fees"

  - header: "item"
    sanitizer: "decimal"
    validator: "optional_numeric"
    required: false
    sheet_name: "Fees"
    target_frame: "fees"

  - header: "shipment"
    sanitizer: "decimal"
    validator: "optional_numeric"
    required: false
    sheet_name: "Fees"
    target_frame: "fees"

  - header: "bill"
    sanitizer: "decimal"
    validator: "optional_numeric"
    required: false
    sheet_name: "Fees"
    target_frame: "fees"

  - header: "container"
    sanitizer: "decimal"
    validator: "optional_numeric"
    required: false
    sheet_name: "Fees"
    target_frame: "fees"

  - header: "wm"
    sanitizer: "decimal"
    validator: "optional_numeric"
    required: false
    sheet_name: "Fees"
    target_frame: "fees"

  - header: "percentage"
    sanitizer: "decimal"
    validator: "optional_numeric"
    required: false
    sheet_name: "Fees"
    target_frame: "fees"

  - header: "service"
    sanitizer: "text"
    validator: "optional_string"
    required: false
    alternative_keys:
      - "service_level"
    fallback: "standard"
    target_frame: "default"
    exclude_sheets:
      - Zones
      - Fees
    column_length: 1

  - header: "carrier"
    sanitizer: "text"
    validator: "string"
    required: false
    fallback: ORGANIZATION_SLUG
    target_frame: "default"
    exclude_sheets:
      - Zones
      - Fees
    column_length: 1
  - header: "carrier_code"
    sanitizer: "downcase"
    validator: "string"
    required: false
    fallback: ORGANIZATION_SLUG
    alternative_keys:
      - "carrier"
    target_frame: "default"
    exclude_sheets:
      - Zones
      - Fees
    column_length: 1

  - header: "direction"
    sanitizer: "downcase"
    validator: "direction"
    required: true
    target_frame: "default"
    exclude_sheets:
      - Zones
      - Fees
    column_length: 1

  - header: "cargo_class"
    sanitizer: "downcase"
    validator: "cargo_class"
    required: true
    target_frame: "default"
    exclude_sheets:
      - Zones
      - Fees
    column_length: 1

  - header: "load_type"
    sanitizer: "downcase"
    validator: "load_type"
    required: true
    target_frame: "default"
    exclude_sheets:
      - Zones
      - Fees
    column_length: 1

  - header: "truck_type"
    sanitizer: "downcase"
    validator: "truck_type"
    required: true
    target_frame: "default"
    exclude_sheets:
      - Zones
      - Fees
    column_length: 1

  - header: "effective_date"
    sanitizer: "date"
    validator: "date"
    required: false
    target_frame: "default"
    exclude_sheets:
      - Zones
      - Fees
    column_length: 1
  - header: "expiration_date"
    sanitizer: "date"
    validator: "date"
    required: false
    target_frame: "default"
    exclude_sheets:
      - Zones
      - Fees
    column_length: 1

  - header: "cbm_ratio"
    sanitizer: "decimal"
    validator: "optional_numeric"
    required: true
    target_frame: "default"
    exclude_sheets:
      - Zones
      - Fees
    column_length: 1
    fallback: 0

  - header: "currency"
    sanitizer: "upcase"
    validator: "currency"
    required: true
    target_frame: "default"
    exclude_sheets:
      - Zones
      - Fees
    column_length: 1

  - header: "base"
    sanitizer: "decimal"
    validator: "optional_numeric"
    required: true
    target_frame: "rates"
    exclude_sheets:
      - Zones
      - Fees
    column_length: 1
    fallback: 0

  - header: "load_meterage_stackable_limit"
    sanitizer: "decimal"
    validator: "optional_numeric"
    required: false
    target_frame: "default"
    exclude_sheets:
      - Zones
      - Fees
    column_length: 1

  - header: "load_meterage_non_stackable_limit"
    sanitizer: "decimal"
    validator: "optional_numeric"
    required: false
    target_frame: "default"
    exclude_sheets:
      - Zones
      - Fees
    column_length: 1

  - header: "load_meterage_hard_limit"
    sanitizer: "boolean"
    validator: "optional_boolean"
    required: false
    target_frame: "default"
    exclude_sheets:
      - Zones
      - Fees
    column_length: 1

  - header: "load_meterage_stackable_type"
    sanitizer: "text"
    validator: "optional_string"
    required: false
    target_frame: "default"
    exclude_sheets:
      - Zones
      - Fees
    column_length: 1

  - header: "load_meterage_non_stackable_type"
    sanitizer: "text"
    validator: "optional_string"
    required: false
    target_frame: "default"
    exclude_sheets:
      - Zones
      - Fees
    column_length: 1

  - header: "rate_basis"
    sanitizer: "upcase"
    validator: "string"
    required: false
    target_frame: "rates"
    exclude_sheets:
      - Zones
      - Fees
    column_length: 1

  - header: "mode_of_transport"
    sanitizer: "downcase"
    validator: "string"
    required: false
    fallback: "truck_carriage"

  - header: "zone"
    sanitizer: "text"
    validator: "zone"
    required: true
    sheet_name: "Zones"
    target_frame: "zones"
  - header: "postal_code"
    sanitizer: "text"
    validator: "optional_string"
    required: false
    alternative_keys:
      - "zipcode"
    sheet_name: "Zones"
    target_frame: "zones"
  - header: "locode"
    sanitizer: "text"
    validator: "optional_locode"
    required: false
    sheet_name: "Zones"
    target_frame: "zones"
  - header: "distance"
    sanitizer: "distance"
    validator: "optional_numeric_like"
    required: false
    sheet_name: "Zones"
    target_frame: "zones"
  - header: "city"
    sanitizer: "text"
    validator: "optional_string"
    required: false
    sheet_name: "Zones"
    target_frame: "zones"
  - header: "province"
    sanitizer: "text"
    validator: "optional_string"
    required: false
    sheet_name: "Zones"
    target_frame: "zones"
  - header: "range"
    sanitizer: "text"
    validator: "zone_range"
    required: false
    sheet_name: "Zones"
    target_frame: "zones"
  - header: "country_code"
    sanitizer: "upcase"
    validator: "country_code"
    required: true
    sheet_name: "Zones"
    target_frame: "zones"

matrixes:
  - header: "rate"
    rows: "6:?"
    columns: "C:?"
    sanitizer: "decimal"
    validator: "numeric"
    required: false
    target_frame: "rates"
    exclude_sheets:
      - Zones
      - Fees

  - header: "row_minimum"
    rows: "6:?"
    columns: "B"
    sanitizer: "text"
    validator: "string"
    required: false
    target_frame: "rates"
    exclude_sheets:
      - Zones
      - Fees

  - header: "zone"
    rows: "6:?"
    columns: "A"
    sanitizer: "text"
    validator: "string"
    required: false
    target_frame: "rates"
    exclude_sheets:
      - Zones
      - Fees

  - header: "bracket_minimum"
    rows: "5"
    columns: "C:?"
    sanitizer: "text"
    validator: "string"
    required: false
    target_frame: "rates"
    exclude_sheets:
      - Zones
      - Fees

  - header: "bracket"
    rows: "4"
    columns: "C:?"
    sanitizer: "text"
    validator: "zone_range"
    required: false
    target_frame: "rates"
    exclude_sheets:
      - Zones
      - Fees

  - header: "modifier"
    rows: "3"
    columns: "C:?"
    sanitizer: "text"
    validator: "modifier"
    required: false
    target_frame: "rates"
    exclude_sheets:
      - Zones
      - Fees

  - header: "identifier"
    rows: "1"
    columns: "B"
    sanitizer: "identifier"
    validator: "identifier"
    required: true
    sheet_name: "Zones"
    target_frame: "zones"

framer: "TruckingRates"

operations:
  - type: LocationFilter
    frames: ["zones"]
  - type: TruckingZones
    frames: ["zones"]
  # - type: TruckingFees
  #   frames: ["fees"]

data_validators:
  - type: DefaultTruckingDates
    frames: ["default"]
  - type: ChargeFees
    frames: ["fees", "rates"]
  - type: TruckingSheet
    frames: ["rates"]

pipelines:
  - extractors:
      - type: OrganizationCarrier
        frames: ["default"]
      - type: RoutingCarrier
        frames: ["default"]
    formatter: RoutingCarrier
    importer:
      model: Routing::Carrier

  - extractors:
      - type: Carrier
        frames: ["default"]
    formatter: Carrier
    importer:
      model: Legacy::Carrier

  - validators:
      - type: Carrier
        frames: ["default"]
    extractors:
      - type: TenantVehicle
        frames: ["default"]
    formatter: TenantVehicle
    importer:
      model: Legacy::TenantVehicle

  - validators:
      - type: QueryType
        frames: ["zones"]
      - type: LocationsLocation
        frames: ["zones"]
      - type: Country
        frames: ["zones"]
    extractors:
      - type: TruckingLocation
        frames: ["zones"]
      - type: TruckingLocationUpsertId
        frames: ["zones"]
    formatter: TruckingLocation
    importer:
      model: Trucking::Location

  - validators:
      - type: QueryMethod
        frames: ["zones"]
    extractors:
      - type: Carriage
        frames: ["default", "fees"]
      - type: DistributionHub
        frames: ["default"]
      - type: TypeAvailability
        frames: ["default"]
    formatter: TypeAvailability
    importer:
      model: Trucking::TypeAvailability

  - extractors:
      - type: ChargeCategory
        frames: ["rates"]
    formatter: ChargeCategory
    importer:
      model: Legacy::ChargeCategory

  - validators:
      - type: TypeAvailability
        frames: ["default"]
    formatter: HubAvailability
    importer:
      model: Trucking::HubAvailability

  - validators:
      - type: Carrier
        frames: ["default"]
      - type: TenantVehicle
        frames: ["default"]
      - type: ChargeCategory
        frames: ["rates", "fees"]
      - type: Group
        frames: ["default"]
      - type: RateBasis
        frames: ["rates", "fees"]
      - type: TruckingLocation
        frames: ["zones"]
    extractors:
      - type: StringValidity
        frames: ["default"]
    conflicts:
      - model: Trucking::Trucking
        conflict_keys:
          - hub_id
          - cargo_class
          - organization_id
          - group_id
          - tenant_vehicle_id
          - carriage
          - country_id
    formatter: Trucking
    importer:
      model: Trucking::Trucking
      options:
        batch_size: 500