# frozen_string_literal: true

module OfferCalculator
  class Errors
    Failure = Class.new(StandardError)
    NoDrivingTime = Class.new(Failure)
    NoValidPricings = Class.new(Failure)
    NoValidSchedules = Class.new(Failure)
    InvalidRoutes = Class.new(Failure)
    NoRoute = Class.new(Failure)
    HubNotFound = Class.new(Failure)
    NoDirectionsFound = Class.new(Failure)
    InvalidPickupAddress = Class.new(Failure)
    InvalidDeliveryAddress = Class.new(Failure)
    MissingTruckingData = Class.new(Failure)
    InvalidTruckingMatch = Class.new(Failure)
    InvalidLocalCharges = Class.new(Failure)
    InvalidFreightResult = Class.new(Failure)
    InvalidLocalChargeResult = Class.new(Failure)
    CalculationError = Class.new(Failure)
    RateBuilderError = Class.new(Failure)
    LoadMeterageExceeded = Class.new(Failure)
    OfferBuilder = Class.new(Failure)
    NoValidOffers = Class.new(Failure)
    NoPreCarriageFound = Class.new(Failure)
    NoOnCarriageFound = Class.new(Failure)
    NoExportFeesFound = Class.new(Failure)
    NoImportFeesFound = Class.new(Failure)
    NoPricingsFound = Class.new(Failure)
    NoManipulatedPreCarriageFound = Class.new(Failure)
    NoManipulatedOnCarriageFound = Class.new(Failure)
    NoManipulatedExportFeesFound = Class.new(Failure)
    NoManipulatedImportFeesFound = Class.new(Failure)
    NoManipulatedPricingsFound = Class.new(Failure)
    InvalidShipmentError = Class.new(Failure)
    InvalidQuotationError = Class.new(Failure)
    InvalidDirection = Class.new(Failure)
    InvalidCargoUnit = Class.new(Failure)
  end
end
