{{- if .Values.migrate.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "migrate.serviceAccountName" . }}
  labels:
    {{- include "polaris.labels" . | nindent 4 }}
  {{- with .Values.migrate.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
