# frozen_string_literal: true

FactoryBot.define do
  factory :excel_data_restructured, class: 'Array' do
    initialize_with { attributes[:data].deep_dup }

    trait :correct_pricings_one_fee_col_and_ranges do
      data do
        [[{ sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Sun, 11 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: nil,
            origin: 'Gothenburg',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'lcl',
            rate_basis: 'PER_WM',
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'USD',
            fee_min: 17,
            fee: 17,
            row_nr: 2,
            origin_name: 'Gothenburg Port',
            destination_name: 'Shanghai Port' },
          { sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Sun, 11 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: nil,
            origin: 'Gothenburg',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'lcl',
            rate_basis: 'PER_WM',
            fee_code: 'HAS',
            fee_name: 'Has',
            currency: 'USD',
            fee_min: 20,
            row_nr: 3,
            range: [{ 'max' => 100, 'min' => 0, 'rate' => 20 }, { 'max' => 500, 'min' => 101, 'rate' => 25 }],
            origin_name: 'Gothenburg Port',
            destination_name: 'Shanghai Port' }],
         [{ sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Thu, 15 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: nil,
            origin: 'Gothenburg',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'lcl',
            rate_basis: 'PER_WM',
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'USD',
            fee_min: 17,
            fee: 17,
            row_nr: 2,
            origin_name: 'Gothenburg Port',
            destination_name: 'Shanghai Port' },
          { sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Thu, 15 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: nil,
            origin: 'Gothenburg',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'lcl',
            rate_basis: 'PER_WM',
            fee_code: 'HAS',
            fee_name: 'Has',
            currency: 'USD',
            fee_min: 20,
            row_nr: 3,
            range: [{ 'max' => 100, 'min' => 0, 'rate' => 20 }, { 'max' => 500, 'min' => 101, 'rate' => 25 }],
            origin_name: 'Gothenburg Port',
            destination_name: 'Shanghai Port' }],
         [{ sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Thu, 15 Nov 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: nil,
            origin: 'Gothenburg',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'lcl',
            rate_basis: 'PER_WM',
            fee_code: 'WAR',
            fee_name: 'War Risk Surcharge',
            currency: 'USD',
            fee_min: 2,
            fee: 2,
            row_nr: 2,
            origin_name: 'Gothenburg Port',
            destination_name: 'Shanghai Port' },
          { sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Thu, 15 Nov 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: nil,
            origin: 'Gothenburg',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'lcl',
            rate_basis: 'PER_WM',
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'USD',
            fee_min: 17,
            fee: 17,
            row_nr: 2,
            origin_name: 'Gothenburg Port',
            destination_name: 'Shanghai Port' },
          { sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Thu, 15 Nov 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: nil,
            origin: 'Gothenburg',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'lcl',
            rate_basis: 'PER_WM',
            fee_code: 'HAS',
            fee_name: 'Has',
            currency: 'USD',
            fee_min: 20,
            row_nr: 3,
            range: [{ 'max' => 100, 'min' => 0, 'rate' => 20 }, { 'max' => 500, 'min' => 101, 'rate' => 25 }],
            origin_name: 'Gothenburg Port',
            destination_name: 'Shanghai Port' }],
         [{ sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Fri, 30 Nov 2018'),
            expiration_date: Date.parse('Thu, 28 Mar 2019'),
            customer_email: nil,
            origin: 'Gothenburg',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'lcl',
            rate_basis: 'PER_WM',
            fee_code: 'ABC',
            fee_name: 'ABC Surcharge',
            currency: 'USD',
            fee_min: 500,
            fee: 500,
            row_nr: 2,
            origin_name: 'Gothenburg Port',
            destination_name: 'Shanghai Port' }],
         [{ sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Fri, 30 Nov 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: nil,
            origin: 'Gothenburg',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'lcl',
            rate_basis: 'PER_WM',
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'USD',
            fee_min: 17,
            fee: 17,
            row_nr: 2,
            origin_name: 'Gothenburg Port',
            destination_name: 'Shanghai Port' },
          { sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Fri, 30 Nov 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: nil,
            origin: 'Gothenburg',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'lcl',
            rate_basis: 'PER_WM',
            fee_code: 'ABC',
            fee_name: 'ABC Surcharge',
            currency: 'USD',
            fee_min: 500,
            fee: 500,
            row_nr: 2,
            origin_name: 'Gothenburg Port',
            destination_name: 'Shanghai Port' },
          { sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Fri, 30 Nov 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: nil,
            origin: 'Gothenburg',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'lcl',
            rate_basis: 'PER_WM',
            fee_code: 'HAS',
            fee_name: 'Has',
            currency: 'USD',
            fee_min: 20,
            row_nr: 3,
            range: [{ 'max' => 100, 'min' => 0, 'rate' => 20 }, { 'max' => 500, 'min' => 101, 'rate' => 25 }],
            origin_name: 'Gothenburg Port',
            destination_name: 'Shanghai Port' },
          { sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Fri, 30 Nov 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: nil,
            origin: 'Gothenburg',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'lcl',
            rate_basis: 'PER_WM',
            fee_code: 'WAR',
            fee_name: 'War Risk Surcharge',
            currency: 'USD',
            fee_min: 2,
            fee: 2,
            row_nr: 2,
            origin_name: 'Gothenburg Port',
            destination_name: 'Shanghai Port' }],
         [{ sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Thu, 15 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: nil,
            origin: 'Gothenburg',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'fcl_10',
            rate_basis: 'PER_CONTAINER',
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'USD',
            fee_min: 1234,
            fee: 1234,
            row_nr: 5,
            origin_name: 'Gothenburg Port',
            destination_name: 'Shanghai Port' }],
         [{ sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Thu, 15 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: nil,
            origin: 'Gothenburg',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'fcl_20',
            rate_basis: 'PER_CONTAINER',
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'USD',
            fee_min: 1234,
            fee: 1234,
            row_nr: 5,
            origin_name: 'Gothenburg Port',
            destination_name: 'Shanghai Port' }],
         [{ sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Thu, 15 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: nil,
            origin: 'Gothenburg',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'fcl_20_ot',
            rate_basis: 'PER_CONTAINER',
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'USD',
            fee_min: 1234,
            fee: 1234,
            row_nr: 5,
            origin_name: 'Gothenburg Port',
            destination_name: 'Shanghai Port' }],
         [{ sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Thu, 15 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: nil,
            origin: 'Gothenburg',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'fcl_20_rf',
            rate_basis: 'PER_CONTAINER',
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'USD',
            fee_min: 1234,
            fee: 1234,
            row_nr: 5,
            origin_name: 'Gothenburg Port',
            destination_name: 'Shanghai Port' }],
         [{ sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Thu, 15 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: nil,
            origin: 'Gothenburg',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'fcl_20_frs',
            rate_basis: 'PER_CONTAINER',
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'USD',
            fee_min: 1234,
            fee: 1234,
            row_nr: 5,
            origin_name: 'Gothenburg Port',
            destination_name: 'Shanghai Port' }],
         [{ sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Thu, 15 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: nil,
            origin: 'Gothenburg',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'fcl_20_frw',
            rate_basis: 'PER_CONTAINER',
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'USD',
            fee_min: 1234,
            fee: 1234,
            row_nr: 5,
            origin_name: 'Gothenburg Port',
            destination_name: 'Shanghai Port' }],
         [{ sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Thu, 15 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: nil,
            origin: 'Gothenburg',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'fcl_40',
            rate_basis: 'PER_CONTAINER',
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'USD',
            fee_min: 1234,
            fee: 1234,
            row_nr: 5,
            origin_name: 'Gothenburg Port',
            destination_name: 'Shanghai Port' }],
         [{ sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Thu, 15 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: nil,
            origin: 'Gothenburg',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'fcl_40_hq',
            rate_basis: 'PER_CONTAINER',
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'USD',
            fee_min: 1234,
            fee: 1234,
            row_nr: 5,
            origin_name: 'Gothenburg Port',
            destination_name: 'Shanghai Port' }],
         [{ sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Thu, 15 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: nil,
            origin: 'Gothenburg',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'fcl_40_ot',
            rate_basis: 'PER_CONTAINER',
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'USD',
            fee_min: 1234,
            fee: 1234,
            row_nr: 5,
            origin_name: 'Gothenburg Port',
            destination_name: 'Shanghai Port' }],
         [{ sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Thu, 15 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: nil,
            origin: 'Gothenburg',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'fcl_40_rf',
            rate_basis: 'PER_CONTAINER',
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'USD',
            fee_min: 1234,
            fee: 1234,
            row_nr: 5,
            origin_name: 'Gothenburg Port',
            destination_name: 'Shanghai Port' }],
         [{ sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Thu, 15 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: nil,
            origin: 'Gothenburg',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'fcl_40_frs',
            rate_basis: 'PER_CONTAINER',
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'USD',
            fee_min: 1234,
            fee: 1234,
            row_nr: 5,
            origin_name: 'Gothenburg Port',
            destination_name: 'Shanghai Port' }],
         [{ sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Thu, 15 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: nil,
            origin: 'Gothenburg',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'fcl_40_frw',
            rate_basis: 'PER_CONTAINER',
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'USD',
            fee_min: 1234,
            fee: 1234,
            row_nr: 5,
            origin_name: 'Gothenburg Port',
            destination_name: 'Shanghai Port' }],
         [{ sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Thu, 15 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: nil,
            origin: 'Gothenburg',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'fcl_45',
            rate_basis: 'PER_CONTAINER',
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'USD',
            fee_min: 1234,
            fee: 1234,
            row_nr: 5,
            origin_name: 'Gothenburg Port',
            destination_name: 'Shanghai Port' }],
         [{ sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Thu, 15 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: nil,
            origin: 'Gothenburg',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'fcl_45_hq',
            rate_basis: 'PER_CONTAINER',
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'USD',
            fee_min: 1234,
            fee: 1234,
            row_nr: 5,
            origin_name: 'Gothenburg Port',
            destination_name: 'Shanghai Port' }],
         [{ sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Thu, 15 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: nil,
            origin: 'Gothenburg',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'fcl_45_rf',
            rate_basis: 'PER_CONTAINER',
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'USD',
            fee_min: 1234,
            fee: 1234,
            row_nr: 5,
            origin_name: 'Gothenburg Port',
            destination_name: 'Shanghai Port' }]]
      end
    end

    trait :faulty_pricings_one_fee_col_and_ranges do
      data do
        [[{ sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Thu, 15 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2011'),
            customer_email: nil,
            origin: 'GothenERRORburg',
            origin_name: 'GothenERRORburg Port',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            destination_name: 'Shanghai Port',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'lcl',
            rate_basis: 'PER_WM',
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'USD',
            fee_min: 17,
            fee: 17,
            row_nr: 2 }],
         [{ sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Thu, 15 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: 'Non.Existent@email.address',
            origin: 'Gothenburg',
            origin_name: 'Gothenburg Port',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            destination_name: 'Shanghai Port',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'lcl',
            rate_basis: 'PER_WM',
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'USD',
            fee_min: 17,
            fee: 17,
            row_nr: 3 }]]
      end
    end

    trait :correct_pricings_dynamic_fee_cols_no_rangs do
      data do
        [[{ carrier: 'APL',
            country_destination: 'Sweden',
            country_origin: 'China',
            currency: 'USD',
            customer_email: nil,
            data_restructurer_name: 'pricing_dynamic_fee_cols_no_ranges',
            destination: 'Gothenburg',
            destination_name: 'Gothenburg Port',
            effective_date: Date.parse('Fri, 01 Feb 2019'),
            expiration_date: Date.parse('Sun, 31 Mar 2019'),
            fee: 60,
            fee_code: 'LSS',
            fee_min: 60,
            fee_name: 'Lss',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Dalian',
            origin_name: 'Dalian Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            service_level: 'standard',
            sheet_name: 'Sheet1',
            transit_time: 42 },
          { carrier: 'APL',
            country_destination: 'Sweden',
            country_origin: 'China',
            currency: 'USD',
            customer_email: nil,
            data_restructurer_name: 'pricing_dynamic_fee_cols_no_ranges',
            destination: 'Gothenburg',
            destination_name: 'Gothenburg Port',
            effective_date: Date.parse('Fri, 01 Feb 2019'),
            expiration_date: Date.parse('Sun, 31 Mar 2019'),
            fee: 1550,
            fee_code: 'RATE',
            fee_min: 1550,
            fee_name: 'Rate',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Dalian',
            origin_name: 'Dalian Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            service_level: 'standard',
            sheet_name: 'Sheet1',
            transit_time: 42 }],
         [{ carrier: 'YML',
            country_destination: 'United Kingdom of Great Britain and Northern Ireland',
            country_origin: 'Hong Kong',
            currency: 'USD',
            customer_email: nil,
            data_restructurer_name: 'pricing_dynamic_fee_cols_no_ranges',
            destination: 'Southampton',
            destination_name: 'Southampton Port',
            effective_date: Date.parse('Tue, 01 Jan 2019'),
            expiration_date: Date.parse('Sun, 31 Mar 2019'),
            fee: 60,
            fee_code: 'LSS',
            fee_min: 60,
            fee_name: 'Lss',
            load_type: 'fcl_40_hq',
            mot: 'ocean',
            origin: 'Hong Kong',
            origin_name: 'Hong Kong Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            service_level: 'standard',
            sheet_name: 'Sheet1',
            transit_time: 27 },
          { carrier: 'YML',
            country_destination: 'United Kingdom of Great Britain and Northern Ireland',
            country_origin: 'Hong Kong',
            currency: 'USD',
            customer_email: nil,
            data_restructurer_name: 'pricing_dynamic_fee_cols_no_ranges',
            destination: 'Southampton',
            destination_name: 'Southampton Port',
            effective_date: Date.parse('Tue, 01 Jan 2019'),
            expiration_date: Date.parse('Sun, 31 Mar 2019'),
            fee: 2550,
            fee_code: 'RATE',
            fee_min: 2550,
            fee_name: 'Rate',
            load_type: 'fcl_40_hq',
            mot: 'ocean',
            origin: 'Hong Kong',
            origin_name: 'Hong Kong Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            service_level: 'standard',
            sheet_name: 'Sheet1',
            transit_time: 27 }]]
      end
    end

    trait :correct_margins do
      data do
        [
          [{ sheet_name: 'Tabelle1',
             data_restructurer_name: 'margins',
             effective_date: Date.parse('Tue, 01 Jan 2019'),
             expiration_date: Date.parse('Sun, 31 Mar 2019'),
             origin: 'Dalian',
             country_origin: 'China',
             destination: 'Gothenburg',
             country_destination: 'Sweden',
             mot: 'ocean',
             carrier: 'Consolidation',
             service_level: 'standard',
             margin_type: 'freight',
             load_type: 'lcl',
             fee_code: 'BAS',
             operator: '%',
             margin: 0.1,
             row_nr: 2 }],
          [{ sheet_name: 'Tabelle1',
             data_restructurer_name: 'margins',
             effective_date: Date.parse('Mon, 01 Apr 2019'),
             expiration_date: Date.parse('Tue, 30 Apr 2019'),
             origin: 'Dalian',
             country_origin: 'China',
             destination: 'Gothenburg',
             country_destination: 'Sweden',
             mot: 'ocean',
             carrier: 'Consolidation',
             service_level: 'standard',
             margin_type: 'freight',
             load_type: 'lcl',
             fee_code: 'BAS',
             operator: '%',
             margin: 0.1,
             row_nr: 3 }],
          [{ sheet_name: 'Tabelle1',
             data_restructurer_name: 'margins',
             effective_date: Date.parse('Tue, 01 Jan 2019'),
             expiration_date: Date.parse('Sun, 31 Mar 2019'),
             origin: 'Ningbo',
             country_origin: 'China',
             destination: 'Gothenburg',
             country_destination: 'Sweden',
             mot: 'ocean',
             carrier: 'Consolidation',
             service_level: 'standard',
             margin_type: 'freight',
             load_type: 'lcl',
             fee_code: 'BAS',
             operator: '%',
             margin: 0.1,
             row_nr: 4 }],
          [{ sheet_name: 'Tabelle1',
             data_restructurer_name: 'margins',
             effective_date: Date.parse('Mon, 01 Apr 2019'),
             expiration_date: Date.parse('Tue, 30 Apr 2019'),
             origin: 'Ningbo',
             country_origin: 'China',
             destination: 'Gothenburg',
             country_destination: 'Sweden',
             mot: 'ocean',
             carrier: 'Consolidation',
             service_level: 'standard',
             margin_type: 'freight',
             load_type: 'lcl',
             fee_code: 'BAS',
             operator: '%',
             margin: 0.1,
             row_nr: 5 }]
        ]
      end
    end

    trait :correct_local_charges do
      data do
        [{ hub: 'Bremerhaven',
           country: 'Germany',
           effective_date: Date.parse('Thu, 24 Jan 2019'),
           expiration_date: Date.parse('Fri, 24 Jan 2020'),
           counterpart_hub: nil,
           counterpart_country: nil,
           service_level: 'standard',
           carrier: 'SACO Shipping',
           mot: 'ocean',
           row_nr: '2',
           load_type: 'lcl',
           direction: 'export',
           dangerous: nil,
           fees: { 'DOC' =>
            { currency: 'EUR',
              key: 'DOC',
              min: nil,
              max: nil,
              name: 'Documentation',
              rate_basis: 'PER_BILL',
              value: 20 } },
           hub_name: 'Bremerhaven Port',
           counterpart_hub_name: nil },
         { hub: 'Antwerp',
           country: 'Belgium',
           effective_date: Date.parse('Thu, 24 Jan 2019'),
           expiration_date: Date.parse('Fri, 24 Jan 2020'),
           counterpart_hub: 'all',
           counterpart_country: nil,
           service_level: 'all',
           carrier: 'SACO Shipping',
           mot: 'ocean',
           row_nr: '3',
           load_type: 'lcl',
           direction: 'export',
           dangerous: nil,
           fees: { 'DOC' =>
           { currency: 'EUR',
             key: 'DOC',
             min: nil,
             max: nil,
             name: 'Documentation',
             rate_basis: 'PER_BILL',
             range: [{ currency: 'EUR', max: 100, min: 0, value: 20 }] } },
           hub_name: 'Antwerp Port',
           counterpart_hub_name: nil },
         { hub: 'Le Havre',
           country: 'France',
           effective_date: Date.parse('Thu, 24 Jan 2019'),
           expiration_date: Date.parse('Fri, 24 Jan 2020'),
           counterpart_hub: 'Antwerp',
           counterpart_country: 'Belgium',
           service_level: 'standard',
           carrier: 'all',
           mot: 'ocean',
           row_nr: '4',
           load_type: 'lcl',
           direction: 'export',
           dangerous: nil,
           fees: { 'DOC' =>
            { currency: 'EUR',
              key: 'DOC',
              min: nil,
              max: nil,
              name: 'Documentation',
              rate_basis: 'PER_BILL',
              value: 20 } },
           hub_name: 'Le Havre Port',
           counterpart_hub_name: 'Antwerp Port' }]
      end
    end

    trait :faulty_local_charges do
      data do
        [
          { hub: 'Bremerhaven',
            country: 'Germany',
            mot: 'ocean',
            row_nr: '2',
            load_type: 'lcl',
            counterpart_hub: nil,
            direction: 'export',
            fees: { 'CMP': { 'key': 'CMP', 'max': nil, 'min': nil, 'name': 'Compliance Fee', 'value': 2.7, 'currency':  'EUR', 'rate_basis':  'PER_SHIPMENT' },
                    'DOC': { 'key': 'DOC', 'max': nil, 'min': nil, 'name': 'Documentation', 'value': 20, 'currency':  'EUR', 'rate_basis':  'PER_WRONG' },
                    'ISP': { 'key':  'ISP', 'max':  nil, 'min':  nil, 'name': 'ISPS', 'value': nil, 'currency': 'EUR', 'rate_basis': 'PER_SHIPMENT' },
                    'QDF': { 'key':  'QDF', 'max':  125, 'min':  55, 'ton': 40, 'name': 'Quay dues', 'currency': 'EUR', 'rate_basis': 'PER_TON' },
                    'SOL': { 'key':  'SOL', 'max':  nil, 'min':  nil, 'name':  'SOLAS Fee', 'value': 7.5, 'currency': 'EUR', 'rate_basis': 'PER_SHIPMENT' },
                    'ZAP': { 'key':  'ZAP', 'max':  nil, 'min':  nil, 'name':  'Zapp', 'currency': 'EUR', 'rate_basis': 'PER_BILL' } },
            dangerous: nil,
            effective_date: Date.parse('Thu, 24 Jan 2019'),
            expiration_date: Date.parse('Fri, 24 Jan 2020')
           },
          { hub: 'BremerERRORhaven',
            country: 'Germany',
            mot: 'ocean',
            row_nr: '3',
            load_type: 'lcl',
            counterpart_hub: nil,
            direction: 'export',
            fees: {},
            dangerous: nil,
            effective_date: Date.parse('Thu, 24 Jan 2019'),
            expiration_date: Date.parse('Fri, 24 Jan 2020')
           }
        ]
      end
    end

    trait :correct_saco_shipping_pricings do
      data do
        [[{ sheet_name: 'Africa',
            data_restructurer_name: 'saco_shipping',
            internal: true,
            destination_locode: 'AOCAB',
            origin_locode: 'DE HAM',
            carrier: 'CMA CGM',
            effective_date: Date.parse('Mon, 01 Apr 2019'),
            expiration_date: Date.parse('Sat, 31 Aug 2019'),
            mot: 'ocean',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'EUR',
            fee: 0.2715e4,
            fee_min: 0.2715e4,
            load_type: 'fcl_20',
            notes: [{ header: 'Electronic Cargo Tracking Note/Waiver (Ectn/Besc)', body: nil, transshipment: false },
                    { header: 'Import Lizenz Nr (Form)', body: nil, transshipment: false },
                    { header: 'Transshipment Via', body: 'CGPNR', transshipment: true },
                    { header: 'Remarks', body: 'some remark', transshipment: false }],
            origin: nil,
            country_origin: nil,
            destination: 'Cabinda',
            country_destination: 'Angola' }],
         [{ sheet_name: 'Africa',
            data_restructurer_name: 'saco_shipping',
            internal: true,
            destination_locode: 'AOCAB',
            origin_locode: 'DE HAM',
            carrier: 'CMA CGM',
            effective_date: Date.parse('Mon, 01 Apr 2019'),
            expiration_date: Date.parse('Sat, 31 Aug 2019'),
            mot: 'ocean',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'EUR',
            fee: 0.4415e4,
            fee_min: 0.4415e4,
            load_type: 'fcl_40',
            notes: [{ header: 'Electronic Cargo Tracking Note/Waiver (Ectn/Besc)', body: nil, transshipment: false },
                    { header: 'Import Lizenz Nr (Form)', body: nil, transshipment: false },
                    { header: 'Transshipment Via', body: 'CGPNR', transshipment: true },
                    { header: 'Remarks', body: 'some remark', transshipment: false }],
            origin: nil,
            country_origin: nil,
            destination: 'Cabinda',
            country_destination: 'Angola' }],
         [{ sheet_name: 'Africa',
            data_restructurer_name: 'saco_shipping',
            internal: true,
            destination_locode: 'AOCAB',
            origin_locode: 'DE HAM',
            carrier: 'CMA CGM',
            effective_date: Date.parse('Mon, 01 Apr 2019'),
            expiration_date: Date.parse('Sat, 31 Aug 2019'),
            mot: 'ocean',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'EUR',
            fee: 0.4415e4,
            fee_min: 0.4415e4,
            load_type: 'fcl_40_hq',
            notes: [{ header: 'Electronic Cargo Tracking Note/Waiver (Ectn/Besc)', body: nil, transshipment: false },
                    { header: 'Import Lizenz Nr (Form)', body: nil, transshipment: false },
                    { header: 'Transshipment Via', body: 'CGPNR', transshipment: true },
                    { header: 'Remarks', body: 'some remark', transshipment: false }],
            origin: nil,
            country_origin: nil,
            destination: 'Cabinda',
            country_destination: 'Angola' }],
         [{ sheet_name: 'Africa',
            data_restructurer_name: 'saco_shipping',
            internal: false,
            destination_locode: 'AOCAB',
            origin_locode: 'BE ANR',
            carrier: 'CMA CGM',
            effective_date: Date.parse('Mon, 01 Apr 2019'),
            expiration_date: Date.parse('Sat, 31 Aug 2019'),
            mot: 'ocean',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'EUR',
            fee: 0.2565e4,
            fee_min: 0.2565e4,
            load_type: 'fcl_20',
            notes: [{ header: 'Electronic Cargo Tracking Note/Waiver (Ectn/Besc)', body: nil, transshipment: false },
                    { header: 'Import Lizenz Nr (Form)', body: nil, transshipment: false },
                    { header: 'Transshipment Via', body: 'CGPNR', transshipment: true },
                    { header: 'Remarks', body: 'some remark', transshipment: false }],
            origin: nil,
            country_origin: nil,
            destination: 'Cabinda - ABC TERMINAL',
            country_destination: 'Angola' }],
         [{ sheet_name: 'Africa',
            data_restructurer_name: 'saco_shipping',
            internal: false,
            destination_locode: 'AOCAB',
            origin_locode: 'BE ANR',
            carrier: 'CMA CGM',
            effective_date: Date.parse('Mon, 01 Apr 2019'),
            expiration_date: Date.parse('Sat, 31 Aug 2019'),
            mot: 'ocean',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'EUR',
            fee: 0.4115e4,
            fee_min: 0.4115e4,
            load_type: 'fcl_40',
            notes: [{ header: 'Electronic Cargo Tracking Note/Waiver (Ectn/Besc)', body: nil, transshipment: false },
                    { header: 'Import Lizenz Nr (Form)', body: nil, transshipment: false },
                    { header: 'Transshipment Via', body: 'CGPNR', transshipment: true },
                    { header: 'Remarks', body: 'some remark', transshipment: false }],
            origin: nil,
            country_origin: nil,
            destination: 'Cabinda - ABC TERMINAL',
            country_destination: 'Angola' }],
         [{ sheet_name: 'Africa',
            data_restructurer_name: 'saco_shipping',
            internal: false,
            destination_locode: 'AOCAB',
            origin_locode: 'BE ANR',
            carrier: 'CMA CGM',
            effective_date: Date.parse('Mon, 01 Apr 2019'),
            expiration_date: Date.parse('Sat, 31 Aug 2019'),
            mot: 'ocean',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'EUR',
            fee: 0.4115e4,
            fee_min: 0.4115e4,
            load_type: 'fcl_40_hq',
            notes: [{ header: 'Electronic Cargo Tracking Note/Waiver (Ectn/Besc)', body: nil, transshipment: false },
                    { header: 'Import Lizenz Nr (Form)', body: nil, transshipment: false },
                    { header: 'Transshipment Via', body: 'CGPNR', transshipment: true },
                    { header: 'Remarks', body: 'some remark', transshipment: false }],
            origin: nil,
            country_origin: nil,
            destination: 'Cabinda - ABC TERMINAL',
            country_destination: 'Angola' }]]
      end
    end

    trait :correct_saco_shipping_local_charges do
      data do
        [{ internal: true,
           carrier: 'CMA CGM',
           effective_date: Date.parse('Mon, 01 Apr 2019'),
           expiration_date: Date.parse('Sat, 31 Aug 2019'),
           mot: 'ocean',
           load_type: 'fcl_20',
           hub: nil,
           hub_locode: 'DE HAM',
           country: nil,
           counterpart_hub: 'Cabinda',
           counterpart_hub_locode: 'AOCAB',
           counterpart_country: 'Angola',
           direction: 'export',
           service_level: 'standard',
           fees: { 'INCLUDED_LSF' => { currency: 'EUR', key: 'INCLUDED_LSF', min: 0, max: nil, name: 'Lsf (included)', rate_basis: 'PER_CONTAINER', value: 0 },
                   'THC' => { currency: 'EUR', key: 'THC', min: 0.232e3, max: nil, name: 'Thc', rate_basis: 'PER_CONTAINER', value: 0.232e3 },
                   'EBS' => { currency: 'EUR', key: 'EBS', min: 0.45e2, max: nil, name: 'Ebs', rate_basis: 'PER_CONTAINER', value: 0.45e2 },
                   'ISPS' => { currency: 'EUR', key: 'ISPS', min: 0.27e2, max: nil, name: 'Isps', rate_basis: 'PER_CONTAINER', value: 0.27e2 } },
           row_nr: '2, 2, 2, 2' },
         { internal: true,
           carrier: 'CMA CGM',
           effective_date: Date.parse('Mon, 01 Apr 2019'),
           expiration_date: Date.parse('Sat, 31 Aug 2019'),
           mot: 'ocean',
           load_type: 'fcl_40',
           hub: nil,
           hub_locode: 'DE HAM',
           country: nil,
           counterpart_hub: 'Cabinda',
           counterpart_hub_locode: 'AOCAB',
           counterpart_country: 'Angola',
           direction: 'export',
           service_level: 'standard',
           fees: { 'INCLUDED_LSF' => { currency: 'EUR', key: 'INCLUDED_LSF', min: 0, max: nil, name: 'Lsf (included)', rate_basis: 'PER_CONTAINER', value: 0 },
                   'THC' => { currency: 'EUR', key: 'THC', min: 0.232e3, max: nil, name: 'Thc', rate_basis: 'PER_CONTAINER', value: 0.232e3 },
                   'EBS' => { currency: 'EUR', key: 'EBS', min: 0.9e2, max: nil, name: 'Ebs', rate_basis: 'PER_CONTAINER', value: 0.9e2 },
                   'ISPS' => { currency: 'EUR', key: 'ISPS', min: 0.27e2, max: nil, name: 'Isps', rate_basis: 'PER_CONTAINER', value: 0.27e2 } },
           row_nr: '2, 2, 2, 2' },
         { internal: true,
           carrier: 'CMA CGM',
           effective_date: Date.parse('Mon, 01 Apr 2019'),
           expiration_date: Date.parse('Sat, 31 Aug 2019'),
           mot: 'ocean',
           load_type: 'fcl_40_hq',
           hub: nil,
           hub_locode: 'DE HAM',
           country: nil,
           counterpart_hub: 'Cabinda',
           counterpart_hub_locode: 'AOCAB',
           counterpart_country: 'Angola',
           direction: 'export',
           service_level: 'standard',
           fees: { 'INCLUDED_LSF' => { currency: 'EUR', key: 'INCLUDED_LSF', min: 0, max: nil, name: 'Lsf (included)', rate_basis: 'PER_CONTAINER', value: 0 },
                   'THC' => { currency: 'EUR', key: 'THC', min: 0.232e3, max: nil, name: 'Thc', rate_basis: 'PER_CONTAINER', value: 0.232e3 },
                   'EBS' => { currency: 'EUR', key: 'EBS', min: 0.9e2, max: nil, name: 'Ebs', rate_basis: 'PER_CONTAINER', value: 0.9e2 },
                   'ISPS' => { currency: 'EUR', key: 'ISPS', min: 0.27e2, max: nil, name: 'Isps', rate_basis: 'PER_CONTAINER', value: 0.27e2 } },
           row_nr: '2, 2, 2, 2' },
         { internal: true,
           carrier: 'CMA CGM',
           effective_date: Date.parse('Tue, 01 Jan 2019'),
           expiration_date: Date.parse('Thu, 31 Jan 2019'),
           mot: 'ocean',
           load_type: 'fcl_20',
           hub: nil,
           hub_locode: 'DE HAM',
           country: nil,
           counterpart_hub: 'Cabinda',
           counterpart_hub_locode: 'AOCAB',
           counterpart_country: 'Angola',
           direction: 'export',
           service_level: 'standard',
           fees: { 'BAF' => { currency: 'EUR', key: 'BAF', min: 0.19e1, max: nil, name: 'Baf', rate_basis: 'PER_CONTAINER', value: 0.19e1 } },
           row_nr: '2' },
         { internal: true,
           carrier: 'CMA CGM',
           effective_date: Date.parse('Tue, 01 Jan 2019'),
           expiration_date: Date.parse('Thu, 31 Jan 2019'),
           mot: 'ocean',
           load_type: 'fcl_40',
           hub: nil,
           hub_locode: 'DE HAM',
           country: nil,
           counterpart_hub: 'Cabinda',
           counterpart_hub_locode: 'AOCAB',
           counterpart_country: 'Angola',
           direction: 'export',
           service_level: 'standard',
           fees: { 'INCLUDED_BAF' => { currency: 'EUR', key: 'INCLUDED_BAF', min: 0, max: nil, name: 'Baf (included)', rate_basis: 'PER_CONTAINER', value: 0 } },
           row_nr: '2' },
         { internal: true,
           carrier: 'CMA CGM',
           effective_date: Date.parse('Tue, 01 Jan 2019'),
           expiration_date: Date.parse('Thu, 31 Jan 2019'),
           mot: 'ocean',
           load_type: 'fcl_40_hq',
           hub: nil,
           hub_locode: 'DE HAM',
           country: nil,
           counterpart_hub: 'Cabinda',
           counterpart_hub_locode: 'AOCAB',
           counterpart_country: 'Angola',
           direction: 'export',
           service_level: 'standard',
           fees: { 'INCLUDED_BAF' => { currency: 'EUR', key: 'INCLUDED_BAF', min: 0, max: nil, name: 'Baf (included)', rate_basis: 'PER_CONTAINER', value: 0 } },
           row_nr: '2' },
         { internal: true,
           carrier: 'CMA CGM',
           effective_date: Date.parse('Sat, 01 Jun 2019'),
           expiration_date: Date.parse('Sun, 30 Jun 2019'),
           mot: 'ocean',
           load_type: 'fcl_20',
           hub: nil,
           hub_locode: 'DE HAM',
           country: nil,
           counterpart_hub: 'Cabinda',
           counterpart_hub_locode: 'AOCAB',
           counterpart_country: 'Angola',
           direction: 'export',
           service_level: 'standard',
           fees: { 'INCLUDED_BAF' => { currency: 'EUR', key: 'INCLUDED_BAF', min: 0, max: nil, name: 'Baf (included)', rate_basis: 'PER_CONTAINER', value: 0 },
                   'INCLUDED_CAF' => { currency: 'EUR', key: 'INCLUDED_CAF', min: 0, max: nil, name: 'Caf (included)', rate_basis: 'PER_CONTAINER', value: 0 } },
           row_nr: '2, 2' },
         { internal: true,
           carrier: 'CMA CGM',
           effective_date: Date.parse('Sat, 01 Jun 2019'),
           expiration_date: Date.parse('Sun, 30 Jun 2019'),
           mot: 'ocean',
           load_type: 'fcl_40',
           hub: nil,
           hub_locode: 'DE HAM',
           country: nil,
           counterpart_hub: 'Cabinda',
           counterpart_hub_locode: 'AOCAB',
           counterpart_country: 'Angola',
           direction: 'export',
           service_level: 'standard',
           fees: { 'INCLUDED_BAF' => { currency: 'EUR', key: 'INCLUDED_BAF', min: 0, max: nil, name: 'Baf (included)', rate_basis: 'PER_CONTAINER', value: 0 },
                   'INCLUDED_CAF' => { currency: 'EUR', key: 'INCLUDED_CAF', min: 0, max: nil, name: 'Caf (included)', rate_basis: 'PER_CONTAINER', value: 0 } },
           row_nr: '2, 2' },
         { internal: true,
           carrier: 'CMA CGM',
           effective_date: Date.parse('Sat, 01 Jun 2019'),
           expiration_date: Date.parse('Sun, 30 Jun 2019'),
           mot: 'ocean',
           load_type: 'fcl_40_hq',
           hub: nil,
           hub_locode: 'DE HAM',
           country: nil,
           counterpart_hub: 'Cabinda',
           counterpart_hub_locode: 'AOCAB',
           counterpart_country: 'Angola',
           direction: 'export',
           service_level: 'standard',
           fees: { 'INCLUDED_BAF' => { currency: 'EUR', key: 'INCLUDED_BAF', min: 0, max: nil, name: 'Baf (included)', rate_basis: 'PER_CONTAINER', value: 0 },
                   'INCLUDED_CAF' => { currency: 'EUR', key: 'INCLUDED_CAF', min: 0, max: nil, name: 'Caf (included)', rate_basis: 'PER_CONTAINER', value: 0 } },
           row_nr: '2, 2' },
         { internal: true,
           carrier: 'CMA CGM',
           effective_date: Date.parse('Wed, 01 May 2019'),
           expiration_date: Date.parse('Fri, 31 May 2019'),
           mot: 'ocean',
           load_type: 'fcl_20',
           hub: nil,
           hub_locode: 'DE HAM',
           country: nil,
           counterpart_hub: 'Cabinda',
           counterpart_hub_locode: 'AOCAB',
           counterpart_country: 'Angola',
           direction: 'export',
           service_level: 'standard',
           fees: { 'INCLUDED_CAF' => { currency: 'EUR', key: 'INCLUDED_CAF', min: 0, max: nil, name: 'Caf (included)', rate_basis: 'PER_CONTAINER', value: 0 } },
           row_nr: '2' },
         { internal: true,
           carrier: 'CMA CGM',
           effective_date: Date.parse('Wed, 01 May 2019'),
           expiration_date: Date.parse('Fri, 31 May 2019'),
           mot: 'ocean',
           load_type: 'fcl_40',
           hub: nil,
           hub_locode: 'DE HAM',
           country: nil,
           counterpart_hub: 'Cabinda',
           counterpart_hub_locode: 'AOCAB',
           counterpart_country: 'Angola',
           direction: 'export',
           service_level: 'standard',
           fees: { 'INCLUDED_CAF' => { currency: 'EUR', key: 'INCLUDED_CAF', min: 0, max: nil, name: 'Caf (included)', rate_basis: 'PER_CONTAINER', value: 0 } },
           row_nr: '2' },
         { internal: true,
           carrier: 'CMA CGM',
           effective_date: Date.parse('Wed, 01 May 2019'),
           expiration_date: Date.parse('Fri, 31 May 2019'),
           mot: 'ocean',
           load_type: 'fcl_40_hq',
           hub: nil,
           hub_locode: 'DE HAM',
           country: nil,
           counterpart_hub: 'Cabinda',
           counterpart_hub_locode: 'AOCAB',
           counterpart_country: 'Angola',
           direction: 'export',
           service_level: 'standard',
           fees: { 'INCLUDED_CAF' => { currency: 'EUR', key: 'INCLUDED_CAF', min: 0, max: nil, name: 'Caf (included)', rate_basis: 'PER_CONTAINER', value: 0 } },
           row_nr: '2' },
         { internal: true,
           carrier: 'CMA CGM',
           effective_date: Date.parse('Mon, 01 Apr 2019'),
           expiration_date: Date.parse('Sat, 31 Aug 2019'),
           mot: 'ocean',
           load_type: 'fcl_20',
           hub: 'Cabinda',
           hub_locode: 'AOCAB',
           country: 'Angola',
           counterpart_hub: nil,
           counterpart_hub_locode: 'DE HAM',
           counterpart_country: nil,
           direction: 'import',
           service_level: 'standard',
           fees: { 'THC' => { currency: 'EUR', key: 'THC', min: 0.15e1, max: nil, name: 'Thc', rate_basis: 'PER_CONTAINER', value: 0.15e1 } },
           row_nr: '2' },
         { internal: false,
           carrier: 'CMA CGM',
           effective_date: Date.parse('Mon, 01 Apr 2019'),
           expiration_date: Date.parse('Sat, 31 Aug 2019'),
           mot: 'ocean',
           load_type: 'fcl_20',
           hub: nil,
           hub_locode: 'BE ANR',
           country: nil,
           counterpart_hub: 'Cabinda - ABC TERMINAL',
           counterpart_hub_locode: 'AOCAB',
           counterpart_country: 'Angola',
           direction: 'export',
           service_level: 'standard',
           fees: { 'INCLUDED_LSF' => { currency: 'EUR', key: 'INCLUDED_LSF', min: 0, max: nil, name: 'Lsf (included)', rate_basis: 'PER_CONTAINER', value: 0 },
                   'THC' => { currency: 'EUR', key: 'THC', min: 0.197e3, max: nil, name: 'Thc', rate_basis: 'PER_CONTAINER', value: 0.197e3 },
                   'EBS' => { currency: 'EUR', key: 'EBS', min: 0.45e2, max: nil, name: 'Ebs', rate_basis: 'PER_CONTAINER', value: 0.45e2 },
                   'ISPS' => { currency: 'EUR', key: 'ISPS', min: 0.27e2, max: nil, name: 'Isps', rate_basis: 'PER_CONTAINER', value: 0.27e2 } },
           row_nr: '3, 3, 3, 3' },
         { internal: false,
           carrier: 'CMA CGM',
           effective_date: Date.parse('Mon, 01 Apr 2019'),
           expiration_date: Date.parse('Sat, 31 Aug 2019'),
           mot: 'ocean',
           load_type: 'fcl_40',
           hub: nil,
           hub_locode: 'BE ANR',
           country: nil,
           counterpart_hub: 'Cabinda - ABC TERMINAL',
           counterpart_hub_locode: 'AOCAB',
           counterpart_country: 'Angola',
           direction: 'export',
           service_level: 'standard',
           fees: { 'INCLUDED_LSF' => { currency: 'EUR', key: 'INCLUDED_LSF', min: 0, max: nil, name: 'Lsf (included)', rate_basis: 'PER_CONTAINER', value: 0 },
                   'THC' => { currency: 'EUR', key: 'THC', min: 0.197e3, max: nil, name: 'Thc', rate_basis: 'PER_CONTAINER', value: 0.197e3 },
                   'EBS' => { currency: 'EUR', key: 'EBS', min: 0.9e2, max: nil, name: 'Ebs', rate_basis: 'PER_CONTAINER', value: 0.9e2 },
                   'ISPS' => { currency: 'EUR', key: 'ISPS', min: 0.27e2, max: nil, name: 'Isps', rate_basis: 'PER_CONTAINER', value: 0.27e2 } },
           row_nr: '3, 3, 3, 3' },
         { internal: false,
           carrier: 'CMA CGM',
           effective_date: Date.parse('Mon, 01 Apr 2019'),
           expiration_date: Date.parse('Sat, 31 Aug 2019'),
           mot: 'ocean',
           load_type: 'fcl_40_hq',
           hub: nil,
           hub_locode: 'BE ANR',
           country: nil,
           counterpart_hub: 'Cabinda - ABC TERMINAL',
           counterpart_hub_locode: 'AOCAB',
           counterpart_country: 'Angola',
           direction: 'export',
           service_level: 'standard',
           fees: { 'INCLUDED_LSF' => { currency: 'EUR', key: 'INCLUDED_LSF', min: 0, max: nil, name: 'Lsf (included)', rate_basis: 'PER_CONTAINER', value: 0 },
                   'THC' => { currency: 'EUR', key: 'THC', min: 0.197e3, max: nil, name: 'Thc', rate_basis: 'PER_CONTAINER', value: 0.197e3 },
                   'EBS' => { currency: 'EUR', key: 'EBS', min: 0.9e2, max: nil, name: 'Ebs', rate_basis: 'PER_CONTAINER', value: 0.9e2 },
                   'ISPS' => { currency: 'EUR', key: 'ISPS', min: 0.27e2, max: nil, name: 'Isps', rate_basis: 'PER_CONTAINER', value: 0.27e2 } },
           row_nr: '3, 3, 3, 3' },
         { internal: false,
           carrier: 'CMA CGM',
           effective_date: Date.parse('Sat, 01 Jun 2019'),
           expiration_date: Date.parse('Sun, 30 Jun 2019'),
           mot: 'ocean',
           load_type: 'fcl_20',
           hub: nil,
           hub_locode: 'BE ANR',
           country: nil,
           counterpart_hub: 'Cabinda - ABC TERMINAL',
           counterpart_hub_locode: 'AOCAB',
           counterpart_country: 'Angola',
           direction: 'export',
           service_level: 'standard',
           fees: { 'INCLUDED_BAF' => { currency: 'EUR', key: 'INCLUDED_BAF', min: 0, max: nil, name: 'Baf (included)', rate_basis: 'PER_CONTAINER', value: 0 },
                   'INCLUDED_CAF' => { currency: 'EUR', key: 'INCLUDED_CAF', min: 0, max: nil, name: 'Caf (included)', rate_basis: 'PER_CONTAINER', value: 0 } },
           row_nr: '3, 3' },
         { internal: false,
           carrier: 'CMA CGM',
           effective_date: Date.parse('Sat, 01 Jun 2019'),
           expiration_date: Date.parse('Sun, 30 Jun 2019'),
           mot: 'ocean',
           load_type: 'fcl_40',
           hub: nil,
           hub_locode: 'BE ANR',
           country: nil,
           counterpart_hub: 'Cabinda - ABC TERMINAL',
           counterpart_hub_locode: 'AOCAB',
           counterpart_country: 'Angola',
           direction: 'export',
           service_level: 'standard',
           fees: { 'INCLUDED_BAF' => { currency: 'EUR', key: 'INCLUDED_BAF', min: 0, max: nil, name: 'Baf (included)', rate_basis: 'PER_CONTAINER', value: 0 },
                   'INCLUDED_CAF' => { currency: 'EUR', key: 'INCLUDED_CAF', min: 0, max: nil, name: 'Caf (included)', rate_basis: 'PER_CONTAINER', value: 0 } },
           row_nr: '3, 3' },
         { internal: false,
           carrier: 'CMA CGM',
           effective_date: Date.parse('Sat, 01 Jun 2019'),
           expiration_date: Date.parse('Sun, 30 Jun 2019'),
           mot: 'ocean',
           load_type: 'fcl_40_hq',
           hub: nil,
           hub_locode: 'BE ANR',
           country: nil,
           counterpart_hub: 'Cabinda - ABC TERMINAL',
           counterpart_hub_locode: 'AOCAB',
           counterpart_country: 'Angola',
           direction: 'export',
           service_level: 'standard',
           fees: { 'INCLUDED_BAF' => { currency: 'EUR', key: 'INCLUDED_BAF', min: 0, max: nil, name: 'Baf (included)', rate_basis: 'PER_CONTAINER', value: 0 },
                   'INCLUDED_CAF' => { currency: 'EUR', key: 'INCLUDED_CAF', min: 0, max: nil, name: 'Caf (included)', rate_basis: 'PER_CONTAINER', value: 0 } },
           row_nr: '3, 3' },
         { internal: false,
           carrier: 'CMA CGM',
           effective_date: Date.parse('Wed, 01 May 2019'),
           expiration_date: Date.parse('Fri, 31 May 2019'),
           mot: 'ocean',
           load_type: 'fcl_20',
           hub: nil,
           hub_locode: 'BE ANR',
           country: nil,
           counterpart_hub: 'Cabinda - ABC TERMINAL',
           counterpart_hub_locode: 'AOCAB',
           counterpart_country: 'Angola',
           direction: 'export',
           service_level: 'standard',
           fees: { 'INCLUDED_CAF' => { currency: 'EUR', key: 'INCLUDED_CAF', min: 0, max: nil, name: 'Caf (included)', rate_basis: 'PER_CONTAINER', value: 0 } },
           row_nr: '3' },
         { internal: false,
           carrier: 'CMA CGM',
           effective_date: Date.parse('Wed, 01 May 2019'),
           expiration_date: Date.parse('Fri, 31 May 2019'),
           mot: 'ocean',
           load_type: 'fcl_40',
           hub: nil,
           hub_locode: 'BE ANR',
           country: nil,
           counterpart_hub: 'Cabinda - ABC TERMINAL',
           counterpart_hub_locode: 'AOCAB',
           counterpart_country: 'Angola',
           direction: 'export',
           service_level: 'standard',
           fees: { 'INCLUDED_CAF' => { currency: 'EUR', key: 'INCLUDED_CAF', min: 0, max: nil, name: 'Caf (included)', rate_basis: 'PER_CONTAINER', value: 0 } },
           row_nr: '3' },
         { internal: false,
           carrier: 'CMA CGM',
           effective_date: Date.parse('Wed, 01 May 2019'),
           expiration_date: Date.parse('Fri, 31 May 2019'),
           mot: 'ocean',
           load_type: 'fcl_40_hq',
           hub: nil,
           hub_locode: 'BE ANR',
           country: nil,
           counterpart_hub: 'Cabinda - ABC TERMINAL',
           counterpart_hub_locode: 'AOCAB',
           counterpart_country: 'Angola',
           direction: 'export',
           service_level: 'standard',
           fees: { 'INCLUDED_CAF' => { currency: 'EUR', key: 'INCLUDED_CAF', min: 0, max: nil, name: 'Caf (included)', rate_basis: 'PER_CONTAINER', value: 0 } },
           row_nr: '3' },
         { internal: false,
           carrier: 'CMA CGM',
           effective_date: Date.parse('Mon, 01 Apr 2019'),
           expiration_date: Date.parse('Sat, 31 Aug 2019'),
           mot: 'ocean',
           load_type: 'fcl_40',
           hub: 'Cabinda - ABC TERMINAL',
           hub_locode: 'AOCAB',
           country: 'Angola',
           counterpart_hub: nil,
           counterpart_hub_locode: 'BE ANR',
           counterpart_country: nil,
           direction: 'import',
           service_level: 'standard',
           fees: { 'THC' => { currency: 'EUR', key: 'THC', min: 0.25e1, max: nil, name: 'Thc', rate_basis: 'PER_CONTAINER', value: 0.25e1 } },
           row_nr: '3' },
         { internal: false,
           carrier: 'CMA CGM',
           effective_date: Date.parse('Mon, 01 Apr 2019'),
           expiration_date: Date.parse('Sat, 31 Aug 2019'),
           mot: 'ocean',
           load_type: 'fcl_40_hq',
           hub: 'Cabinda - ABC TERMINAL',
           hub_locode: 'AOCAB',
           country: 'Angola',
           counterpart_hub: nil,
           counterpart_hub_locode: 'BE ANR',
           counterpart_country: nil,
           direction: 'import',
           service_level: 'standard',
           fees: { 'THC' => { currency: 'EUR', key: 'THC', min: 0.25e1, max: nil, name: 'Thc', rate_basis: 'PER_CONTAINER', value: 0.25e1 } },
           row_nr: '3' }]
      end
    end

    factory :excel_data_restructured_correct_pricings_one_fee_col_and_ranges, traits: %i(correct_pricings_one_fee_col_and_ranges)
    factory :excel_data_restructured_faulty_pricings_one_fee_col_and_ranges, traits: %i(faulty_pricings_one_fee_col_and_ranges)
    factory :excel_data_restructured_correct_pricings_dynamic_fee_cols_no_rangs, traits: %i(correct_pricings_dynamic_fee_cols_no_rangs)
    factory :excel_data_restructured_correct_margins, traits: %i(correct_margins)
    factory :excel_data_restructured_correct_local_charges, traits: %i(correct_local_charges)
    factory :excel_data_restructured_faulty_local_charges, traits: %i(faulty_local_charges)
    factory :excel_data_restructured_correct_saco_shipping_pricings, traits: %i(correct_saco_shipping_pricings)
    factory :excel_data_restructured_correct_saco_shipping_local_charges, traits: %i(correct_saco_shipping_local_charges)
  end
end
