# frozen_string_literal: true

FactoryBot.define do
  factory :excel_data_restructured, class: 'Array' do
    initialize_with { attributes[:data].deep_dup }

    trait :correct_pricings_one_fee_col_and_ranges do
      data do
        [[{sheet_name: "Sheet1",
          data_restructurer_name: "pricing_one_col_fee_and_ranges",
          effective_date: Date.parse('Thu, 15 Mar 2018'),
          expiration_date: Date.parse('Sun, 17 Mar 2019'),
          customer_email: nil,
          origin: "Gothenburg",
          country_origin: "Sweden",
          destination: "Shanghai",
          country_destination: "China",
          mot: "ocean",
          carrier: nil,
          service_level: "standard",
          load_type: "lcl",
          rate_basis: "PER_WM",
          fee_code: "BAS",
          fee_name: "Bas",
          currency: "USD",
          fee_min: 17,
          fee: 17,
          row_nr: 2,
          origin_name: "Gothenburg Port",
          destination_name: "Shanghai Port"}],
        [{sheet_name: "Sheet1",
          data_restructurer_name: "pricing_one_col_fee_and_ranges",
          effective_date: Date.parse('Sun, 11 Mar 2018'),
          expiration_date: Date.parse('Sun, 17 Mar 2019'),
          customer_email: nil,
          origin: "Gothenburg",
          country_origin: "Sweden",
          destination: "Shanghai",
          country_destination: "China",
          mot: "ocean",
          carrier: nil,
          service_level: "standard",
          load_type: "lcl",
          rate_basis: "PER_WM",
          fee_code: "BAS",
          fee_name: "Bas",
          currency: "USD",
          fee_min: 17,
          fee: 17,
          row_nr: 2,
          origin_name: "Gothenburg Port",
          destination_name: "Shanghai Port"},
         {sheet_name: "Sheet1",
          data_restructurer_name: "pricing_one_col_fee_and_ranges",
          effective_date: Date.parse('Sun, 11 Mar 2018'),
          expiration_date: Date.parse('Sun, 17 Mar 2019'),
          customer_email: nil,
          origin: "Gothenburg",
          country_origin: "Sweden",
          destination: "Shanghai",
          country_destination: "China",
          mot: "ocean",
          carrier: nil,
          service_level: "standard",
          load_type: "lcl",
          rate_basis: "PER_WM",
          fee_code: "HAS",
          fee_name: "Has",
          currency: "USD",
          fee_min: 20,
          row_nr: 3,
          range: [{"max" => 100, "min" => 0, "rate" => 20}, {"max" => 500, "min" => 101, "rate" => 25}],
          origin_name: "Gothenburg Port",
          destination_name: "Shanghai Port"}],
        [{sheet_name: "Sheet1",
          data_restructurer_name: "pricing_one_col_fee_and_ranges",
          effective_date: Date.parse('Thu, 15 Mar 2018'),
          expiration_date: Date.parse('Sun, 17 Mar 2019'),
          customer_email: nil,
          origin: "Gothenburg",
          country_origin: "Sweden",
          destination: "Shanghai",
          country_destination: "China",
          mot: "ocean",
          carrier: nil,
          service_level: "standard",
          load_type: "fcl_10",
          rate_basis: "PER_CONTAINER",
          fee_code: "BAS",
          fee_name: "Bas",
          currency: "USD",
          fee_min: 1234,
          fee: 1234,
          row_nr: 5,
          origin_name: "Gothenburg Port",
          destination_name: "Shanghai Port"}],
        [{sheet_name: "Sheet1",
          data_restructurer_name: "pricing_one_col_fee_and_ranges",
          effective_date: Date.parse('Thu, 15 Mar 2018'),
          expiration_date: Date.parse('Sun, 17 Mar 2019'),
          customer_email: nil,
          origin: "Gothenburg",
          country_origin: "Sweden",
          destination: "Shanghai",
          country_destination: "China",
          mot: "ocean",
          carrier: nil,
          service_level: "standard",
          load_type: "fcl_20",
          rate_basis: "PER_CONTAINER",
          fee_code: "BAS",
          fee_name: "Bas",
          currency: "USD",
          fee_min: 1234,
          fee: 1234,
          row_nr: 5,
          origin_name: "Gothenburg Port",
          destination_name: "Shanghai Port"}],
        [{sheet_name: "Sheet1",
          data_restructurer_name: "pricing_one_col_fee_and_ranges",
          effective_date: Date.parse('Thu, 15 Mar 2018'),
          expiration_date: Date.parse('Sun, 17 Mar 2019'),
          customer_email: nil,
          origin: "Gothenburg",
          country_origin: "Sweden",
          destination: "Shanghai",
          country_destination: "China",
          mot: "ocean",
          carrier: nil,
          service_level: "standard",
          load_type: "fcl_20_ot",
          rate_basis: "PER_CONTAINER",
          fee_code: "BAS",
          fee_name: "Bas",
          currency: "USD",
          fee_min: 1234,
          fee: 1234,
          row_nr: 5,
          origin_name: "Gothenburg Port",
          destination_name: "Shanghai Port"}],
        [{sheet_name: "Sheet1",
          data_restructurer_name: "pricing_one_col_fee_and_ranges",
          effective_date: Date.parse('Thu, 15 Mar 2018'),
          expiration_date: Date.parse('Sun, 17 Mar 2019'),
          customer_email: nil,
          origin: "Gothenburg",
          country_origin: "Sweden",
          destination: "Shanghai",
          country_destination: "China",
          mot: "ocean",
          carrier: nil,
          service_level: "standard",
          load_type: "fcl_20_rf",
          rate_basis: "PER_CONTAINER",
          fee_code: "BAS",
          fee_name: "Bas",
          currency: "USD",
          fee_min: 1234,
          fee: 1234,
          row_nr: 5,
          origin_name: "Gothenburg Port",
          destination_name: "Shanghai Port"}],
        [{sheet_name: "Sheet1",
          data_restructurer_name: "pricing_one_col_fee_and_ranges",
          effective_date: Date.parse('Thu, 15 Mar 2018'),
          expiration_date: Date.parse('Sun, 17 Mar 2019'),
          customer_email: nil,
          origin: "Gothenburg",
          country_origin: "Sweden",
          destination: "Shanghai",
          country_destination: "China",
          mot: "ocean",
          carrier: nil,
          service_level: "standard",
          load_type: "fcl_20_frs",
          rate_basis: "PER_CONTAINER",
          fee_code: "BAS",
          fee_name: "Bas",
          currency: "USD",
          fee_min: 1234,
          fee: 1234,
          row_nr: 5,
          origin_name: "Gothenburg Port",
          destination_name: "Shanghai Port"}],
        [{sheet_name: "Sheet1",
          data_restructurer_name: "pricing_one_col_fee_and_ranges",
          effective_date: Date.parse('Thu, 15 Mar 2018'),
          expiration_date: Date.parse('Sun, 17 Mar 2019'),
          customer_email: nil,
          origin: "Gothenburg",
          country_origin: "Sweden",
          destination: "Shanghai",
          country_destination: "China",
          mot: "ocean",
          carrier: nil,
          service_level: "standard",
          load_type: "fcl_20_frw",
          rate_basis: "PER_CONTAINER",
          fee_code: "BAS",
          fee_name: "Bas",
          currency: "USD",
          fee_min: 1234,
          fee: 1234,
          row_nr: 5,
          origin_name: "Gothenburg Port",
          destination_name: "Shanghai Port"}],
        [{sheet_name: "Sheet1",
          data_restructurer_name: "pricing_one_col_fee_and_ranges",
          effective_date: Date.parse('Thu, 15 Mar 2018'),
          expiration_date: Date.parse('Sun, 17 Mar 2019'),
          customer_email: nil,
          origin: "Gothenburg",
          country_origin: "Sweden",
          destination: "Shanghai",
          country_destination: "China",
          mot: "ocean",
          carrier: nil,
          service_level: "standard",
          load_type: "fcl_40",
          rate_basis: "PER_CONTAINER",
          fee_code: "BAS",
          fee_name: "Bas",
          currency: "USD",
          fee_min: 1234,
          fee: 1234,
          row_nr: 5,
          origin_name: "Gothenburg Port",
          destination_name: "Shanghai Port"}],
        [{sheet_name: "Sheet1",
          data_restructurer_name: "pricing_one_col_fee_and_ranges",
          effective_date: Date.parse('Thu, 15 Mar 2018'),
          expiration_date: Date.parse('Sun, 17 Mar 2019'),
          customer_email: nil,
          origin: "Gothenburg",
          country_origin: "Sweden",
          destination: "Shanghai",
          country_destination: "China",
          mot: "ocean",
          carrier: nil,
          service_level: "standard",
          load_type: "fcl_40_hq",
          rate_basis: "PER_CONTAINER",
          fee_code: "BAS",
          fee_name: "Bas",
          currency: "USD",
          fee_min: 1234,
          fee: 1234,
          row_nr: 5,
          origin_name: "Gothenburg Port",
          destination_name: "Shanghai Port"}],
        [{sheet_name: "Sheet1",
          data_restructurer_name: "pricing_one_col_fee_and_ranges",
          effective_date: Date.parse('Thu, 15 Mar 2018'),
          expiration_date: Date.parse('Sun, 17 Mar 2019'),
          customer_email: nil,
          origin: "Gothenburg",
          country_origin: "Sweden",
          destination: "Shanghai",
          country_destination: "China",
          mot: "ocean",
          carrier: nil,
          service_level: "standard",
          load_type: "fcl_40_ot",
          rate_basis: "PER_CONTAINER",
          fee_code: "BAS",
          fee_name: "Bas",
          currency: "USD",
          fee_min: 1234,
          fee: 1234,
          row_nr: 5,
          origin_name: "Gothenburg Port",
          destination_name: "Shanghai Port"}],
        [{sheet_name: "Sheet1",
          data_restructurer_name: "pricing_one_col_fee_and_ranges",
          effective_date: Date.parse('Thu, 15 Mar 2018'),
          expiration_date: Date.parse('Sun, 17 Mar 2019'),
          customer_email: nil,
          origin: "Gothenburg",
          country_origin: "Sweden",
          destination: "Shanghai",
          country_destination: "China",
          mot: "ocean",
          carrier: nil,
          service_level: "standard",
          load_type: "fcl_40_rf",
          rate_basis: "PER_CONTAINER",
          fee_code: "BAS",
          fee_name: "Bas",
          currency: "USD",
          fee_min: 1234,
          fee: 1234,
          row_nr: 5,
          origin_name: "Gothenburg Port",
          destination_name: "Shanghai Port"}],
        [{sheet_name: "Sheet1",
          data_restructurer_name: "pricing_one_col_fee_and_ranges",
          effective_date: Date.parse('Thu, 15 Mar 2018'),
          expiration_date: Date.parse('Sun, 17 Mar 2019'),
          customer_email: nil,
          origin: "Gothenburg",
          country_origin: "Sweden",
          destination: "Shanghai",
          country_destination: "China",
          mot: "ocean",
          carrier: nil,
          service_level: "standard",
          load_type: "fcl_40_frs",
          rate_basis: "PER_CONTAINER",
          fee_code: "BAS",
          fee_name: "Bas",
          currency: "USD",
          fee_min: 1234,
          fee: 1234,
          row_nr: 5,
          origin_name: "Gothenburg Port",
          destination_name: "Shanghai Port"}],
        [{sheet_name: "Sheet1",
          data_restructurer_name: "pricing_one_col_fee_and_ranges",
          effective_date: Date.parse('Thu, 15 Mar 2018'),
          expiration_date: Date.parse('Sun, 17 Mar 2019'),
          customer_email: nil,
          origin: "Gothenburg",
          country_origin: "Sweden",
          destination: "Shanghai",
          country_destination: "China",
          mot: "ocean",
          carrier: nil,
          service_level: "standard",
          load_type: "fcl_40_frw",
          rate_basis: "PER_CONTAINER",
          fee_code: "BAS",
          fee_name: "Bas",
          currency: "USD",
          fee_min: 1234,
          fee: 1234,
          row_nr: 5,
          origin_name: "Gothenburg Port",
          destination_name: "Shanghai Port"}],
        [{sheet_name: "Sheet1",
          data_restructurer_name: "pricing_one_col_fee_and_ranges",
          effective_date: Date.parse('Thu, 15 Mar 2018'),
          expiration_date: Date.parse('Sun, 17 Mar 2019'),
          customer_email: nil,
          origin: "Gothenburg",
          country_origin: "Sweden",
          destination: "Shanghai",
          country_destination: "China",
          mot: "ocean",
          carrier: nil,
          service_level: "standard",
          load_type: "fcl_45",
          rate_basis: "PER_CONTAINER",
          fee_code: "BAS",
          fee_name: "Bas",
          currency: "USD",
          fee_min: 1234,
          fee: 1234,
          row_nr: 5,
          origin_name: "Gothenburg Port",
          destination_name: "Shanghai Port"}],
        [{sheet_name: "Sheet1",
          data_restructurer_name: "pricing_one_col_fee_and_ranges",
          effective_date: Date.parse('Thu, 15 Mar 2018'),
          expiration_date: Date.parse('Sun, 17 Mar 2019'),
          customer_email: nil,
          origin: "Gothenburg",
          country_origin: "Sweden",
          destination: "Shanghai",
          country_destination: "China",
          mot: "ocean",
          carrier: nil,
          service_level: "standard",
          load_type: "fcl_45_hq",
          rate_basis: "PER_CONTAINER",
          fee_code: "BAS",
          fee_name: "Bas",
          currency: "USD",
          fee_min: 1234,
          fee: 1234,
          row_nr: 5,
          origin_name: "Gothenburg Port",
          destination_name: "Shanghai Port"}],
        [{sheet_name: "Sheet1",
          data_restructurer_name: "pricing_one_col_fee_and_ranges",
          effective_date: Date.parse('Thu, 15 Mar 2018'),
          expiration_date: Date.parse('Sun, 17 Mar 2019'),
          customer_email: nil,
          origin: "Gothenburg",
          country_origin: "Sweden",
          destination: "Shanghai",
          country_destination: "China",
          mot: "ocean",
          carrier: nil,
          service_level: "standard",
          load_type: "fcl_45_rf",
          rate_basis: "PER_CONTAINER",
          fee_code: "BAS",
          fee_name: "Bas",
          currency: "USD",
          fee_min: 1234,
          fee: 1234,
          row_nr: 5,
          origin_name: "Gothenburg Port",
          destination_name: "Shanghai Port"}]]
      end
    end

    trait :faulty_pricings_one_fee_col_and_ranges do
      data do
        [[{ sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Thu, 15 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: nil,
            origin: 'GothenERRORburg',
            origin_name: 'GothenERRORburg Port',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            destination_name: 'Shanghai Port',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'lcl',
            rate_basis: 'PER_WM',
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'USD',
            fee_min: 17,
            fee: 17,
            row_nr: 2 }],
         [{ sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Thu, 15 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: 'Non.Existent@email.address',
            origin: 'Gothenburg',
            origin_name: 'Gothenburg Port',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            destination_name: 'Shanghai Port',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'lcl',
            rate_basis: 'PER_WM',
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'USD',
            fee_min: 17,
            fee: 17,
            row_nr: 3 }]]
      end
    end

    trait :correct_pricings_dynamic_fee_cols_no_rangs do
      data do
        [[{ carrier: 'APL',
            country_destination: 'Sweden',
            country_origin: 'China',
            currency: 'USD',
            customer_email: nil,
            data_restructurer_name: 'pricing_dynamic_fee_cols_no_ranges',
            destination: 'Gothenburg',
            destination_name: 'Gothenburg Port',
            effective_date: Date.parse('Fri, 01 Feb 2019'),
            expiration_date: Date.parse('Sun, 31 Mar 2019'),
            fee: 60,
            fee_code: 'LSS',
            fee_min: 60,
            fee_name: 'Lss',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Dalian',
            origin_name: 'Dalian Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            service_level: 'standard',
            sheet_name: 'Sheet1',
            transit_time: 42 },
          { carrier: 'APL',
            country_destination: 'Sweden',
            country_origin: 'China',
            currency: 'USD',
            customer_email: nil,
            data_restructurer_name: 'pricing_dynamic_fee_cols_no_ranges',
            destination: 'Gothenburg',
            destination_name: 'Gothenburg Port',
            effective_date: Date.parse('Fri, 01 Feb 2019'),
            expiration_date: Date.parse('Sun, 31 Mar 2019'),
            fee: 1550,
            fee_code: 'RATE',
            fee_min: 1550,
            fee_name: 'Rate',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Dalian',
            origin_name: 'Dalian Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            service_level: 'standard',
            sheet_name: 'Sheet1',
            transit_time: 42 }],
         [{ carrier: 'YML',
            country_destination: 'United Kingdom of Great Britain and Northern Ireland',
            country_origin: 'Hong Kong',
            currency: 'USD',
            customer_email: nil,
            data_restructurer_name: 'pricing_dynamic_fee_cols_no_ranges',
            destination: 'Southampton',
            destination_name: 'Southampton Port',
            effective_date: Date.parse('Tue, 01 Jan 2019'),
            expiration_date: Date.parse('Sun, 31 Mar 2019'),
            fee: 60,
            fee_code: 'LSS',
            fee_min: 60,
            fee_name: 'Lss',
            load_type: 'fcl_40_hq',
            mot: 'ocean',
            origin: 'Hong Kong',
            origin_name: 'Hong Kong Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            service_level: 'standard',
            sheet_name: 'Sheet1',
            transit_time: 27 },
          { carrier: 'YML',
            country_destination: 'United Kingdom of Great Britain and Northern Ireland',
            country_origin: 'Hong Kong',
            currency: 'USD',
            customer_email: nil,
            data_restructurer_name: 'pricing_dynamic_fee_cols_no_ranges',
            destination: 'Southampton',
            destination_name: 'Southampton Port',
            effective_date: Date.parse('Tue, 01 Jan 2019'),
            expiration_date: Date.parse('Sun, 31 Mar 2019'),
            fee: 2550,
            fee_code: 'RATE',
            fee_min: 2550,
            fee_name: 'Rate',
            load_type: 'fcl_40_hq',
            mot: 'ocean',
            origin: 'Hong Kong',
            origin_name: 'Hong Kong Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            service_level: 'standard',
            sheet_name: 'Sheet1',
            transit_time: 27 }]]
      end
    end

    trait :correct_margins do
      data do
        [
          [{ sheet_name: 'Tabelle1',
             data_restructurer_name: 'margins',
             effective_date: Date.parse('Tue, 01 Jan 2019'),
             expiration_date: Date.parse('Sun, 31 Mar 2019'),
             origin: 'Dalian',
             country_origin: 'China',
             destination: 'Gothenburg',
             country_destination: 'Sweden',
             mot: 'ocean',
             carrier: 'Consolidation',
             service_level: 'standard',
             load_type: 'lcl',
             fee_code: 'BAS',
             operator: '%',
             margin: 0.1,
             row_nr: 2 }],
          [{ sheet_name: 'Tabelle1',
             data_restructurer_name: 'margins',
             effective_date: Date.parse('Mon, 01 Apr 2019'),
             expiration_date: Date.parse('Tue, 30 Apr 2019'),
             origin: 'Dalian',
             country_origin: 'China',
             destination: 'Gothenburg',
             country_destination: 'Sweden',
             mot: 'ocean',
             carrier: 'Consolidation',
             service_level: 'standard',
             load_type: 'lcl',
             fee_code: 'BAS',
             operator: '%',
             margin: 0.1,
             row_nr: 3 }],
          [{ sheet_name: 'Tabelle1',
             data_restructurer_name: 'margins',
             effective_date: Date.parse('Tue, 01 Jan 2019'),
             expiration_date: Date.parse('Sun, 31 Mar 2019'),
             origin: 'Ningbo',
             country_origin: 'China',
             destination: 'Gothenburg',
             country_destination: 'Sweden',
             mot: 'ocean',
             carrier: 'Consolidation',
             service_level: 'standard',
             load_type: 'lcl',
             fee_code: 'BAS',
             operator: '%',
             margin: 0.1,
             row_nr: 4 }],
          [{ sheet_name: 'Tabelle1',
             data_restructurer_name: 'margins',
             effective_date: Date.parse('Mon, 01 Apr 2019'),
             expiration_date: Date.parse('Tue, 30 Apr 2019'),
             origin: 'Ningbo',
             country_origin: 'China',
             destination: 'Gothenburg',
             country_destination: 'Sweden',
             mot: 'ocean',
             carrier: 'Consolidation',
             service_level: 'standard',
             load_type: 'lcl',
             fee_code: 'BAS',
             operator: '%',
             margin: 0.1,
             row_nr: 5 }]
        ]
      end
    end

    trait :correct_local_charges do
      data do
        [{ hub: 'Bremerhaven',
           country: 'Germany',
           effective_date: Date.parse('Thu, 24 Jan 2019'),
           expiration_date: Date.parse('Fri, 24 Jan 2020'),
           counterpart_hub: nil,
           counterpart_country: nil,
           service_level: 'standard',
           carrier: 'SACO Shipping',
           mot: 'ocean',
           row_nr: '2',
           load_type: 'lcl',
           direction: 'export',
           dangerous: nil,
           fees: { 'DOC' =>
            { currency: 'EUR',
              key: 'DOC',
              min: nil,
              max: nil,
              name: 'Documentation',
              rate_basis: 'PER_BILL',
              value: 20 } },
           hub_name: 'Bremerhaven Port',
           counterpart_hub_name: nil },
         { hub: 'Antwerp',
           country: 'Belgium',
           effective_date: Date.parse('Thu, 24 Jan 2019'),
           expiration_date: Date.parse('Fri, 24 Jan 2020'),
           counterpart_hub: 'all',
           counterpart_country: nil,
           service_level: 'all',
           carrier: 'SACO Shipping',
           mot: 'ocean',
           row_nr: '3',
           load_type: 'lcl',
           direction: 'export',
           dangerous: nil,
           fees: { 'DOC' =>
           { currency: 'EUR',
             key: 'DOC',
             min: nil,
             max: nil,
             name: 'Documentation',
             rate_basis: 'PER_BILL',
             range: [{ currency: 'EUR', max: 100, min: 0, value: 20 }] } },
           hub_name: 'Antwerp Port',
           counterpart_hub_name: nil },
         { hub: 'Le Havre',
           country: 'France',
           effective_date: Date.parse('Thu, 24 Jan 2019'),
           expiration_date: Date.parse('Fri, 24 Jan 2020'),
           counterpart_hub: 'Antwerp',
           counterpart_country: 'Belgium',
           service_level: 'standard',
           carrier: 'all',
           mot: 'ocean',
           row_nr: '4',
           load_type: 'lcl',
           direction: 'export',
           dangerous: nil,
           fees: { 'DOC' => 
            { currency: 'EUR',
              key: 'DOC',
              min: nil,
              max: nil,
              name: 'Documentation',
              rate_basis: 'PER_BILL',
              value: 20 } },
           hub_name: 'Le Havre Port',
           counterpart_hub_name: 'Antwerp Port' }]
      end
    end

    trait :faulty_local_charges do
      data do
        [
          { hub: 'Bremerhaven',
            country: 'Germany',
            mot: 'ocean',
            row_nr: '2',
            load_type: 'lcl',
            counterpart_hub_id: nil,
            direction: 'export',
            fees: { 'CMP':  { 'key':  'CMP', 'max':  nil, 'min':  nil, 'name':  'Compliance Fee', 'value':  2.7, 'currency':  'EUR', 'rate_basis':  'PER_SHIPMENT' },
                    'DOC' =>  { 'key':  'DOC', 'max':  nil, 'min':  nil, 'name':  'Documentation', 'value':  20, 'currency':  'EUR', 'rate_basis':  'PER_WRONG' },
                    'ISP':  { 'key':  'ISP', 'max':  nil, 'min':  nil, 'name':  'ISPS', 'value':  nil, 'currency':  'EUR', 'rate_basis':  'PER_SHIPMENT' },
                    'QDF':  { 'key':  'QDF', 'max':  125, 'min':  55, 'ton':  40, 'name':  'Quay dues', 'currency':  'EUR', 'rate_basis':  'PER_TON' },
                    'SOL':  { 'key':  'SOL', 'max':  nil, 'min':  nil, 'name':  'SOLAS Fee', 'value':  7.5, 'currency':  'EUR', 'rate_basis':  'PER_SHIPMENT' },
                    'ZAP':  { 'key':  'ZAP', 'max':  nil, 'min':  nil, 'name':  'Zapp', 'currency':  'EUR', 'rate_basis':  'PER_BILL' } },
            dangerous: nil,
            effective_date: Date.parse('Thu, 24 Jan 2019'),
            expiration_date: Date.parse('Fri, 24 Jan 2020'),
            hub_name: 'Bremerhaven Port',
            counterpart_hub_name: nil },
          { hub: 'BremerERRORhaven',
            country: 'Germany',
            mot: 'ocean',
            row_nr: '3',
            load_type: 'lcl',
            counterpart_hub_id: nil,
            direction: 'export',
            fees: {},
            dangerous: nil,
            effective_date: Date.parse('Thu, 24 Jan 2019'),
            expiration_date: Date.parse('Fri, 24 Jan 2020'),
            hub_name: 'BremerERRORhaven Port',
            counterpart_hub_name: nil }
        ]
      end
    end

    trait :correct_saco_shipping_pricings do
      data do
        [[{ carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: 'EUR',
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 2550,
            fee_code: 'BAS',
            fee_min: 2550,
            fee_name: 'Bas',
            klass_identifier: 'Pricing',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Antwerp',
            origin_name: 'Antwerp Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 0,
            fee_code: 'INCLUDED_LSF',
            fee_min: 0,
            fee_name: 'Lsf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Antwerp',
            origin_name: 'Antwerp Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 0,
            fee_code: 'INCLUDED_BAF',
            fee_min: 0,
            fee_name: 'Baf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Antwerp',
            origin_name: 'Antwerp Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 0,
            fee_code: 'INCLUDED_CAF',
            fee_min: 0,
            fee_name: 'Caf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Antwerp',
            origin_name: 'Antwerp Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: 'EUR',
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 45,
            fee_code: 'EBS',
            fee_min: 45,
            fee_name: 'Ebs',
            klass_identifier: 'Pricing',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Antwerp',
            origin_name: 'Antwerp Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            sheet_name: 'Sheet1' }],
         [{ carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: 'EUR',
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 4100,
            fee_code: 'BAS',
            fee_min: 4100,
            fee_name: 'Bas',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Antwerp',
            origin_name: 'Antwerp Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 0,
            fee_code: 'INCLUDED_LSF',
            fee_min: 0,
            fee_name: 'Lsf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Antwerp',
            origin_name: 'Antwerp Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 0,
            fee_code: 'INCLUDED_BAF',
            fee_min: 0,
            fee_name: 'Baf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Antwerp',
            origin_name: 'Antwerp Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 0,
            fee_code: 'INCLUDED_CAF',
            fee_min: 0,
            fee_name: 'Caf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Antwerp',
            origin_name: 'Antwerp Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: 'EUR',
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 90,
            fee_code: 'EBS',
            fee_min: 90,
            fee_name: 'Ebs',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Antwerp',
            origin_name: 'Antwerp Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            sheet_name: 'Sheet1' }],
         [{ carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: 'EUR',
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 4100,
            fee_code: 'BAS',
            fee_min: 4100,
            fee_name: 'Bas',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40_hq',
            mot: 'ocean',
            origin: 'Antwerp',
            origin_name: 'Antwerp Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            sheet_name: 'Sheet1' }],
         [{ carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            fee: 0,
            fee_code: 'INCLUDED_BAF',
            fee_min: 0,
            fee_name: 'Baf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: 'EUR',
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            fee: 2700,
            fee_code: 'BAS',
            fee_min: 2700,
            fee_name: 'Bas',
            klass_identifier: 'Pricing',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            fee: 0,
            fee_code: 'INCLUDED_LSF',
            fee_min: 0,
            fee_name: 'Lsf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            fee: 0,
            fee_code: 'INCLUDED_CAF',
            fee_min: 0,
            fee_name: 'Caf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: 'EUR',
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            fee: 45,
            fee_code: 'EBS',
            fee_min: 45,
            fee_name: 'Ebs',
            klass_identifier: 'Pricing',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' }],
         [{ carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 0,
            fee_code: 'INCLUDED_BAF',
            fee_min: 0,
            fee_name: 'Baf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: 'EUR',
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 2700,
            fee_code: 'BAS',
            fee_min: 2700,
            fee_name: 'Bas',
            klass_identifier: 'Pricing',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 0,
            fee_code: 'INCLUDED_LSF',
            fee_min: 0,
            fee_name: 'Lsf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 0,
            fee_code: 'INCLUDED_CAF',
            fee_min: 0,
            fee_name: 'Caf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: 'EUR',
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 45,
            fee_code: 'EBS',
            fee_min: 45,
            fee_name: 'Ebs',
            klass_identifier: 'Pricing',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' }],
         [{ carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: 'EUR',
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            fee: 4400,
            fee_code: 'BAS',
            fee_min: 4400,
            fee_name: 'Bas',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            fee: 0,
            fee_code: 'INCLUDED_LSF',
            fee_min: 0,
            fee_name: 'Lsf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            fee: 0,
            fee_code: 'INCLUDED_BAF',
            fee_min: 0,
            fee_name: 'Baf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            fee: 0,
            fee_code: 'INCLUDED_CAF',
            fee_min: 0,
            fee_name: 'Caf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: 'EUR',
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            fee: 90,
            fee_code: 'EBS',
            fee_min: 90,
            fee_name: 'Ebs',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' }],
         [{ carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: 'EUR',
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 4400,
            fee_code: 'BAS',
            fee_min: 4400,
            fee_name: 'Bas',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 0,
            fee_code: 'INCLUDED_LSF',
            fee_min: 0,
            fee_name: 'Lsf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 0,
            fee_code: 'INCLUDED_BAF',
            fee_min: 0,
            fee_name: 'Baf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 0,
            fee_code: 'INCLUDED_CAF',
            fee_min: 0,
            fee_name: 'Caf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: 'EUR',
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 90,
            fee_code: 'EBS',
            fee_min: 90,
            fee_name: 'Ebs',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' }],
         [{ carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: 'EUR',
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            fee: 4400,
            fee_code: 'BAS',
            fee_min: 4400,
            fee_name: 'Bas',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40_hq',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' }],
         [{ carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: 'EUR',
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 4400,
            fee_code: 'BAS',
            fee_min: 4400,
            fee_name: 'Bas',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40_hq',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' }]]
      end
    end

    trait :correct_saco_shipping_local_charges do
      data do
          [{carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_20",
            hub: "Antwerp",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            direction: "export",
            service_level: "standard",
            hub_name: "Antwerp Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"THC" => {currency: "EUR", key: "THC", min: 192, max: nil, name: "Thc", rate_basis: "PER_CONTAINER", value: 192}},
            row_nr: "2"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_40",
            hub: "Antwerp",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            direction: "export",
            service_level: "standard",
            hub_name: "Antwerp Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"THC" => {currency: "EUR", key: "THC", min: 192, max: nil, name: "Thc", rate_basis: "PER_CONTAINER", value: 192}},
            row_nr: "2"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_20",
            hub: "Antwerp",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            direction: "import",
            service_level: "standard",
            hub_name: "Antwerp Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"THC" => {currency: "EUR", key: "THC", min: 111, max: nil, name: "Thc", rate_basis: "PER_CONTAINER", value: 111}},
            row_nr: "2"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_10",
            hub: "Antwerp",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Antwerp Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "2"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_20",
            hub: "Antwerp",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Antwerp Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "2"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_20_ot",
            hub: "Antwerp",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Antwerp Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "2"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_20_rf",
            hub: "Antwerp",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Antwerp Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "2"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_20_frs",
            hub: "Antwerp",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Antwerp Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "2"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_20_frw",
            hub: "Antwerp",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Antwerp Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "2"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_40",
            hub: "Antwerp",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Antwerp Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "2"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_40_hq",
            hub: "Antwerp",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Antwerp Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "2"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_40_ot",
            hub: "Antwerp",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Antwerp Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "2"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_40_rf",
            hub: "Antwerp",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Antwerp Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "2"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_40_frs",
            hub: "Antwerp",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Antwerp Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "2"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_40_frw",
            hub: "Antwerp",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Antwerp Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "2"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_45",
            hub: "Antwerp",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Antwerp Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "2"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_45_hq",
            hub: "Antwerp",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Antwerp Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "2"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_45_rf",
            hub: "Antwerp",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Antwerp Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "2"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            mot: "ocean",
            load_type: "fcl_20",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            direction: "export",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"THC" => {currency: "EUR", key: "THC", min: 230, max: nil, name: "Thc", rate_basis: "PER_CONTAINER", value: 230}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_20",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            direction: "export",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"THC" => {currency: "EUR", key: "THC", min: 230, max: nil, name: "Thc", rate_basis: "PER_CONTAINER", value: 230}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            mot: "ocean",
            load_type: "fcl_40",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            direction: "export",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"THC" => {currency: "EUR", key: "THC", min: 230, max: nil, name: "Thc", rate_basis: "PER_CONTAINER", value: 230}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_40",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            direction: "export",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"THC" => {currency: "EUR", key: "THC", min: 230, max: nil, name: "Thc", rate_basis: "PER_CONTAINER", value: 230}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            mot: "ocean",
            load_type: "fcl_10",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            mot: "ocean",
            load_type: "fcl_20",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            mot: "ocean",
            load_type: "fcl_20_ot",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            mot: "ocean",
            load_type: "fcl_20_rf",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            mot: "ocean",
            load_type: "fcl_20_frs",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            mot: "ocean",
            load_type: "fcl_20_frw",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            mot: "ocean",
            load_type: "fcl_40",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            mot: "ocean",
            load_type: "fcl_40_hq",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            mot: "ocean",
            load_type: "fcl_40_ot",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            mot: "ocean",
            load_type: "fcl_40_rf",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            mot: "ocean",
            load_type: "fcl_40_frs",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            mot: "ocean",
            load_type: "fcl_40_frw",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            mot: "ocean",
            load_type: "fcl_45",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            mot: "ocean",
            load_type: "fcl_45_hq",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            mot: "ocean",
            load_type: "fcl_45_rf",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_10",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_20",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_20_ot",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_20_rf",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_20_frs",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_20_frw",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_40",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_40_hq",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_40_ot",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_40_rf",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_40_frs",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_40_frw",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_45",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_45_hq",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "3"},
           {carrier: "CMA CGM",
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            mot: "ocean",
            load_type: "fcl_45_rf",
            hub: "Hamburg",
            country: nil,
            counterpart_hub: "Cabinda",
            counterpart_country: "Angola",
            service_level: "standard",
            hub_name: "Hamburg Port",
            counterpart_hub_name: "Cabinda Port",
            fees: {"ISPS" => {currency: "EUR", key: "ISPS", min: 27, max: nil, name: "Isps", rate_basis: "PER_CONTAINER", value: 27}},
            row_nr: "3"}]
      end
    end

    factory :excel_data_restructured_correct_pricings_one_fee_col_and_ranges, traits: %i(correct_pricings_one_fee_col_and_ranges)
    factory :excel_data_restructured_faulty_pricings_one_fee_col_and_ranges, traits: %i(faulty_pricings_one_fee_col_and_ranges)
    factory :excel_data_restructured_correct_pricings_dynamic_fee_cols_no_rangs, traits: %i(correct_pricings_dynamic_fee_cols_no_rangs)
    factory :excel_data_restructured_correct_margins, traits: %i(correct_margins)
    factory :excel_data_restructured_correct_local_charges, traits: %i(correct_local_charges)
    factory :excel_data_restructured_faulty_local_charges, traits: %i(faulty_local_charges)
    factory :excel_data_restructured_correct_saco_shipping_pricings, traits: %i(correct_saco_shipping_pricings)
    factory :excel_data_restructured_correct_saco_shipping_local_charges, traits: %i(correct_saco_shipping_local_charges)
  end
end
