# frozen_string_literal: true

FactoryBot.define do
  factory :excel_data_restructured, class: 'Array' do
    initialize_with { attributes[:data].deep_dup }

    trait :correct_pricings_one_fee_col_and_ranges do
      data do
        [[{ carrier: nil,
            country_destination: 'China',
            country_origin: 'Sweden',
            currency: 'USD',
            customer_email: nil,
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            destination: 'Shanghai',
            destination_name: 'Shanghai Port',
            effective_date: Date.parse('Thu, 15 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            fee: 17,
            fee_code: 'BAS',
            fee_min: 17,
            fee_name: 'Bas',
            load_type: 'lcl',
            mot: 'ocean',
            origin: 'Gothenburg',
            origin_name: 'Gothenburg Port',
            rate_basis: 'PER_WM',
            row_nr: 2,
            service_level: 'standard',
            sheet_name: 'Sheet1' }],
         [{ carrier: nil,
            country_destination: 'China',
            country_origin: 'Sweden',
            currency: 'USD',
            customer_email: nil,
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            destination: 'Shanghai',
            destination_name: 'Shanghai Port',
            effective_date: Date.parse('Sun, 11 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            fee: 17,
            fee_code: 'BAS',
            fee_min: 17,
            fee_name: 'Bas',
            load_type: 'lcl',
            mot: 'ocean',
            origin: 'Gothenburg',
            origin_name: 'Gothenburg Port',
            rate_basis: 'PER_WM',
            row_nr: 2,
            service_level: 'standard',
            sheet_name: 'Sheet1' },
          { carrier: nil,
            country_destination: 'China',
            country_origin: 'Sweden',
            currency: 'USD',
            customer_email: nil,
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            destination: 'Shanghai',
            destination_name: 'Shanghai Port',
            effective_date: Date.parse('Sun, 11 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            fee_code: 'HAS',
            fee_min: 20,
            fee_name: 'Has',
            load_type: 'lcl',
            mot: 'ocean',
            origin: 'Gothenburg',
            origin_name: 'Gothenburg Port',
            range: [{ 'max' => 100, 'min' => 0, 'rate' => 20 },
                    { 'max' => 500, 'min' => 101, 'rate' => 25 }],
            rate_basis: 'PER_WM',
            row_nr: 3,
            service_level: 'standard',
            sheet_name: 'Sheet1' }],
         [{ carrier: nil,
            country_destination: 'China',
            country_origin: 'Sweden',
            currency: 'USD',
            customer_email: nil,
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            destination: 'Shanghai',
            destination_name: 'Shanghai Port',
            effective_date: Date.parse('Thu, 15 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            fee: 1234,
            fee_code: 'BAS',
            fee_min: 1234,
            fee_name: 'Bas',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Gothenburg',
            origin_name: 'Gothenburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 5,
            service_level: 'standard',
            sheet_name: 'Sheet1' }],
         [{ carrier: nil,
            country_destination: 'China',
            country_origin: 'Sweden',
            currency: 'USD',
            customer_email: nil,
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            destination: 'Shanghai',
            destination_name: 'Shanghai Port',
            effective_date: Date.parse('Thu, 15 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            fee: 1234,
            fee_code: 'BAS',
            fee_min: 1234,
            fee_name: 'Bas',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Gothenburg',
            origin_name: 'Gothenburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 5,
            service_level: 'standard',
            sheet_name: 'Sheet1' }],
         [{ carrier: nil,
            country_destination: 'China',
            country_origin: 'Sweden',
            currency: 'USD',
            customer_email: nil,
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            destination: 'Shanghai',
            destination_name: 'Shanghai Port',
            effective_date: Date.parse('Thu, 15 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            fee: 1234,
            fee_code: 'BAS',
            fee_min: 1234,
            fee_name: 'Bas',
            load_type: 'fcl_40_hq',
            mot: 'ocean',
            origin: 'Gothenburg',
            origin_name: 'Gothenburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 5,
            service_level: 'standard',
            sheet_name: 'Sheet1' }]]
      end
    end

    trait :faulty_pricings_one_fee_col_and_ranges do
      data do
        [[{ sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Thu, 15 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: nil,
            origin: 'GothenERRORburg',
            origin_name: 'GothenERRORburg Port',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            destination_name: 'Shanghai Port',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'lcl',
            rate_basis: 'PER_WM',
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'USD',
            fee_min: 17,
            fee: 17,
            row_nr: 2 }],
         [{ sheet_name: 'Sheet1',
            data_restructurer_name: 'pricing_one_col_fee_and_ranges',
            effective_date: Date.parse('Thu, 15 Mar 2018'),
            expiration_date: Date.parse('Sun, 17 Mar 2019'),
            customer_email: 'Non.Existent@email.address',
            origin: 'Gothenburg',
            origin_name: 'Gothenburg Port',
            country_origin: 'Sweden',
            destination: 'Shanghai',
            destination_name: 'Shanghai Port',
            country_destination: 'China',
            mot: 'ocean',
            carrier: nil,
            service_level: 'standard',
            load_type: 'lcl',
            rate_basis: 'PER_WM',
            fee_code: 'BAS',
            fee_name: 'Bas',
            currency: 'USD',
            fee_min: 17,
            fee: 17,
            row_nr: 3 }]]
      end
    end

    trait :correct_pricings_dynamic_fee_cols_no_rangs do
      data do
        [[{ carrier: 'APL',
            country_destination: 'Sweden',
            country_origin: 'China',
            currency: 'USD',
            customer_email: nil,
            data_restructurer_name: 'pricing_dynamic_fee_cols_no_ranges',
            destination: 'Gothenburg',
            destination_name: 'Gothenburg Port',
            effective_date: Date.parse('Fri, 01 Feb 2019'),
            expiration_date: Date.parse('Sun, 31 Mar 2019'),
            fee: 60,
            fee_code: 'LSS',
            fee_min: 60,
            fee_name: 'Lss',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Dalian',
            origin_name: 'Dalian Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            service_level: 'standard',
            sheet_name: 'Sheet1',
            transit_time: 42 },
          { carrier: 'APL',
            country_destination: 'Sweden',
            country_origin: 'China',
            currency: 'USD',
            customer_email: nil,
            data_restructurer_name: 'pricing_dynamic_fee_cols_no_ranges',
            destination: 'Gothenburg',
            destination_name: 'Gothenburg Port',
            effective_date: Date.parse('Fri, 01 Feb 2019'),
            expiration_date: Date.parse('Sun, 31 Mar 2019'),
            fee: 1550,
            fee_code: 'RATE',
            fee_min: 1550,
            fee_name: 'Rate',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Dalian',
            origin_name: 'Dalian Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            service_level: 'standard',
            sheet_name: 'Sheet1',
            transit_time: 42 }],
         [{ carrier: 'YML',
            country_destination: 'United Kingdom of Great Britain and Northern Ireland',
            country_origin: 'Hong Kong',
            currency: 'USD',
            customer_email: nil,
            data_restructurer_name: 'pricing_dynamic_fee_cols_no_ranges',
            destination: 'Southampton',
            destination_name: 'Southampton Port',
            effective_date: Date.parse('Tue, 01 Jan 2019'),
            expiration_date: Date.parse('Sun, 31 Mar 2019'),
            fee: 60,
            fee_code: 'LSS',
            fee_min: 60,
            fee_name: 'Lss',
            load_type: 'fcl_40_hq',
            mot: 'ocean',
            origin: 'Hong Kong',
            origin_name: 'Hong Kong Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            service_level: 'standard',
            sheet_name: 'Sheet1',
            transit_time: 27 },
          { carrier: 'YML',
            country_destination: 'United Kingdom of Great Britain and Northern Ireland',
            country_origin: 'Hong Kong',
            currency: 'USD',
            customer_email: nil,
            data_restructurer_name: 'pricing_dynamic_fee_cols_no_ranges',
            destination: 'Southampton',
            destination_name: 'Southampton Port',
            effective_date: Date.parse('Tue, 01 Jan 2019'),
            expiration_date: Date.parse('Sun, 31 Mar 2019'),
            fee: 2550,
            fee_code: 'RATE',
            fee_min: 2550,
            fee_name: 'Rate',
            load_type: 'fcl_40_hq',
            mot: 'ocean',
            origin: 'Hong Kong',
            origin_name: 'Hong Kong Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            service_level: 'standard',
            sheet_name: 'Sheet1',
            transit_time: 27 }]]
      end
    end

    trait :correct_local_charges do
      data do
        [{ hub: 'Bremerhaven',
           country: 'Germany',
           effective_date: Date.parse('Thu, 24 Jan 2019'),
           expiration_date: Date.parse('Fri, 24 Jan 2020'),
           counterpart_hub: nil,
           counterpart_country: nil,
           service_level: 'standard',
           carrier: 'SACO Shipping',
           mot: 'ocean',
           row_nr: '2',
           load_type: 'lcl',
           direction: 'export',
           dangerous: nil,
           fees: { 'DOC' =>
            { currency: 'EUR',
              key: 'DOC',
              min: nil,
              max: nil,
              name: 'Documentation',
              rate_basis: 'PER_BILL',
              value: 20 } },
           hub_name: 'Bremerhaven Port',
           counterpart_hub_name: nil },
         { hub: 'Antwerp',
           country: 'Belgium',
           effective_date: Date.parse('Thu, 24 Jan 2019'),
           expiration_date: Date.parse('Fri, 24 Jan 2020'),
           counterpart_hub: 'all',
           counterpart_country: nil,
           service_level: 'all',
           carrier: 'SACO Shipping',
           mot: 'ocean',
           row_nr: '3',
           load_type: 'lcl',
           direction: 'export',
           dangerous: nil,
           fees: { 'DOC' =>
           { currency: 'EUR',
             key: 'DOC',
             min: nil,
             max: nil,
             name: 'Documentation',
             rate_basis: 'PER_BILL',
             range: [{ currency: 'EUR', max: 100, min: 0, value: 20 }] } },
           hub_name: 'Antwerp Port',
           counterpart_hub_name: nil },
         { hub: 'Le Havre',
           country: 'France',
           effective_date: Date.parse('Thu, 24 Jan 2019'),
           expiration_date: Date.parse('Fri, 24 Jan 2020'),
           counterpart_hub: 'Antwerp',
           counterpart_country: 'Belgium',
           service_level: 'standard',
           carrier: 'all',
           mot: 'ocean',
           row_nr: '4',
           load_type: 'lcl',
           direction: 'export',
           dangerous: nil,
           fees: { 'DOC' =>
            { currency: 'EUR',
              key: 'DOC',
              min: nil,
              max: nil,
              name: 'Documentation',
              rate_basis: 'PER_BILL',
              value: 20 } },
           hub_name: 'Le Havre Port',
           counterpart_hub_name: 'Antwerp Port' }]
      end
    end

    trait :faulty_local_charges do
      data do
        [
          { hub: 'Bremerhaven',
            country: 'Germany',
            mot: 'ocean',
            row_nr: '2',
            load_type: 'lcl',
            counterpart_hub_id: nil,
            direction: 'export',
            fees: { 'CMP' => { 'key' => 'CMP', 'max' => nil, 'min' => nil, 'name' => 'Compliance Fee', 'value' => 2.7, 'currency' => 'EUR', 'rate_basis' => 'PER_SHIPMENT' },
                    'DOC' => { 'key' => 'DOC', 'max' => nil, 'min' => nil, 'name' => 'Documentation', 'value' => 20, 'currency' => 'EUR', 'rate_basis' => 'PER_WRONG' },
                    'ISP' => { 'key' => 'ISP', 'max' => nil, 'min' => nil, 'name' => 'ISPS', 'value' => nil, 'currency' => 'EUR', 'rate_basis' => 'PER_SHIPMENT' },
                    'QDF' => { 'key' => 'QDF', 'max' => 125, 'min' => 55, 'ton' => 40, 'name' => 'Quay dues', 'currency' => 'EUR', 'rate_basis' => 'PER_TON' },
                    'SOL' => { 'key' => 'SOL', 'max' => nil, 'min' => nil, 'name' => 'SOLAS Fee', 'value' => 7.5, 'currency' => 'EUR', 'rate_basis' => 'PER_SHIPMENT' },
                    'ZAP' => { 'key' => 'ZAP', 'max' => nil, 'min' => nil, 'name' => 'Zapp', 'currency' => 'EUR', 'rate_basis' => 'PER_BILL' } },
            dangerous: nil,
            effective_date: Date.parse('Thu, 24 Jan 2019'),
            expiration_date: Date.parse('Fri, 24 Jan 2020'),
            hub_name: 'Bremerhaven Port',
            counterpart_hub_name: nil },
          { hub: 'BremerERRORhaven',
            country: 'Germany',
            mot: 'ocean',
            row_nr: '3',
            load_type: 'lcl',
            counterpart_hub_id: nil,
            direction: 'export',
            fees: {},
            dangerous: nil,
            effective_date: Date.parse('Thu, 24 Jan 2019'),
            expiration_date: Date.parse('Fri, 24 Jan 2020'),
            hub_name: 'BremerERRORhaven Port',
            counterpart_hub_name: nil }
        ]
      end
    end

    trait :correct_saco_shipping_pricings do
      data do
        [[{ carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: 'EUR',
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 2550,
            fee_code: 'BAS',
            fee_min: 2550,
            fee_name: 'Bas',
            klass_identifier: 'Pricing',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Antwerp',
            origin_name: 'Antwerp Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 0,
            fee_code: 'UNKNOWN_LSF',
            fee_min: 0,
            fee_name: 'Lsf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Antwerp',
            origin_name: 'Antwerp Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 0,
            fee_code: 'UNKNOWN_BAF',
            fee_min: 0,
            fee_name: 'Baf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Antwerp',
            origin_name: 'Antwerp Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 0,
            fee_code: 'UNKNOWN_CAF',
            fee_min: 0,
            fee_name: 'Caf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Antwerp',
            origin_name: 'Antwerp Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: 'EUR',
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 45,
            fee_code: 'EBS',
            fee_min: 45,
            fee_name: 'Ebs',
            klass_identifier: 'Pricing',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Antwerp',
            origin_name: 'Antwerp Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            sheet_name: 'Sheet1' }],
         [{ carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: 'EUR',
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 4100,
            fee_code: 'BAS',
            fee_min: 4100,
            fee_name: 'Bas',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Antwerp',
            origin_name: 'Antwerp Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 0,
            fee_code: 'UNKNOWN_LSF',
            fee_min: 0,
            fee_name: 'Lsf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Antwerp',
            origin_name: 'Antwerp Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 0,
            fee_code: 'UNKNOWN_BAF',
            fee_min: 0,
            fee_name: 'Baf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Antwerp',
            origin_name: 'Antwerp Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 0,
            fee_code: 'UNKNOWN_CAF',
            fee_min: 0,
            fee_name: 'Caf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Antwerp',
            origin_name: 'Antwerp Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: 'EUR',
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 90,
            fee_code: 'EBS',
            fee_min: 90,
            fee_name: 'Ebs',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Antwerp',
            origin_name: 'Antwerp Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            sheet_name: 'Sheet1' }],
         [{ carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: 'EUR',
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 4100,
            fee_code: 'BAS',
            fee_min: 4100,
            fee_name: 'Bas',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40_hq',
            mot: 'ocean',
            origin: 'Antwerp',
            origin_name: 'Antwerp Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 2,
            sheet_name: 'Sheet1' }],
         [{ carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            fee: 0,
            fee_code: 'UNKNOWN_BAF',
            fee_min: 0,
            fee_name: 'Baf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: 'EUR',
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            fee: 2700,
            fee_code: 'BAS',
            fee_min: 2700,
            fee_name: 'Bas',
            klass_identifier: 'Pricing',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            fee: 0,
            fee_code: 'UNKNOWN_LSF',
            fee_min: 0,
            fee_name: 'Lsf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            fee: 0,
            fee_code: 'UNKNOWN_CAF',
            fee_min: 0,
            fee_name: 'Caf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: 'EUR',
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            fee: 45,
            fee_code: 'EBS',
            fee_min: 45,
            fee_name: 'Ebs',
            klass_identifier: 'Pricing',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' }],
         [{ carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 0,
            fee_code: 'UNKNOWN_BAF',
            fee_min: 0,
            fee_name: 'Baf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: 'EUR',
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 2700,
            fee_code: 'BAS',
            fee_min: 2700,
            fee_name: 'Bas',
            klass_identifier: 'Pricing',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 0,
            fee_code: 'UNKNOWN_LSF',
            fee_min: 0,
            fee_name: 'Lsf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 0,
            fee_code: 'UNKNOWN_CAF',
            fee_min: 0,
            fee_name: 'Caf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: 'EUR',
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 45,
            fee_code: 'EBS',
            fee_min: 45,
            fee_name: 'Ebs',
            klass_identifier: 'Pricing',
            load_type: 'fcl_20',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' }],
         [{ carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: 'EUR',
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            fee: 4400,
            fee_code: 'BAS',
            fee_min: 4400,
            fee_name: 'Bas',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            fee: 0,
            fee_code: 'UNKNOWN_LSF',
            fee_min: 0,
            fee_name: 'Lsf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            fee: 0,
            fee_code: 'UNKNOWN_BAF',
            fee_min: 0,
            fee_name: 'Baf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            fee: 0,
            fee_code: 'UNKNOWN_CAF',
            fee_min: 0,
            fee_name: 'Caf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: 'EUR',
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            fee: 90,
            fee_code: 'EBS',
            fee_min: 90,
            fee_name: 'Ebs',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' }],
         [{ carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: 'EUR',
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 4400,
            fee_code: 'BAS',
            fee_min: 4400,
            fee_name: 'Bas',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 0,
            fee_code: 'UNKNOWN_LSF',
            fee_min: 0,
            fee_name: 'Lsf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 0,
            fee_code: 'UNKNOWN_BAF',
            fee_min: 0,
            fee_name: 'Baf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: nil,
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 0,
            fee_code: 'UNKNOWN_CAF',
            fee_min: 0,
            fee_name: 'Caf (included)',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' },
          { carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: 'EUR',
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 90,
            fee_code: 'EBS',
            fee_min: 90,
            fee_name: 'Ebs',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' }],
         [{ carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: 'EUR',
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Thu, 01 Nov 2018'),
            expiration_date: Date.parse('Fri, 30 Nov 2018'),
            fee: 4400,
            fee_code: 'BAS',
            fee_min: 4400,
            fee_name: 'Bas',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40_hq',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' }],
         [{ carrier: 'CMA CGM',
            country_destination: 'Angola',
            country_origin: nil,
            currency: 'EUR',
            data_restructurer_name: 'saco_shipping',
            destination: 'Cabinda',
            destination_name: 'Cabinda Port',
            effective_date: Date.parse('Sat, 01 Dec 2018'),
            expiration_date: Date.parse('Mon, 31 Dec 2018'),
            fee: 4400,
            fee_code: 'BAS',
            fee_min: 4400,
            fee_name: 'Bas',
            klass_identifier: 'Pricing',
            load_type: 'fcl_40_hq',
            mot: 'ocean',
            origin: 'Hamburg',
            origin_name: 'Hamburg Port',
            rate_basis: 'PER_CONTAINER',
            row_nr: 3,
            sheet_name: 'Sheet1' }]]
      end
    end

    trait :correct_saco_shipping_local_charges do
      data do
        [{ carrier: 'CMA CGM',
           counterpart_country: 'Angola',
           counterpart_hub: 'Cabinda',
           counterpart_hub_name: 'Cabinda Port',
           country: nil,
           direction: 'export',
           effective_date: Date.parse('Thu, 01 Nov 2018'),
           expiration_date: Date.parse('Mon, 31 Dec 2018'),
           fees: { 'THC' => { currency: 'EUR',
                              key: 'THC',
                              max: nil,
                              min: 192,
                              name: 'Thc',
                              rate_basis: 'PER_CONTAINER',
                              value: 192 } },
           hub: 'Antwerp',
           hub_name: 'Antwerp Port',
           load_type: 'fcl_20',
           mot: 'ocean',
           row_nr: '2',
           service_level: 'standard' },
         { carrier: 'CMA CGM',
           counterpart_country: 'Angola',
           counterpart_hub: 'Cabinda',
           counterpart_hub_name: 'Cabinda Port',
           country: nil,
           direction: 'export',
           effective_date: Date.parse('Thu, 01 Nov 2018'),
           expiration_date: Date.parse('Mon, 31 Dec 2018'),
           fees: { 'THC' => { currency: 'EUR',
                              key: 'THC',
                              max: nil,
                              min: 192,
                              name: 'Thc',
                              rate_basis: 'PER_CONTAINER',
                              value: 192 } },
           hub: 'Antwerp',
           hub_name: 'Antwerp Port',
           load_type: 'fcl_40',
           mot: 'ocean',
           row_nr: '2',
           service_level: 'standard' },
         { carrier: 'CMA CGM',
           counterpart_country: 'Angola',
           counterpart_hub: 'Cabinda',
           counterpart_hub_name: 'Cabinda Port',
           country: nil,
           direction: 'import',
           effective_date: Date.parse('Thu, 01 Nov 2018'),
           expiration_date: Date.parse('Mon, 31 Dec 2018'),
           fees: { 'THC' => { currency: 'EUR',
                              key: 'THC',
                              max: nil,
                              min: 111,
                              name: 'Thc',
                              rate_basis: 'PER_CONTAINER',
                              value: 111 } },
           hub: 'Antwerp',
           hub_name: 'Antwerp Port',
           load_type: 'fcl_20',
           mot: 'ocean',
           row_nr: '2',
           service_level: 'standard' },
         { carrier: 'CMA CGM',
           counterpart_country: 'Angola',
           counterpart_hub: 'Cabinda',
           counterpart_hub_name: 'Cabinda Port',
           country: nil,
           effective_date: Date.parse('Thu, 01 Nov 2018'),
           expiration_date: Date.parse('Mon, 31 Dec 2018'),
           fees: { 'ISPS' => { currency: 'EUR',
                               key: 'ISPS',
                               max: nil,
                               min: 27,
                               name: 'Isps',
                               rate_basis: 'PER_CONTAINER',
                               value: 27 } },
           hub: 'Antwerp',
           hub_name: 'Antwerp Port',
           load_type: 'fcl_20',
           mot: 'ocean',
           row_nr: '2',
           service_level: 'standard' },
         { carrier: 'CMA CGM',
           counterpart_country: 'Angola',
           counterpart_hub: 'Cabinda',
           counterpart_hub_name: 'Cabinda Port',
           country: nil,
           effective_date: Date.parse('Thu, 01 Nov 2018'),
           expiration_date: Date.parse('Mon, 31 Dec 2018'),
           fees: { 'ISPS' => { currency: 'EUR',
                               key: 'ISPS',
                               max: nil,
                               min: 27,
                               name: 'Isps',
                               rate_basis: 'PER_CONTAINER',
                               value: 27 } },
           hub: 'Antwerp',
           hub_name: 'Antwerp Port',
           load_type: 'fcl_40',
           mot: 'ocean',
           row_nr: '2',
           service_level: 'standard' },
         { carrier: 'CMA CGM',
           counterpart_country: 'Angola',
           counterpart_hub: 'Cabinda',
           counterpart_hub_name: 'Cabinda Port',
           country: nil,
           effective_date: Date.parse('Thu, 01 Nov 2018'),
           expiration_date: Date.parse('Mon, 31 Dec 2018'),
           fees: { 'ISPS' => { currency: 'EUR',
                               key: 'ISPS',
                               max: nil,
                               min: 27,
                               name: 'Isps',
                               rate_basis: 'PER_CONTAINER',
                               value: 27 } },
           hub: 'Antwerp',
           hub_name: 'Antwerp Port',
           load_type: 'fcl_40_hq',
           mot: 'ocean',
           row_nr: '2',
           service_level: 'standard' },
         { carrier: 'CMA CGM',
           counterpart_country: 'Angola',
           counterpart_hub: 'Cabinda',
           counterpart_hub_name: 'Cabinda Port',
           country: nil,
           direction: 'export',
           effective_date: Date.parse('Thu, 01 Nov 2018'),
           expiration_date: Date.parse('Fri, 30 Nov 2018'),
           fees: { 'THC' => { currency: 'EUR',
                              key: 'THC',
                              max: nil,
                              min: 230,
                              name: 'Thc',
                              rate_basis: 'PER_CONTAINER',
                              value: 230 } },
           hub: 'Hamburg',
           hub_name: 'Hamburg Port',
           load_type: 'fcl_20',
           mot: 'ocean',
           row_nr: '3',
           service_level: 'standard' },
         { carrier: 'CMA CGM',
           counterpart_country: 'Angola',
           counterpart_hub: 'Cabinda',
           counterpart_hub_name: 'Cabinda Port',
           country: nil,
           direction: 'export',
           effective_date: Date.parse('Sat, 01 Dec 2018'),
           expiration_date: Date.parse('Mon, 31 Dec 2018'),
           fees: { 'THC' => { currency: 'EUR',
                              key: 'THC',
                              max: nil,
                              min: 230,
                              name: 'Thc',
                              rate_basis: 'PER_CONTAINER',
                              value: 230 } },
           hub: 'Hamburg',
           hub_name: 'Hamburg Port',
           load_type: 'fcl_20',
           mot: 'ocean',
           row_nr: '3',
           service_level: 'standard' },
         { carrier: 'CMA CGM',
           counterpart_country: 'Angola',
           counterpart_hub: 'Cabinda',
           counterpart_hub_name: 'Cabinda Port',
           country: nil,
           direction: 'export',
           effective_date: Date.parse('Thu, 01 Nov 2018'),
           expiration_date: Date.parse('Fri, 30 Nov 2018'),
           fees: { 'THC' => { currency: 'EUR',
                              key: 'THC',
                              max: nil,
                              min: 230,
                              name: 'Thc',
                              rate_basis: 'PER_CONTAINER',
                              value: 230 } },
           hub: 'Hamburg',
           hub_name: 'Hamburg Port',
           load_type: 'fcl_40',
           mot: 'ocean',
           row_nr: '3',
           service_level: 'standard' },
         { carrier: 'CMA CGM',
           counterpart_country: 'Angola',
           counterpart_hub: 'Cabinda',
           counterpart_hub_name: 'Cabinda Port',
           country: nil,
           direction: 'export',
           effective_date: Date.parse('Sat, 01 Dec 2018'),
           expiration_date: Date.parse('Mon, 31 Dec 2018'),
           fees: { 'THC' => { currency: 'EUR',
                              key: 'THC',
                              max: nil,
                              min: 230,
                              name: 'Thc',
                              rate_basis: 'PER_CONTAINER',
                              value: 230 } },
           hub: 'Hamburg',
           hub_name: 'Hamburg Port',
           load_type: 'fcl_40',
           mot: 'ocean',
           row_nr: '3',
           service_level: 'standard' },
         { carrier: 'CMA CGM',
           counterpart_country: 'Angola',
           counterpart_hub: 'Cabinda',
           counterpart_hub_name: 'Cabinda Port',
           country: nil,
           effective_date: Date.parse('Thu, 01 Nov 2018'),
           expiration_date: Date.parse('Fri, 30 Nov 2018'),
           fees: { 'ISPS' => { currency: 'EUR',
                               key: 'ISPS',
                               max: nil,
                               min: 27,
                               name: 'Isps',
                               rate_basis: 'PER_CONTAINER',
                               value: 27 } },
           hub: 'Hamburg',
           hub_name: 'Hamburg Port',
           load_type: 'fcl_20',
           mot: 'ocean',
           row_nr: '3',
           service_level: 'standard' },
         { carrier: 'CMA CGM',
           counterpart_country: 'Angola',
           counterpart_hub: 'Cabinda',
           counterpart_hub_name: 'Cabinda Port',
           country: nil,
           effective_date: Date.parse('Thu, 01 Nov 2018'),
           expiration_date: Date.parse('Fri, 30 Nov 2018'),
           fees: { 'ISPS' => { currency: 'EUR',
                               key: 'ISPS',
                               max: nil,
                               min: 27,
                               name: 'Isps',
                               rate_basis: 'PER_CONTAINER',
                               value: 27 } },
           hub: 'Hamburg',
           hub_name: 'Hamburg Port',
           load_type: 'fcl_40',
           mot: 'ocean',
           row_nr: '3',
           service_level: 'standard' },
         { carrier: 'CMA CGM',
           counterpart_country: 'Angola',
           counterpart_hub: 'Cabinda',
           counterpart_hub_name: 'Cabinda Port',
           country: nil,
           effective_date: Date.parse('Thu, 01 Nov 2018'),
           expiration_date: Date.parse('Fri, 30 Nov 2018'),
           fees: { 'ISPS' => { currency: 'EUR',
                               key: 'ISPS',
                               max: nil,
                               min: 27,
                               name: 'Isps',
                               rate_basis: 'PER_CONTAINER',
                               value: 27 } },
           hub: 'Hamburg',
           hub_name: 'Hamburg Port',
           load_type: 'fcl_40_hq',
           mot: 'ocean',
           row_nr: '3',
           service_level: 'standard' },
         { carrier: 'CMA CGM',
           counterpart_country: 'Angola',
           counterpart_hub: 'Cabinda',
           counterpart_hub_name: 'Cabinda Port',
           country: nil,
           effective_date: Date.parse('Sat, 01 Dec 2018'),
           expiration_date: Date.parse('Mon, 31 Dec 2018'),
           fees: { 'ISPS' => { currency: 'EUR',
                               key: 'ISPS',
                               max: nil,
                               min: 27,
                               name: 'Isps',
                               rate_basis: 'PER_CONTAINER',
                               value: 27 } },
           hub: 'Hamburg',
           hub_name: 'Hamburg Port',
           load_type: 'fcl_20',
           mot: 'ocean',
           row_nr: '3',
           service_level: 'standard' },
         { carrier: 'CMA CGM',
           counterpart_country: 'Angola',
           counterpart_hub: 'Cabinda',
           counterpart_hub_name: 'Cabinda Port',
           country: nil,
           effective_date: Date.parse('Sat, 01 Dec 2018'),
           expiration_date: Date.parse('Mon, 31 Dec 2018'),
           fees: { 'ISPS' => { currency: 'EUR',
                               key: 'ISPS',
                               max: nil,
                               min: 27,
                               name: 'Isps',
                               rate_basis: 'PER_CONTAINER',
                               value: 27 } },
           hub: 'Hamburg',
           hub_name: 'Hamburg Port',
           load_type: 'fcl_40',
           mot: 'ocean',
           row_nr: '3',
           service_level: 'standard' },
         { carrier: 'CMA CGM',
           counterpart_country: 'Angola',
           counterpart_hub: 'Cabinda',
           counterpart_hub_name: 'Cabinda Port',
           country: nil,
           effective_date: Date.parse('Sat, 01 Dec 2018'),
           expiration_date: Date.parse('Mon, 31 Dec 2018'),
           fees: { 'ISPS' => { currency: 'EUR',
                               key: 'ISPS',
                               max: nil,
                               min: 27,
                               name: 'Isps',
                               rate_basis: 'PER_CONTAINER',
                               value: 27 } },
           hub: 'Hamburg',
           hub_name: 'Hamburg Port',
           load_type: 'fcl_40_hq',
           mot: 'ocean',
           row_nr: '3',
           service_level: 'standard' }]
      end
    end

    factory :excel_data_restructured_correct_pricings_one_fee_col_and_ranges, traits: %i(correct_pricings_one_fee_col_and_ranges)
    factory :excel_data_restructured_faulty_pricings_one_fee_col_and_ranges, traits: %i(faulty_pricings_one_fee_col_and_ranges)
    factory :excel_data_restructured_correct_pricings_dynamic_fee_cols_no_rangs, traits: %i(correct_pricings_dynamic_fee_cols_no_rangs)
    factory :excel_data_restructured_correct_local_charges, traits: %i(correct_local_charges)
    factory :excel_data_restructured_faulty_local_charges, traits: %i(faulty_local_charges)
    factory :excel_data_restructured_correct_saco_shipping_pricings, traits: %i(correct_saco_shipping_pricings)
    factory :excel_data_restructured_correct_saco_shipping_local_charges, traits: %i(correct_saco_shipping_local_charges)
  end
end
