# frozen_string_literal: true

source 'https://rubygems.org'

# Declare your gem's dependencies in admiralty_auth.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Allow access to other engines
Gem::Specification.load(Dir[File.join(__dir__, '*.gemspec')].first).dependencies.each do |dep|
  next unless File.directory?(File.expand_path("../#{dep.name}", __dir__))

  gem dep.name, path: '..'
end

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use a debugger
# gem 'byebug', group: [:development, :test]
