# frozen_string_literal: true
class BackfillWrongLocodesAndHubCodesWorker
  include Sidekiq::Worker
  include Sidekiq::Status::Worker

  def perform(*args)
    ActiveRecord::Base.transaction do

      ActiveRecord::Base.connection.execute("
        CREATE TEMP TABLE temp_table AS
        WITH t (incorrect, correct) AS (
        VALUES
          ('ANKRA', 'BQKRA'),
          ('ANPHI', 'SXPHI'),
          ('BBBGT', 'BBBGI'),
          ('BDCGM', 'BDCGP'),
          ('BHBHH', 'BHKBS'),
          ('BLGUS', 'BLSBH'),
          ('BMHLT', 'BMBDA'),
          ('BOLPA', 'BOLPB'),
          ('BRQHV', 'BRNHO'),
          ('BRSAN', 'BRSTN'),
          ('BRSEP', 'BRSPB'),
          ('BRVIC', 'BRVDC'),
          ('BRVLC', 'BRVDC'),
          ('BSFPT', 'BSFPO'),
          ('CGBOA', 'CDBOA'),
          ('CGMAT', 'CDMAT'),
          ('CGPNO', 'CGPNR'),
          ('CISNP', 'CISPY'),
          ('CLSAN', 'CLSAI'),
          ('CLSGO', 'CLSCL'),
          ('CLVPO', 'CLVAP'),
          ('CNAQP', 'CNANJ'),
          ('CNBAY', 'CNBYQ'),
          ('CNBFU', 'CNBBU'),
          ('CNBHI', 'CNBIH'),
          ('CNCGU', 'CNCGS'),
          ('CNFUG', 'CNFQG'),
          ('CNGGY', 'CNTSG'),
          ('CNGVA', 'CHGVA'),
          ('CNHAI', 'CNXWH'),
          ('CNHKG', 'HKHKG'),
          ('CNHOP', 'CNHUA'),
          ('CNJJX', 'CNJUJ'),
          ('CNLAN', 'CNLNS'),
          ('CNLIS', 'CNLSS'),
          ('CNLZU', 'CNLUZ'),
          ('CNNGH', 'CNNIN'),
          ('CNNNP', 'CNNSA'),
          ('CNQUZ', 'CNQZS'),
          ('CNQYN', 'CNQGY'),
          ('CNSBW', 'CNSZX'),
          ('CNSGX', 'CNSGI'),
          ('CNSIN', 'CNSTI'),
          ('CNTAG', 'CNTGS'),
          ('CNTAS', 'CNTGS'),
          ('CNTKG', 'CNTAC'),
          ('CNTSH', 'CNTSA'),
          ('CNULN', 'MNULN'),
          ('CNWTU', 'CNQZL'),
          ('CNWWW', 'CNZUH'),
          ('CNXGG', 'CNXXI'),
          ('CNXHI', 'CNCHI'),
          ('CNXIL', 'CNXAO'),
          ('CNXXX', 'CNWAZ'),
          ('CNYBN', 'CNYIB'),
          ('CNYIW', 'CNYIU'),
          ('CNYNF', 'CNYUF'),
          ('CNYQS', 'CNBJO'),
          ('CNYTP', 'CNYAT'),
          ('CNYUY', 'CNYYA'),
          ('CNYYY', 'CNNAH'),
          ('CNZAP', 'CNZPU'),
          ('CNZGN', 'CNZSN'),
          ('CNZGQ', 'CNZQG'),
          ('COCGN', 'COCTG'),
          ('CRPNM', 'CRLIO'),
          ('CVFOG', 'PTSJO'),
          ('CVSJO', 'PTSJO'),
          ('CVSVT', 'PTSVC'),
          ('DOSDO', 'DOSDQ'),
          ('DXALG', 'DZALG'),
          ('DZORA', 'DZORN'),
          ('DZUAY', 'DZALG'),
          ('ECPOA', 'ECPSJ'),
          ('EG9CO', 'EGCAI'),
          ('EGALX', 'EGALY'),
          ('EGDMT', 'EGDAM'),
          ('ESLPS', 'ESLPG'),
          ('FRIRK', 'FRDKK'),
          ('FRSTB', 'BLSBH'),
          ('GBTIY', 'GBTIL'),
          ('GMKBI', 'CMKBI'),
          ('GPGUS', 'BLGUS'),
          ('GPSBH', 'CASBM'),
          ('GPSFG', 'GBSMN'),
          ('GQBBA', 'GQBSG'),
          ('GYGTT', 'GYGEO'),
          ('HKHKK', 'HKHKG'),
          ('HNSTC', 'HNPCA'),
          ('IDPLS', 'IDPLM'),
          ('INJNR', 'INISK'),
          ('INVIZ', 'INVIG'),
          ('INWFD', 'INBLR'),
          ('ITAPF', 'ITNAP'),
          ('ITGJ4', 'ITGOA'),
          ('JMKGN', 'JMKIN'),
          ('KHKAM', 'KHKOS'),
          ('KHSHV', 'KHKOS'),
          ('KHSIH', 'KHKOS'),
          ('KMMCC', 'KMMUT'),
          ('KNCHF', 'KNCHA'),
          ('KNPNH', 'KHPNH'),
          ('KRBUS', 'KRPUS'),
          ('LCCSJ', 'LCCAS'),
          ('LKCOL', 'LKCMB'),
          ('LYKYE', 'LBKYE'),
          ('MVMXQ', 'SEMMA'),
          ('MWBYR', 'MWBLZ'),
          ('MXEEA', 'MXESE'),
          ('MXLWO', 'MXLEN'),
          ('MXMOY', 'MXMTY'),
          ('MXMZO', 'MXZLO'),
          ('MXVCZ', 'MXVER'),
          ('MYLAA', 'MYLBU'),
          ('NGZGM', 'NGLAG'),
          ('NICRT', 'NICIO'),
          ('NIMGD', 'NIMGA'),
          ('NOSTM', 'NOSRU'),
          ('NOVBN', 'NOBGO'),
          ('NZBLI', 'NZBHE'),
          ('NZCCH', 'NZCHC'),
          ('NZNLS', 'NZNSN'),
          ('NZQEL', 'NZWLG'),
          ('PABAL', 'PABLB'),
          ('PACFD', 'PAONX'),
          ('PAPTD', 'PAPTY'),
          ('PGCON', 'GNCKY'),
          ('PHCYG', 'PHCGY'),
          ('PKPKZ', 'PKKHI'),
          ('PLARW', 'PLWAW'),
          ('PLQLC', 'PLGWC'),
          ('PNMZO', 'PAMIT'),
          ('PRASU', 'PYASU'),
          ('PRUAQ', 'PRSJU'),
          ('REPDG', 'REPD2'),
          ('REREU', 'RELPT'),
          ('RU9MW', 'RUMOW'),
          ('SACAP', 'ZACPT'),
          ('SADMN', 'SADMM'),
          ('SADUR', 'ZADUR'),
          ('SARYD', 'SARYP'),
          ('SCMAH', 'SCMAW'),
          ('SEGHG', 'SEGOT'),
          ('SESMP', 'SESTO'),
          ('SLFTW', 'SLFNA'),
          ('SNSTG', 'CNSTG'),
          ('STSOM', 'STTMS'),
          ('SVSAD', 'SVSAL'),
          ('SVSSA', 'SVSAL'),
          ('SXPHL', 'SXPHI'),
          ('THSGZ', 'THSGK'),
          ('TKBKK', 'THBKK'),
          ('TLDIC', 'TLDIL'),
          ('TRADM', 'TRIZM'),
          ('TRHYA', 'TRIST'),
          ('TRIZR', 'TRIZM'),
          ('TRLIA', 'TRALI'),
          ('UAODE', 'UAODS'),
          ('UYMVE', 'UYMVD'),
          ('VCKSU', 'VCKTN'),
          ('VGANO', 'VGRAD'),
          ('VNHAP', 'VNHPH'),
          ('VUSTO', 'VUSAN'),
          ('WSAPI', 'WSAPW'),
          ('YTLOG', 'YTLON'),
          ('ZAPEB', 'ZAPLZ')
        )
        SELECT * FROM t;
      ")

      ActiveRecord::Base.connection.execute("
        UPDATE hubs SET hub_code = correct
        FROM temp_table
        WHERE hub_code = incorrect;
      ")

      ActiveRecord::Base.connection.execute("
        UPDATE nexuses SET locode = correct
        FROM temp_table
        WHERE locode = incorrect;
      ")
    end
  end
end
