# Disable annoying signature complain when this file changes
verify_signatures: false

PostCheckout:
  EnsureBranchName:
    enabled: true

CommitMsg:
  MessageFormat:
    enabled: true
    pattern: '\A(?:([A-Z]+-[0-9]+)|(?i:(wip|chore|fix|hotfix|fixup))|Merge branch)(.*)'
    expected_pattern_message: '<JIRA_KEY|wip|fix|chore|hotfix> <Commit Message Description>'
    sample_message: 'IMC-1234 - Refactored Pricing'
