gitlab:
  api_endpoint: https://gitlab.com/api/v4
  format: '**%{runner}**: %{msg}'
text:
  format: '%{color_location}: %{color_level}: %{runner}: %{msg}'
rails_best_practices:
  exclude:
    - '**/*'
