detectors:
  # You can disable smells completely
  IrresponsibleModule:
    enabled: false
  UncommunicativeModuleName:
    enabled: false
  
directories:
  "**/db/migrate":
    FeatureEnvy:
      enabled: false
    "TooManyStatements":
      enabled: false
    "UncommunicativeVariableName":
      enabled: false