---
inherit_from: .rubocop_strict.yml

inherit_gem:
  rubocop-itsmycargo:
    - config/base.yml
    - config/rails.yml
    - config/rspec.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - '**/bin/*'
    - 'db/schema.rb'

Layout/LineLength:
  Max: 120
  IgnoreCopDirectives: true
  Exclude:
    - '**/*_spec.rb'
    - '.lefthook/**/*'
    - 'config/routes.rb'
  IgnoredPatterns: ['\A#']

Metrics/AbcSize:
  Max: 25
  Exclude:
    - '**/migrate/*.rb'

Metrics/BlockLength:
  Max: 25
  Exclude:
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/*/factories/**/*.rb'
    - '**/*_spec.rb'
    - '**/migrate/*.rb'
    - config/**/*.rb

Metrics/MethodLength:
  Max: 25
  Exclude:
    - '**/*_spec.rb'
    - '**/migrate/*.rb'

Metrics/ModuleLength:
  Max: 100
  Exclude:
    - '**/*_spec.rb'

Metrics/ParameterLists:
  Max: 5
  Exclude:
    - qa/features/**/*_steps.rb

Naming/VariableName:
  Exclude:
    - 'engines/*/spec/api/*_spec.rb'

RSpec/EmptyExampleGroup:
  Exclude:
    - '**/spec/api/*_spec.rb'
