Lint/NonLocalExitFromIterator:
  Exclude:
    - 'app/models/itinerary.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/classes/document_service/gdpr_writer.rb'
    - 'app/classes/excel_tools.rb'
    - 'app/classes/google_directions.rb'
    - 'app/classes/shipping_tools.rb'
    - 'app/classes/trucking_price_rules_machine.rb'
    - 'app/controllers/admin/companies_controller.rb'
    - 'app/controllers/admin/groups_controller.rb'
    - 'app/controllers/admin/hubs_controller.rb'
    - 'app/controllers/admin/itineraries_controller.rb'
    - 'app/controllers/admin/local_charges_controller.rb'
    - 'app/controllers/admin/maps_controller.rb'
    - 'app/controllers/admin/margins_controller.rb'
    - 'app/controllers/admin/memberships_controller.rb'
    - 'app/controllers/admin/shipments_controller.rb'
    - 'app/controllers/admin/trucking_controller.rb'
    - 'app/controllers/contacts_controller.rb'
    - 'app/controllers/saml_controller.rb'
    - 'app/controllers/shipments_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'app/mailers/account_mailer.rb'
    - 'app/mailers/new_user_mailer.rb'
    - 'app/mailers/shipment_mailer.rb'
    - 'app/mailers/welcome_mailer.rb'
    - 'app/models/addon.rb'
    - 'app/models/itinerary.rb'
    - 'app/models/shipment.rb'
    - 'engines/excel_data_services/app/services/excel_data_services/file_writers/local_charges.rb'
    - 'engines/excel_data_services/app/services/excel_data_services/file_writers/pricings_row_data_builder.rb'
    - 'engines/excel_data_services/app/services/excel_data_services/inserters/pricing.rb'
    - 'engines/excel_data_services/app/services/excel_data_services/loaders/uploader.rb'
    - 'engines/excel_data_services/app/services/excel_data_services/restructurers/local_charges.rb'
    - 'engines/excel_data_services/app/services/excel_data_services/restructurers/pricing_dynamic_fee_cols_no_ranges.rb'
    - 'engines/excel_data_services/app/services/excel_data_services/restructurers/pricing_one_fee_col_and_ranges.rb'
    - 'engines/excel_data_services/app/services/excel_data_services/restructurers/saco_shipping.rb'
    - 'engines/helmsman/app/services/helmsman/validator.rb'
    - 'engines/legacy/app/models/legacy/charge.rb'
    - 'engines/legacy/app/models/legacy/itinerary.rb'
    - 'engines/legacy/app/models/legacy/schedule.rb'
    - 'engines/legacy/app/validators/legacy/max_aggregate_dimensions_validator.rb'
    - 'engines/migrator/lib/migrator/dependency.rb'
    - 'engines/offer_calculator/app/services/offer_calculator/pricing_tools.rb'
    - 'engines/offer_calculator/app/services/offer_calculator/schedule.rb'
    - 'engines/pricings/app/models/pricings/margin.rb'
    - 'engines/pricings/app/services/pricings/manipulator.rb'
    - 'engines/pricings/app/services/pricings/margin_creator.rb'
    - 'engines/pricings/app/services/pricings/preview.rb'
    - 'engines/result_formatter/app/services/result_formatter/fee_table_service.rb'
    - 'engines/shipments/app/services/shipments/shipment_request_creator.rb'
    - 'engines/trucking/app/services/trucking/queries/base.rb'
    - 'engines/trucking/app/services/trucking/queries/find_by_hub_ids.rb'
    - 'lib/cobra_helper.rb'
    - 'lib/generators/engine/engine_generator.rb'


Metrics/BlockLength:
  Exclude:
    - 'app/classes/document_service/gdpr_writer.rb'
    - 'app/controllers/admin/shipments_controller.rb'
    - 'app/controllers/shipments_controller.rb'
    - 'engines/api/config/routes.rb'
    - 'engines/excel_data_services/app/services/excel_data_services/inserters/pricing.rb'
    - 'engines/pricings/app/services/pricings/margin_creator.rb'
    - 'engines/pricings/app/services/pricings/preview.rb'
    - 'engines/validator/app/services/validator/itinerary.rb'
    - 'gems/money_cache/spec/money_cache/converter_spec.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/classes/document_service/gdpr_writer.rb'
    - 'app/classes/excel_tools.rb'
    - 'app/classes/google_directions.rb'
    - 'app/classes/shipping_tools.rb'
    - 'app/controllers/admin/maps_controller.rb'
    - 'app/controllers/admin/margins_controller.rb'
    - 'app/controllers/admin/shipments_controller.rb'
    - 'app/controllers/admin/trucking_controller.rb'
    - 'app/controllers/contacts_controller.rb'
    - 'app/controllers/shipments_controller.rb'
    - 'app/jobs/trucking_migration_job.rb'
    - 'app/mailers/shipment_mailer.rb'
    - 'app/models/addon.rb'
    - 'app/models/itinerary.rb'
    - 'engines/excel_data_services/app/services/excel_data_services/file_writers/local_charges.rb'
    - 'engines/excel_data_services/app/services/excel_data_services/file_writers/pricings_row_data_builder.rb'
    - 'engines/excel_data_services/app/services/excel_data_services/inserters/pricing.rb'
    - 'engines/excel_data_services/app/services/excel_data_services/loaders/uploader.rb'
    - 'engines/excel_data_services/app/services/excel_data_services/restructurers/pricing_dynamic_fee_cols_no_ranges.rb'
    - 'engines/excel_data_services/app/services/excel_data_services/restructurers/pricing_one_fee_col_and_ranges.rb'
    - 'engines/excel_data_services/app/services/excel_data_services/restructurers/saco_shipping.rb'
    - 'engines/excel_data_services/app/services/excel_data_services/validators/insertable_checks/hubs.rb'
    - 'engines/excel_data_services/app/services/excel_data_services/validators/insertable_checks/pricing.rb'
    - 'engines/legacy/app/models/legacy/itinerary.rb'
    - 'engines/legacy/app/validators/legacy/max_aggregate_dimensions_validator.rb'
    - 'engines/offer_calculator/app/services/offer_calculator/pricing_tools.rb'
    - 'engines/offer_calculator/app/services/offer_calculator/schedule.rb'
    - 'engines/offer_calculator/app/services/offer_calculator/service/rate_builders/truckings.rb'
    - 'engines/pricings/app/services/pricings/margin_creator.rb'
    - 'engines/pricings/app/services/pricings/preview.rb'
    - 'engines/validator/app/services/validator/itinerary.rb'
    - 'lib/core_ext/active_record/migration.rb'
    - 'lib/generators/engine/engine_generator.rb'

Metrics/ModuleLength:
  Exclude:
    - 'app/classes/excel_tools.rb'
    - 'engines/excel_data_services/app/services/excel_data_services/validators/header_checker.rb'

RSpec/Pending:
  Exclude:
    - 'spec/mailers/account_mailer_spec.rb'
    - 'spec/requests/password_resets_request_spec.rb'
    - 'spec/sequential/models/sequential/sequence_spec.rb'

Rails/CreateTableWithTimestamps:
  Exclude:
    - 'db/migrate/20181107143133_create_new_locations.rb'

Rails/DynamicFindBy:
  AllowedMethods: find_by_hub_id

Rails/Exit:
  Exclude:
    - 'lib/**/*.rake'
    - 'lib/database_util/downloader.rb'
    - 'lib/database_util/restorer.rb'

Rails/InverseOf:
  Exclude:
    - 'app/models/address.rb'

Rails/Output:
  Exclude:
    - 'lib/cobra_helper.rb'
    - 'lib/database_util/downloader.rb'
    - 'lib/database_util/restorer.rb'

Security/Open:
  Exclude:
    - 'app/classes/google_directions.rb'
