---
inherit_gem:
  rubocop-github:
    - config/default_edge.yml
    - config/rails_edge.yml

inherit_mode:
  merge:
    - Include

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  DisabledByDefault: true
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  CacheRootDirectory: ./tmp
  Exclude:
    - '**/bin/**/*'
    - 'tmp/**/*'

Naming/FileName:
  Exclude:
    - 'config/initializers/*'
