inherit_gem:
  rubocop-itsmycargo: config/default.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - '**/bin/*'
    - 'client/**/*'
    - 'db/schema.rb'
    - '**/Rakefile'

Layout/LineLength:
  Max: 120
  IgnoreCopDirectives: true
  Exclude:
    - '**/*_spec.rb'
    - '**/*/factories/**/*.rb'
    - db/custom_seeds/*.rb
    - qa/features/**/*_steps.rb
    - qa/features/**/*.feature
    - engines/legacy/config/devise.rb

Metrics/AbcSize:
  Max: 25
  Exclude:
    - db/migrate/*.rb
    - engines/*/db/migrate/*.rb

Metrics/BlockLength:
  Max: 25
  Exclude:
    - '**/*_spec.rb'
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/*/factories/**/*.rb'
    - config/**/*.rb
    - db/migrate/*.rb
    - engines/*/db/migrate/*.rb
    - Gemfile

Metrics/MethodLength:
  Max: 25
  Exclude:
    - '**/*_spec.rb'
    - db/migrate/*.rb
    - engines/*/db/migrate/*.rb

Metrics/ParameterLists:
  Max: 5
  Exclude:
    - qa/features/**/*_steps.rb

# Disable Time over DateTime for legacy specs
Style/DateTime:
  Exclude:
    - spec/*
