AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/**/*'
    - 'client/**/*'
    - Rakefile

Metrics/AbcSize:
  Max: 25
  Exclude:
    - db/migrate/*.rb

Metrics/BlockLength:
  Max: 25
  Exclude:
    - config/routes.rb
    - db/migrate/*.rb
    - spec/**/*_spec.rb

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25
  Exclude:
    - db/migrate/*.rb
    - spec/**/*_spec.rb

Style/Documentation:
  Enabled: false

# do / end blocks should be used for side effects,
# methods that run a block for side effects and have
# a useful return value are rare, assign the return
# value to a local variable for those cases.
Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '()'
    '%i': '()'
    '%r': '{}'
    '%w': '()'
    '%x': '{}'

# has_key? and has_value? are far more readable than key? and value?
Style/PreferredHashMethods:
  EnforcedStyle: verbose

Style/SingleLineMethods:
  AllowIfMethodIsEmpty: false

Style/EmptyMethod:
  EnforcedStyle: expanded
