---
inherit_mode:
  merge:
    - Exclude

inherit_gem:
  rubocop-itsmycargo:
    - config/base.yml
    - config/rails.yml
    - config/rspec.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - '**/bin/*'

Layout/LineLength:
  Exclude:
    - 'engines/locations/factories/locations_locations.rb'
    - 'engines/trucking/factories/trucking/coverages.rb'
    - 'engines/trucking/factories/trucking/google_directions_response.rb'
    - 'spec/trucking/services/trucking/google_directions_spec.rb'
    - 'spec/wheelhouse/services/wheelhouse/quotation_service_spec.rb'
  IgnoredPatterns: ['\A\s*#']

Metrics/AbcSize:
  Max: 25
  Exclude:
    - '**/migrate/*.rb'

Metrics/BlockLength:
  Max: 25
  Exclude:
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/*/factories/**/*.rb'
    - '**/migrate/*.rb'
    - 'spec/**/*.rb'
    - config/**/*.rb

Metrics/MethodLength:
  Max: 25
  Exclude:
    - '**/*_spec.rb'
    - '**/migrate/*.rb'

Metrics/ModuleLength:
  Max: 100
  Exclude:
    - '**/*_spec.rb'

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/**/api/*_spec.rb'
