---
steps:
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - --build-arg=RELEASE=$COMMIT_SHA
  - --tag=eu.gcr.io/itsmycargo-main/apps/api:$BRANCH_NAME
  - --tag=eu.gcr.io/itsmycargo-main/apps/api:$COMMIT_SHA
  - /workspace/
  waitFor:
  - '-'
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - --build-arg=RELEASE=$COMMIT_SHA
  - --build-arg=SENTRY_AUTH_TOKEN=$_SENTRY_AUTH_TOKEN
  - --tag=eu.gcr.io/itsmycargo-main/apps/client:$BRANCH_NAME
  - --tag=eu.gcr.io/itsmycargo-main/apps/client:$COMMIT_SHA
  - /workspace/client/
  waitFor:
  - '-'
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - --tag=eu.gcr.io/itsmycargo-main/qa/api:$BRANCH_NAME
  - --tag=eu.gcr.io/itsmycargo-main/qa/api:$COMMIT_SHA
  - /workspace/qa/
  waitFor:
  - '-'
timeout: 1800s
images:
- eu.gcr.io/itsmycargo-main/apps/api:$BRANCH_NAME
- eu.gcr.io/itsmycargo-main/apps/api:$COMMIT_SHA
- eu.gcr.io/itsmycargo-main/apps/client:$BRANCH_NAME
- eu.gcr.io/itsmycargo-main/apps/client:$COMMIT_SHA
- eu.gcr.io/itsmycargo-main/qa/api:$BRANCH_NAME
- eu.gcr.io/itsmycargo-main/qa/api:$COMMIT_SHA
