---
steps:
  - id: backend
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg=RELEASE=$COMMIT_SHA
      - --tag=eu.gcr.io/itsmycargo-main/$_REPOSITORY/backend:$COMMIT_SHA
      - /workspace/
    waitFor:
      - "-"

  - id: frontend
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg=RELEASE=$COMMIT_SHA
      - --build-arg=SENTRY_AUTH_TOKEN=$_SENTRY_AUTH_TOKEN
      - --tag=eu.gcr.io/itsmycargo-main/$_REPOSITORY/frontend:$COMMIT_SHA
      - /workspace/client/
    waitFor:
    - "-"

  - id: qa
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=eu.gcr.io/itsmycargo-main/$_REPOSITORY/qa:$COMMIT_SHA
      - /workspace/qa/
    waitFor:
    - "-"

timeout: 1800s
images:
  - eu.gcr.io/itsmycargo-main/$_REPOSITORY/backend:$COMMIT_SHA
  - eu.gcr.io/itsmycargo-main/$_REPOSITORY/frontend:$COMMIT_SHA
  - eu.gcr.io/itsmycargo-main/$_REPOSITORY/qa:$COMMIT_SHA
