---
steps:
  - id: api
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg=RELEASE=$COMMIT_SHA
      - --tag=eu.gcr.io/itsmycargo-main/apps/api:$COMMIT_SHA
      - /workspace/
    waitFor:
      - "-"

  - id: client
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg=RELEASE=$COMMIT_SHA
      - --build-arg=SENTRY_AUTH_TOKEN=$_SENTRY_AUTH_TOKEN
      - --tag=eu.gcr.io/itsmycargo-main/apps/client:$COMMIT_SHA
      - /workspace/client/
    waitFor:
    - "-"

  - id: qa
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=eu.gcr.io/itsmycargo-main/qa/api:$COMMIT_SHA
      - /workspace/qa/
    waitFor:
    - "-"

timeout: 1800s
images:
  - eu.gcr.io/itsmycargo-main/apps/api:$COMMIT_SHA
  - eu.gcr.io/itsmycargo-main/apps/client:$COMMIT_SHA
  - eu.gcr.io/itsmycargo-main/qa/api:$COMMIT_SHA
