version: "2.4"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.test
    init: true
    entrypoint: scripts/ci-build.sh
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: "postgis://postgres:cargotime@postgresql/imcr_test"
      MALLOC_ARENA_MAX: 2
      NODE_ENV: test
      RAILS_ENV: test
      REDIS_URL: "redis://redis:6379"
    stdin_open: true
    tty: true
    mem_limit: 2g
    depends_on:
      - postgresql
      - redis

  postgresql:
    image: mdillon/postgis:9.6
    expose:
      - 5432
    environment:
      POSTGRES_DB: imcr_test
      POSTGRES_PASSWORD: cargotime
    restart: always
    mem_limit: 512m

  redis:
    image: redis
    expose:
      - 6379
    restart: always
