apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}
  labels:
{{ include "app.labels" . | indent 4 }}
data:
  vault-agent-config.hcl: |
    exit_after_auth = true
    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
          config = {
            role = "review-{{ .Values.vault.roleName }}"
          }
      }

      sink "file" {
        config = {
          path = "/var/run/secrets/vault/token"
        }
      }
    }
  consul-template-config.hcl: |
    upcase   = true
    sanitize = true

    secret {
      path      = "secret/review/{{ .Values.vault.roleName }}"
      no_prefix = true
    }

    secret {
      path      = "database/creds/review-{{ .Values.vault.roleName }}"
      no_prefix = true
      format    = "database_{{`{{ key }}`}}"
    }
