{{- if .Values.ingress.enabled -}}
{{- $fullName := include "app.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-frontend
  labels:
    app.kubernetes.io/component: frontend
{{ include "app.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: "{{ include "app.host" . }}"
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}-frontend
              servicePort: http
{{- end }}
