{{- if .Values.ingress.enabled -}}
{{- $fullName := include "app.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-backend
  labels:
    app.kubernetes.io/component: backend
{{ include "app.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: "api-{{ include "app.host" . }}"
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}-backend
              servicePort: http
{{- end }}
