{{- if .Values.backend.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app.fullname" . }}-migrate-{{ .Release.Revision }}
  labels:
    app.kubernetes.io/component: migrate
{{ include "app.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: migrate
      annotations:
        vault.security.banzaicloud.io/vault-role: review-{{ .Chart.Name }}
    spec:
      restartPolicy: OnFailure
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Chart.Name }}
      {{- end }}
      automountServiceAccountToken: true
{{- if .Values.backend.usePodSecurityContext }}
      securityContext:
        runAsUser: {{ default 0 .Values.backend.runAsUser }}
{{- if and (.Values.backend.runAsUser) (.Values.backend.fsGroup) }}
{{- if not (eq .Values.backend.runAsUser 0.0) }}
        fsGroup: {{ .Values.backend.fsGroup }}
{{- end }}
{{- end }}
{{- end }}
      {{- include "app.imagePullSecrets" . | nindent 6 }}
      initContainers:
        - name: deps
          image: jwilder/dockerize
          args:
            - dockerize
            - -wait
            - tcp://{{ template "app.fullname" . }}-postgresql:5432
            - -wait
            - tcp://{{ template "app.fullname" . }}-redis-master:6379
            - -timeout
            - '300s'
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}/backend:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - bin/rails
            - db:migrate
          env:
            - name: DATABASE_URL
              value: {{ template "app.db_url" . }}
            - name: REDIS_URL
              value: redis://:{{ .Values.redis.password }}@{{ template "app.fullname" . }}-redis-master:6379
            - name: REVIEW_URL
              value: {{ include "app.app_url" . | quote }}
            - name: GOOGLE_CREDENTIALS
              value: "vault:secret/data/review/{{ .Chart.Name }}#google-service-account.json"
            - name: RAILS_MASTER_KEY
              value: "vault:secret/data/review/{{ .Chart.Name }}#rails_master_key"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
