apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ include "polaris.fullname" . }}
  labels:
    {{- include "polaris.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: /products/polaris/{{ .Values.stage }}/config
        objectType: ssmparameter
        objectAlias: env
      - objectName: /products/polaris/{{ .Values.stage }}/master_key
        objectType: ssmparameter
        objectAlias: master.key
