{{- if .Values.ingress.auth.username -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    app: {{ include "app.name" . }}
    chart: {{ include "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  auth: {{ printf "%s:%s" .Values.ingress.auth.username .Values.ingress.auth.password | b64enc | quote }}
{{- end }}
