{{- if .Values.credentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  credentials.json: {{ .Values.credentials | b64enc | quote }}
  master.key: {{ .Values.masterKey | b64enc | quote }}
{{- end }}
