{{- if and (.Values.serviceAccount.enabled) (not .Values.serviceAccount.name) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{ include "app.labels" . | nindent 2 }}
  name: {{ .Chart.Name }}
{{- end }}
