#!/usr/bin/env ruby

COMMIT_PATTERN = %r{\A(((IMC-[[:digit:]]+)|((docs|fix|feat|chore|style|refactor|perf|test|wip)(\(.*\))?))(: | - )(.*))|(Merge .*)}

input_file, * = ARGV
commit_message = File.read(input_file)

if %r{(imc)-[[:digit]]}.match?(commit_message)
  warn "• Use only upper case ticket numbers in commit messages."
  warn "  IMC-1234: summary"
  warn ""

  exit 1
end

unless COMMIT_PATTERN.match?(commit_message)
  warn "• Invalid commit message, see examples:"
  warn "    * Ticket Tracking"
  warn "        IMC-1234: short summary"
  warn "    * Conventional Commits (https://www.conventionalcommits.org/en/v1.0.0/#summary)"
  warn "        chore(deps): some text"
  warn "    * Work in Progress Commits"
  warn "        wip: some text"
  warn ""

  exit 1
end
exit 0
