# frozen_string_literal: true

require "rails_helper"

RSpec.describe ExcelDataServices::V4::Files::SpreadsheetData do
  include_context "V4 setup"

  let(:service) { described_class.new(state: state_arguments, section_parser: section_parser) }
  let(:section_parser) { ExcelDataServices::V4::Files::SectionParser.new(section: section_string, state: state_arguments) }
  let(:xlsx) { File.open(file_fixture("excel/example_pricings_slim.xlsx")) }

  describe "#frame" do
    let(:section_string) { "Pricings" }
    let(:expected_results) do
      [{ "value" => "standard",
         "header" => "service",
         "row" => 2,
         "column" => "N",
         "sheet_name" => "Sheet1" },
        { "value" => "1b536235-4bd4-49a7-874e-489ce9e2d251",
          "header" => "group_id",
          "row" => 2,
          "column" => "A",
          "sheet_name" => "Sheet1" },
        { "value" => "TEST_GROUP",
          "header" => "group_name",
          "row" => 2,
          "column" => "B",
          "sheet_name" => "Sheet1" },
        { "value" => Date.parse("Wed, 30 Jun 2021"),
          "header" => "effective_date",
          "row" => 2,
          "column" => "C",
          "sheet_name" => "Sheet1" },
        { "value" => Date.parse("Thu, 30 Dec 2021"),
          "header" => "expiration_date",
          "row" => 2,
          "column" => "D",
          "sheet_name" => "Sheet1" },
        { "value" => "SEGOT",
          "header" => "origin_locode",
          "row" => 2,
          "column" => "G",
          "sheet_name" => "Sheet1" },
        { "value" => "Gothenburg",
          "header" => "origin_hub",
          "row" => 2,
          "column" => "F",
          "sheet_name" => "Sheet1" },
        { "value" => "Sweden",
          "header" => "origin_country",
          "row" => 2,
          "column" => "E",
          "sheet_name" => "Sheet1" },
        { "value" => "CNSHA",
          "header" => "destination_locode",
          "row" => 2,
          "column" => "J",
          "sheet_name" => "Sheet1" },
        { "value" => "Shanghai",
          "header" => "destination_hub",
          "row" => 2,
          "column" => "I",
          "sheet_name" => "Sheet1" },
        { "value" => "China",
          "header" => "destination_country",
          "row" => 2,
          "column" => "H",
          "sheet_name" => "Sheet1" },
        { "value" => "ocean",
          "header" => "mode_of_transport",
          "row" => 2,
          "column" => "L",
          "sheet_name" => "Sheet1" },
        { "value" => organization.slug,
          "header" => "carrier",
          "row" => 2,
          "column" => "M",
          "sheet_name" => "Sheet1" },
        { "value" => organization.slug.downcase,
          "header" => "carrier_code",
          "row" => 2,
          "column" => "M",
          "sheet_name" => "Sheet1" },
        { "value" => "standard",
          "header" => "service_level",
          "row" => 2,
          "column" => "N",
          "sheet_name" => "Sheet1" },
        { "value" => "lcl",
          "header" => "cargo_class",
          "row" => 2,
          "column" => "O",
          "sheet_name" => "Sheet1" },
        { "value" => false,
          "header" => "internal",
          "row" => 2,
          "column" => "N/A",
          "sheet_name" => "Sheet1" },
        { "value" => "ZACPT",
          "header" => "transshipment",
          "row" => 2,
          "column" => "K",
          "sheet_name" => "Sheet1" },
        { "value" => 1.0,
          "header" => "wm_rate",
          "row" => 2,
          "column" => "V",
          "sheet_name" => "Sheet1" },
        { "value" => 1.0,
          "header" => "vm_rate",
          "row" => 2,
          "column" => "W",
          "sheet_name" => "Sheet1" },
        { "value" => nil,
          "header" => "origin_terminal",
          "row" => 2,
          "column" => "N/A",
          "sheet_name" => "Sheet1" },
        { "value" => nil,
          "header" => "destination_terminal",
          "row" => 2,
          "column" => "N/A",
          "sheet_name" => "Sheet1" },
        { "value" => 210.0,
          "header" => "min",
          "row" => 2,
          "column" => "T",
          "sheet_name" => "Sheet1" },
        { "value" => "Ocean Freight",
          "header" => "fee_name",
          "row" => 2,
          "column" => "S",
          "sheet_name" => "Sheet1" },
        { "value" => "bas",
          "header" => "fee_code",
          "row" => 2,
          "column" => "R",
          "sheet_name" => "Sheet1" },
        { "value" => "USD",
          "header" => "currency",
          "row" => 2,
          "column" => "P",
          "sheet_name" => "Sheet1" },
        { "value" => 210.0,
          "header" => "rate",
          "row" => 2,
          "column" => "U",
          "sheet_name" => "Sheet1" },
        { "value" => "PER_WM",
          "header" => "rate_basis",
          "row" => 2,
          "column" => "Q",
          "sheet_name" => "Sheet1" },
        { "value" => 0.0,
          "header" => "range_min",
          "row" => 2,
          "column" => "X",
          "sheet_name" => "Sheet1" },
        { "value" => 100.0,
          "header" => "range_max",
          "row" => 2,
          "column" => "Y",
          "sheet_name" => "Sheet1" },
        { "value" => nil,
          "header" => "base",
          "row" => 2,
          "column" => "N/A",
          "sheet_name" => "Sheet1" },
        { "value" => "A test",
          "header" => "remarks",
          "row" => 2,
          "column" => "Z",
          "sheet_name" => "Sheet1" },
        { "column" => "N/A",
          "header" => "transit_time",
          "row" => 2,
          "sheet_name" => "Sheet1",
          "value" => nil },
        { "value" => organization.id,
          "header" => "organization_id",
          "row" => 0,
          "column" => 0,
          "sheet_name" => "Sheet1" }]
    end

    it "returns a DataFrame of extracted values, with fallbacks" do
      expect(service.frame).to match_array(expected_results)
    end
  end
end
