# Drop all tables

Pricing.destroy_all
Vehicle.delete_all
TenantVehicle.delete_all
TransportCategory.delete_all
User.delete_all
TruckingPricing.delete_all
HubTrucking.delete_all
TruckingDestination.delete_all
Hub.delete_all
LocalCharge.delete_all
CustomsFee.delete_all
Location.delete_all
UserLocation.delete_all
Tenant.destroy_all