# frozen_string_literal: true

namespace :routing do
  task import_carriers: :environment do
    list = [
      { abbreviated_name: 'CONSOLIDATED',
        name: 'Consolidated Freight',
        code: 'CONSOL' },
      { abbreviated_name: 'ACL',
        name: 'Atlantic Container Line',
        code: 'ACLU' },
      { abbreviated_name: 'Alianca',
        name: 'Alianca',
        code: 'ANRM' },
      { abbreviated_name: 'AML',
        name: 'Alaska Marine Lines',
        code: 'AKMR' },
      { abbreviated_name: 'ANL',
        name: 'Australia National Line',
        code: 'ANNU' },
      { abbreviated_name: 'APL',
        name: 'American President Lines',
        code: 'APLU' },
      { abbreviated_name: 'Arkas',
        name: 'Arkas Container Transport S.A.',
        code: 'ARKU' },
      { abbreviated_name: 'ARRC',
        name: 'Atlantic Ro-Ro Carriers Inc',
        code: 'AROF' },
      { abbreviated_name: 'Bahri',
        name: 'Bahri / National Shipping Company of Saudi Arabia',
        code: 'NSAU' },
      { abbreviated_name: 'BCL',
        name: 'Bermuda Container Line',
        code: 'BCLU' },
      { abbreviated_name: 'CGL',
        name: 'Central Gulf Lines, Inc',
        code: 'CEGL' },
      { abbreviated_name: 'CCNI',
        name: 'Compagnia Chilena de Navigacion Interoceanica SA',
        code: 'CNIU' },
      { abbreviated_name: 'CHIPOLBROK',
        name: 'Chinese-Polish Joint Stock Shipping Company',
        code: 'CPJQ' },
      { abbreviated_name: 'CMA CGM',
        name: 'Compagnie Maritime d Affretement Compagnie Generale Maritime',
        code: 'CMDU' },
      { abbreviated_name: 'CNC Line',
        name: 'Cheng Lie Navigation Co.,Ltd',
        code: '11DX' },
      { abbreviated_name: 'COSCO',
        name: 'COSCO Container Lines',
        code: 'COSU' },
      { abbreviated_name: 'Crowley',
        name: 'Crowley',
        code: 'CMCU/CAMN' },
      { abbreviated_name: 'CSAV',
        name: 'Compania Sud Americana de Vapores',
        code: 'CHIW' },
      { abbreviated_name: 'CSAV Norasia',
        name: 'CSAV Norasia',
        code: 'NSLU' },
      { abbreviated_name: 'CSCL',
        name: 'China Shipping Container Lines Co',
        code: 'CHNJ' },
      { abbreviated_name: 'Delmas',
        name: 'Delmas',
        code: 'DAAE' },
      { abbreviated_name: 'Dole',
        name: 'Dole Ocean Cargo Express',
        code: 'DOLQ' },
      { abbreviated_name: 'Ecuadorian Line',
        name: 'Ecuadorian Line',
        code: 'EQLI' },
      { abbreviated_name: 'Eimskip',
        name: 'Eimskip',
        code: 'EIMU/EIMW' },
      { abbreviated_name: 'Emirates',
        name: 'Emirates Shipping Line',
        code: 'ESPU' },
      { abbreviated_name: 'Eukor',
        name: 'Eukor',
        code: 'EUKO' },
      { abbreviated_name: 'Evergreen',
        name: 'Evergreen Line',
        code: 'EGLV' },
      { abbreviated_name: 'FESCO',
        name: 'Far Eastern Shipping Company',
        code: 'FESO' },
      { abbreviated_name: 'GAL',
        name: 'Galborg',
        code: 'GFAL' },
      { abbreviated_name: 'Grieg Star',
        name: 'Grieg Star Shipping',
        code: 'ACSU' },
      { abbreviated_name: 'Grimaldi',
        name: 'Grimaldi',
        code: 'GRIU' },
      { abbreviated_name: 'GSL',
        name: 'Gold Star Line Ltd.',
        code: 'GSLU' },
      { abbreviated_name: 'GWF',
        name: 'Great White Fleet',
        code: 'UBCU' },
      { abbreviated_name: 'GES',
        name: 'Great Eastern Shipping Inc.',
        code: 'GESC' },
      { abbreviated_name: 'HAMBURG SUD',
        name: 'Hamburg Sud',
        code: 'SUDU' },
      { abbreviated_name: 'Hapag Lloyd',
        name: 'Hapag Lloyd Container Line/A>',
        code: 'HLCU' },
      { abbreviated_name: 'HMM',
        name: 'Hyundai Merchant Marine Co., Ltd.',
        code: 'HDMU' },
      { abbreviated_name: 'Hoegh',
        name: 'Hoegh Autoliners',
        code: 'HUAU' },
      { abbreviated_name: 'Horizon',
        name: 'Horizon Lines',
        code: 'HRZU' },
      { abbreviated_name: 'Hyde Shipping',
        name: 'Hyde Shipping',
        code: 'HYDU' },
      { abbreviated_name: 'ICL',
        name: 'Independent Container Line',
        code: 'IILU' },
      { abbreviated_name: 'IMC',
        name: 'Industrial Maritime Carriers (Intermarine)',
        code: 'IDMC' },
      { abbreviated_name: 'Interocean Lines',
        name: 'Interocean Lines',
        code: 'INOC' },
      { abbreviated_name: 'K Line',
        name: 'Kawasaki Kisen Kaisha, Ltd.',
        code: 'KKLU' },
      { abbreviated_name: 'King Ocean',
        name: 'King Ocean Sercies',
        code: 'KOSL' },
      { abbreviated_name: 'KMTC',
        name: 'Korea Marine Transport Co., Ltd.',
        code: 'KMTU' },
      { abbreviated_name: 'Libra',
        name: 'Companhia Libra de Navegacao',
        code: 'CLIB' },
      { abbreviated_name: 'LGL',
        name: 'Liberty Global Logistics, LLC',
        code: 'LGLT' },
      { abbreviated_name: 'Linea Messina',
        name: 'Linea Messina',
        code: 'LMCU' },
      { abbreviated_name: 'Maersk',
        name: 'Maersk Line',
        code: 'MAEU' },
      { abbreviated_name: 'Marfret',
        name: 'Marfret Compagnie Maritime',
        code: 'MFTU' },
      { abbreviated_name: 'Maruba',
        name: 'Maruba',
        code: 'MRUB' },
      { abbreviated_name: 'Matson',
        name: 'Matson',
        code: 'MATS' },
      { abbreviated_name: 'MCC',
        name: 'MCC Transport Pte. Ltd.',
        code: 'MCCQ' },
      { abbreviated_name: 'MISC',
        name: 'Malaysia International Shipping Corporation Berhad',
        code: 'MISC' },
      { abbreviated_name: 'MSC',
        name: 'Mediterranean Shipping Company',
        code: 'MSCU' },
      { abbreviated_name: 'NDS',
        name: 'Nile Dutch Africa Line',
        code: 'NIDU' },
      { abbreviated_name: 'Neptune',
        name: 'Neptune Shipping Line',
        code: 'NOSU' },
      { abbreviated_name: 'Nordana',
        name: 'Nordana Line',
        code: 'NODA' },
      { abbreviated_name: 'Ocean Network Express',
        name: 'Ocean Network Express (ONE Line)',
        code: 'ONEY' },
      { abbreviated_name: 'OOCL',
        name: 'Orient Overseas Container Line Ltd.',
        code: 'OOLU' },
      { abbreviated_name: 'PHT',
        name: 'Pasha Hawaii Transport Lines',
        code: 'PSHI' },
      { abbreviated_name: 'PIL',
        name: 'Pacific International Lines',
        code: 'PCIU' },
      { abbreviated_name: 'PMO',
        name: 'PM&O Lines',
        code: 'PMOL' },
      { abbreviated_name: 'PL',
        name: 'Polynesia Line',
        code: 'PLLU' },
      { abbreviated_name: 'Rickmers Line',
        name: 'Rickmers Linie',
        code: 'RCKI' },
      { abbreviated_name: 'Safmarine',
        name: 'Safmarine',
        code: 'SAFM' },
      { abbreviated_name: 'Sallaum',
        name: 'Sallaum Lines',
        code: 'SLAQ' },
      { abbreviated_name: 'SAM',
        name: 'Samskip, Inc.',
        code: 'SKII' },
      { abbreviated_name: 'SCI',
        name: 'The Shipping Coporation of India Ltd.',
        code: 'SCIU' },
      { abbreviated_name: 'Seaboard Marine',
        name: 'Seaboard Marine',
        code: 'SMLU' },
      { abbreviated_name: 'SeaFreight',
        name: 'SeaFreight Line',
        code: 'SEFN' },
      { abbreviated_name: 'Seago',
        name: 'Seago Line',
        code: 'SEJJ' },
      { abbreviated_name: 'Siem Car',
        name: 'Siem Car Carriers AS',
        code: 'SCYE' },
      { abbreviated_name: 'Sinokor',
        name: 'Sinokor Merchant Marine Co.,Ltd',
        code: 'SKLU' },
      { abbreviated_name: 'Swire',
        name: 'Swire Shipping',
        code: 'CHVW' },
      { abbreviated_name: 'TS',
        name: 'Thorco Shipping',
        code: 'THZS' },
      { abbreviated_name: 'TSC',
        name: 'TOHO Shipping Co., Ltd',
        code: 'TOHO' },
      { abbreviated_name: 'TOT',
        name: 'TOTE Maritime',
        code: 'TOTE' },
      { abbreviated_name: 'Turkon',
        name: 'Turkon Line Inc',
        code: 'TRKU' },
      { abbreviated_name: 'UAL',
        name: 'Universal Africa Lines',
        code: 'UALC' },
      { abbreviated_name: 'USL',
        name: 'US Lines',
        code: 'USLU' },
      { abbreviated_name: 'WEC',
        name: 'West European Container Lines',
        code: 'WECU' },
      { abbreviated_name: 'Westwood',
        name: 'Westwood Shipping Lines',
        code: 'WWSU' },
      { abbreviated_name: 'WHL',
        name: 'Wan Hai Lines',
        code: '22AA' },
      { abbreviated_name: 'WLS',
        name: 'World Logistics Service (USA) Inc',
        code: 'WDLS' },
      { abbreviated_name: 'WWL',
        name: 'Wallenius Wilhelmsen Logistics',
        code: 'WLWH' },
      { abbreviated_name: 'YML',
        name: 'Yang Ming Line',
        code: 'YMLU' },
      { abbreviated_name: 'ZIM',
        name: 'ZIM Integrated Shipping Services Ltd',
        code: 'ZIMU' }
    ]
    Trucking::Courier.all.group_by(&:name).keys.each do |courier|
      list << { abbreviated_name: courier,
                name: courier,
                code: nil }
    end
    Routing::Carrier.import(list)
  end
end
