# frozen_string_literal: true

# Disallow Merge Commits - force rebasing
if git.commits.any? { |c| c.message =~ /^Merge branch/ }
  failure 'Please rebase to get rid of the merge commits in this PR'
end

# Disallow Draft commits
if git.commits.any? { |c| c.message.split("\n").first =~ /wip/i }
  failure 'Please rebase to remove work in progress commits'
end
