source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in money_cache.gemspec
gemspec

gem "activesupport"

group :test do
  gem "rspec_junit_formatter"
  gem "webmock"
end
