development:
  host: 'localhost'
  port: '6379'
test:
  host: 'imcr-new-cache.7gkcnp.0001.euc1.cache.amazonaws.com'
  port: '6379'
production:
  host: 'imcr-new-cache.7gkcnp.0001.euc1.cache.amazonaws.com'
  port: '6379'