# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 23ecc149c3836f9bfd6a6a42cef61bccab2c433e7001f85ca5f22019f1035b833946984c094ead03ba563967d1dcc5a0a92799e3e9ef6da1e217f22f350a754c
  google_maps_server_api_key: <%= ENV["GOOGLE_MAPS_SERVER_API_KEY"] %>
  sendgrid_username: <%= ENV["SENDGRID_USERNAME"] %>
  sendgrid_password: <%= ENV["SENDGRID_PASSWORD"] %>

test:
  secret_key_base: f4049768a8c82b36cf6315693ce4310539e0dbc6ba131b865e17254afd0cf206268516014238c13d99b2ea7e78c15a14af05b2ec8d07e9a216136841a403af1b
  google_maps_server_api_key: <%= ENV["GOOGLE_MAPS_SERVER_API_KEY"] %>
  sendgrid_username: <%= ENV["SENDGRID_USERNAME"] %>
  sendgrid_password: <%= ENV["SENDGRID_PASSWORD"] %>

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_maps_server_api_key: <%= ENV["GOOGLE_MAPS_SERVER_API_KEY"] %>
  sendgrid_username: <%= ENV["SENDGRID_USERNAME"] %>
  sendgrid_password: <%= ENV["SENDGRID_PASSWORD"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_maps_server_api_key: <%= ENV["GOOGLE_MAPS_SERVER_API_KEY"] %>
  sendgrid_username: <%= ENV["SENDGRID_USERNAME"] %>
  sendgrid_password: <%= ENV["SENDGRID_PASSWORD"] %>
