aws:
  bucket:
  ingest_bucket:

cors:
  origins: <%= ENV['CORS_ORIGINS'] %>

elasticsearch:
  url:

emails:
  booking:
  domain:
  support: support@itsmycargo.com

passwords:
  default: IMC123456789

fixer:
  api_key:

google:
  api_key:

open_exchange_rate:
  app_id:

google_sign_in:
  client_id:
  client_secret:

mailer:
  queue:

mailgun:
  api_key:
  domain:

sentry:
  dsn: 'https://bc342488f6d646bf94b880fc5c5dc76a@o410390.ingest.sentry.io/5284300'

smtp:
  host:
  domain:
  username:
  password:

uploads:
  secret:
