aws:
  access_key_id:
  secret_access_key:
  region: eu-central-1
  bucket:

cors:
  origins: <%= ENV['CORS_ORIGINS'] %>

fixer:
  api_key:

google:
  api_key:

smtp:
  host:
  domain:
  username:
  password:

mailer:
  queue:
