aws:
  access_key_id:
  secret_access_key:
  region: eu-central-1
  bucket:

breezy:
  secret: iqY!O}_LOnP]A-]bkBq$WJRXSn9t%0-(
  url: https://breezy-pdf.armada.itsmycargo.io

cors:
  origins: <%= ENV['CORS_ORIGINS'] %>

elasticsearch:
  url:

emails:
  booking:
  domain:
  support: support@itsmycargo.com

fixer:
  api_key:

google:
  api_key:

google_sign_in:
  client_id:
  client_secret:

mailer:
  queue:

mailgun:
  api_key:
  domain:

sentry:
  dsn: 'https://9159192f3db04fd3bdb6779d433e1429:995839ef5a0d4b66a4acafb771ccf9d7@sentry.itsmycargo.tech/2'

smtp:
  host:
  domain:
  username:
  password:
