aws:
  access_key_id:
  secret_access_key:
  region: eu-central-1
  bucket:

breezy:
  secret: iqY!O}_LOnP]A-]bkBq$WJRXSn9t%0-(
  url: https://breezypdf.itsmycargo.tech

cors:
  origins: <%= ENV['CORS_ORIGINS'] %>

fixer:
  api_key:

google:
  api_key:

smtp:
  host:
  domain:
  username:
  password:

mailer:
  queue:
