# Services
disk:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

amazon:
  service: S3
  bucket: <%= Settings.aws.bucket %>

# Configuration
development:
  service: Cascade
  primary: disk
  secondary: amazon

review:
  service: Cascade
  primary: disk
  secondary: amazon

staging:
  service: Cascade
  primary: disk
  secondary: amazon
