# Services
disk:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

amazon:
  service: S3
  access_key_id: <%= Settings.aws.access_key_id %>
  secret_access_key: <%= Settings.aws.secret_access_key %>
  region: <%= Settings.aws.region %>
  bucket: <%= Settings.aws.bucket %>

# Configuration
development:
  service: Cascade
  primary: disk
  secondary: amazon

review:
  service: Cascade
  primary: disk
  secondary: amazon

staging:
  service: Cascade
  primary: disk
  secondary: amazon
