apiVersion: v1
kind: Service
metadata:
  name: {{ include "polaris.fullname" . }}-webserver
  labels:
    {{- include "polaris.labels" . | nindent 4 }}
    app.kubernetes.io/component: webserver
spec:
  type: {{ .Values.webserver.service.type }}
  ports:
    - port: {{ .Values.webserver.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "polaris.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: webserver
