{{- if .Values.webserver.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "webserver.serviceAccountName" . }}
  labels:
    {{- include "polaris.labels" . | nindent 4 }}
  {{- with .Values.webserver.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
