# frozen_string_literal: true

required "1:1", "A:?", %w[MOT CARRIER SERVICE_LEVEL]

column "service",
  sanitizer: "text",
  validator: "string",
  required: true,
  type: :object,
  alternative_keys: ["service_level"],
  fallback: "standard"
column "group_id",
  sanitizer: "text",
  validator: "optional_string",
  required: false,
  type: :object
column "group_name",
  sanitizer: "text",
  validator: "optional_string",
  required: false,
  type: :object
column "effective_date",
  sanitizer: "date",
  validator: "date",
  required: false,
  type: :object
column "expiration_date",
  sanitizer: "date",
  validator: "date",
  required: false,
  type: :object
column "origin_locode",
  sanitizer: "text",
  validator: "optional_locode",
  required: false,
  type: :object
column "origin",
  sanitizer: "text",
  validator: "optional_string",
  required: false,
  type: :object
column "country_origin",
  sanitizer: "text",
  validator: "optional_string",
  required: false,
  type: :object
column "destination_locode",
  sanitizer: "text",
  validator: "optional_locode",
  required: false,
  type: :object
column "destination",
  sanitizer: "text",
  validator: "optional_string",
  required: false,
  type: :object
column "country_destination",
  sanitizer: "text",
  validator: "optional_string",
  required: false,
  type: :object
column "mode_of_transport",
  sanitizer: "downcase",
  validator: "string",
  required: false,
  alternative_keys: ["mot"],
  type: :object
column "carrier",
  sanitizer: "text",
  validator: "string",
  required: false,
  type: :object,
  fallback: organization.slug
column "service_level",
  sanitizer: "text",
  validator: "string",
  required: false,
  type: :object
column "cargo_class",
  sanitizer: "downcase",
  validator: "string",
  required: true,
  alternative_keys: ["load_type"],
  type: :object
column "internal",
  sanitizer: "boolean",
  validator: "optional_boolean",
  required: false,
  type: :object
column "transshipment",
  sanitizer: "text",
  validator: "optional_string",
  required: false,
  type: :object
column "wm_rate",
  sanitizer: "decimal",
  validator: "optional_numeric",
  required: false,
  alternative_keys: ["wm_ratio"],
  type: :object
column "vm_rate",
  sanitizer: "decimal",
  validator: "optional_numeric",
  required: false,
  alternative_keys: ["vm_ratio"],
  type: :object
column "origin_terminal",
  sanitizer: "text",
  validator: "optional_string",
  required: false,
  type: :object
column "destination_terminal",
  sanitizer: "text",
  validator: "optional_string",
  required: false,
  type: :object
column "remarks",
  sanitizer: "text",
  validator: "optional_string",
  required: false,
  type: :object

prerequisite "Pricings"

add_extractor "TenantVehicle"
add_extractor "RouteHubs"
add_extractor "Itinerary"
add_extractor "Group"

add_extractor "Pricing"
add_formatter "Remark"

model_importer Legacy::Note
target_model Legacy::Note
