#!/bin/bash

if [[ $# -lt 2 ]];
then
  echo "Usage: $0 NAME DIR"
  exit 1
fi

ROOTDIR="$(cd "$( dirname "${BASH_SOURCE[0]}/" )/../" >/dev/null 2>&1 && pwd )"

# Setup Environment
: "${CI:=1}"
: "${COVERAGE:=1}"
: "${COVERAGE_DIR:="${ROOTDIR}/coverage"}"
: "${DISABLE_PROFILE:=1}"
: "${RAILS_ENV:=test}"
: "${SEED:=$(((RANDOM % 0xFFFF) + 1))}"
: "${SPEC_OPTS:="--order rand:${SEED} --format progress --color --format RspecJunitFormatter --out junit.xml"}"
: "${WORKSPACE_ROOT:="${ROOTDIR}"}"

export CI COVERAGE COVERAGE_DIR DISABLE_PROFILE RAILS_ENV SEED SPEC_OPTS WORKSPACE_ROOT

(
  cd "$2" || exit 2
  bin/rspec
)

exit $?
