#!/bin/bash

trap 'trap - SIGTERM && kill -- -$$' SIGINT SIGTERM

# Helpers
fail () {
  echo -e "\033[0;31m$1\033[0m"
}
success () {
  echo -e "\033[0;32m$1\033[0m"
}
warn () {
  echo -e "\033[0;33m$1\033[0m"
}

ci-runner () {
  warn "--- Running tests for $1 ---"
  "${SCRIPTDIR}/ci-runner" "$1" "$2"
  ret=$?

  if [[ $ret -eq 0 ]];
  then
    success "--- SUCCESS for $1 ---"
  else
    fail "--- FAILURE for $1 ---"
  fi

  return $ret
}

ci-app () {
  ci-runner app "${ROOTDIR}"
  return $?
}

ci-engines () {
  exitcode=0

  for engine in $("${SCRIPTDIR}/ci-finder");
  do
    ci-runner "${engine}" "engines/${engine}"
    ret=$?
    [[ $ret -ne 0 ]] && FAILURES=( "${FAILURES[@]}" "${engine}" )

    exitcode=$((exitcode|$ret))
  done

  return $exitcode
}

ci-lib () {
  exitcode=0
    for lib in $"${ROOTDIR}/lib"/*/;
  do
    dir=${lib%*/}
    dirname=${dir##*/}
    if [ "${dirname}" = "money_cache" ]; then
      ci-runner "${dirname}" "lib/${dirname}"
    fi
    exitcode=$((exitcode|$?))
  done

  return $exitcode
}

ROOTDIR="$(cd "$( dirname "${BASH_SOURCE[0]}/" )/../" >/dev/null 2>&1 && pwd )"
SCRIPTDIR="$ROOTDIR/scripts"
REPORTSDIR="$ROOTDIR/reports"
FAILURES=()

# Set Environment
: "${SEED:=$(((RANDOM % 0xFFFF) + 1))}"
export SEED

mkdir -p "${REPORTSDIR}"

exitcode=0

for run in "$@";
do
  case "$run" in
    all )
      ci-app
      exitcode=$((exitcode | $?))
      ci-engines
      exitcode=$((exitcode | $?))
      ;;
    app )
      ci-app
      exitcode=$((exitcode | $?))
      ci-lib
      exitcode=$((exitcode | $?))
      ;;
    engines )
      ci-engines
      exitcode=$((exitcode | $?))
      ;;
    lib )
      ci-lib
      exitcode=$((exitcode | $?))
      ;;
    * )
      echo "Usage: $0 [all|app|lib|engines]"
      exit 1
      ;;
  esac
done

echo "FAILURES:"
echo "${FAILURES[@]}"

exit $exitcode
