#!/bin/bash -e

TARGET_BRANCH=$(curl -s --header "PRIVATE-TOKEN:${PRONTO_GITLAB_API_PRIVATE_TOKEN}" "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/merge_requests?source_branch=${CI_COMMIT_REF_NAME}" |jq -r '.[].target_branch')

DEFAULT_FORMATTER=$(test -n "${TARGET_BRANCH}" && echo "text gitlab" || echo text)

: ${FORMATTER:=$DEFAULT_FORMATTER}

echo "Pronto"
echo ""
echo "Target Branch: ${TARGET_BRANCH:-dev}"
echo "    Formatter: ${FORMATTER}"
echo ""

echo "Installing NPM packages..."
(cd client/; npm install)

echo "Running Pronto..."
pronto run -f ${FORMATTER} -c origin/${TARGET_BRANCH:-dev}
