#!/bin/bash -e

TARGET_BRANCH=$(curl -s --header "PRIVATE-TOKEN:${PRONTO_GITLAB_API_PRIVATE_TOKEN}" "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/merge_requests?source_branch=${CI_COMMIT_REF_NAME}" |jq -r '.[].target_branch')

echo "Target Branch: ${TARGET_BRANCH:-dev}"

pronto run -f gitlab -c origin/${TARGET_BRANCH:-dev}
