# frozen_string_literal: true

all_labels = github.api.labels(github.pr_json[:base][:repo][:full_name]).map(&:name)
pr_labels = github.pr_json[:labels].map { |l| l[:name] }
new_labels = []

all_files = git.added_files + git.modified_files + git.deleted_files

## Applications
new_labels << 'dipper' if all_files.include?('client/*')
new_labels << 'polaris' if all_files.any? { |f| f =~ /\A(?!client)/ }

## Migrations
new_labels << 'migrations' if all_files.include?('db/migrate/*')

## Translations
rails_translations = all_files.include? 'config/locales/*'
js_translations = all_files.include? 'client/i18n/**/*'
new_labels << 'translations' if rails_translations || js_translations

## Drafts
new_labels << 'draft' if git.commits.any? { |c| c.message =~ /\Awip/i }

### Set new labels
(new_labels - pr_labels).uniq.each do |label|
  github.api.add_labels_to_an_issue(github.pr_json[:base][:repo][:full_name], github.pr_json['number'], [label])
end
