# frozen_string_literal: true

source "https://rubygems.org"

gemspec

eval_gemfile "Gemfile.runtime"

gem "measured-itsmycargo", path: "../../gems/measured-itsmycargo"
gem "shared-factory", path: "../../gems/shared-factory"

gem "cargo", path: "../cargo"
gem "companies", path: "../companies"
gem "organization_manager", path: "../organization_manager"
gem "quotations", path: "../quotations"
