aws:
  bucket: assets.itsmycargo.com
  ingest_bucket: <%= ENV.fetch('AWS_INGEST_BUCKET', 'itsmycargo-ingest') %>

carta:
  token: <%= Rails.application.credentials.dig(:development, :carta, :token) %>
  url: https://geo.itsmycargo.com/v1

emails:
  booking: test@itsmycargo.tech
  domain: itsmycargo.test
  support: support@itsmycargo.tech

passwords:
  default: IMC123456789

open_exchange_rate:
  app_id: <%= ENV.fetch('OXR_APP_ID') { Rails.application.credentials.dig(:development, :open_exchange_rate, :app_id) } %>

google:
  api_key: <%= ENV.fetch('GOOGLE_MAPS_SERVER_API_KEY') { Rails.application.credentials.dig(:development, :google, :api_key) } %>

google_sign_in:
  client_id: 924497825642-9tirmrp45vvjd82r45sjd4q8njj6laa2.apps.googleusercontent.com
  client_secret: <%= Rails.application.credentials.dig(:development, :google_sign_in, :client_secret) %>

geodata:
  path: "development/postcodes"

uploads:
  secret: <%= Rails.application.credentials.dig(:development, :uploads, :secret) %>

airflow: https://airflow-dev.itsmycargo.tech
