aws:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  bucket: assets.itsmycargo.com

emails:
  domain: itsmycargo.tech

fixer:
  api_key: <%= ENV.fetch('FIXER_API_KEY') { Rails.application.credentials.dig(:development, :fixer, :api_key) } %>

google:
  api_key: <%= ENV.fetch('GOOGLE_MAPS_SERVER_API_KEY') { Rails.application.credentials.dig(:development, :google, :api_key) } %>

google_sign_in:
  client_id: 924497825642-9tirmrp45vvjd82r45sjd4q8njj6laa2.apps.googleusercontent.com
  client_secret: <%= Rails.application.credentials.dig(:development, :google_sign_in, :client_secret) %>
