aws:
  bucket: assets.itsmycargo.com
  ingest_bucket: <%= ENV['AWS_INGEST_BUCKET'] %>

carta:
  token: <%= Rails.application.credentials.dig(:production, :carta, :token) %>
  url: https://geo.itsmycargo.com/v1

elasticsearch:
  url: <%= Rails.application.credentials.dig(:production, :elasticsearch, :url) %>

emails:
  booking: bookingemails@itsmycargo.com
  domain: itsmycargo.shop

passwords:
  default: IMC123456789

open_exchange_rate:
  app_id: <%= Rails.application.credentials.dig(:production, :open_exchange_rate, :app_id) %>

google:
  api_key: <%= Rails.application.credentials.dig(:production, :google, :api_key) %>

google_sign_in:
  client_id: 924497825642-9tirmrp45vvjd82r45sjd4q8njj6laa2.apps.googleusercontent.com
  client_secret: <%= Rails.application.credentials.dig(:production, :google_sign_in, :client_secret) %>

mailer:
  queue: https://sqs.eu-central-1.amazonaws.com/003688427525/mailers

mailgun:
  api_key: <%= Rails.application.credentials.dig(:production, :mailgun, :api_key) %>
  domain: itsmycargo.shop

smtp:
  host: smtp.sendgrid.net
  domain: itsmycargo.com
  username: apikey
  password: <%= Rails.application.credentials.dig(:production, :smtp, :password) %>

uploads:
  secret: <%= Rails.application.credentials.dig(:production, :uploads, :secret) %>

airflow: https://airflow.itsmycargo.tech
