aws:
  access_key_id: <%= Rails.application.credentials.dig(:production, :aws, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:production, :aws, :secret_access_key) %>
  region: eu-central-1
  bucket: assets.itsmycargo.com

fixer:
  api_key: <%= Rails.application.credentials.dig(:production, :fixer, :api_key) %>

google_sign_in:
  client_id: 924497825642-9tirmrp45vvjd82r45sjd4q8njj6laa2.apps.googleusercontent.com
  client_secret: <%= Rails.application.credentials.dig(:production, :google_sign_in, :client_secret) %>

google:
  api_key: <%= Rails.application.credentials.dig(:production, :google, :api_key) %>

mailer:
  queue: https://sqs.eu-central-1.amazonaws.com/003688427525/mailers

smtp:
  host: smtp.sendgrid.net
  domain: itsmycargo.com
  username: apikey
  password: <%= Rails.application.credentials.dig(:production, :smtp, :password) %>
