aws:
  ingest_bucket: "itsmycargo-ingest"

carta:
  token: FAKECARTATOKEN
  url: fakecartaurl

elasticsearch:
  url: http://localhost:9200/

emails:
  booking: itsmycargodev@gmail.com
  domain: itsmycargo.test
  support: support@itsmycargo.tech

passwords:
  default: IMC123456789

open_exchange_rate:
  app_id: FAKEKEY

google:
  api_key: FAKEKEY

uploads:
  secret: FAKEKEY

airflow: https://example.com
