emails:
  booking: itsmycargodev@gmail.com
  domain: itsmycargo.test
  support: support@itsmycargo.tech

passwords:
  default: IMC123456789

open_exchange_rate:
  app_id: FAKEKEY

google:
  api_key: FAKEKEY

uploads:
  secret: FAKEKEY
