# frozen_string_literal: true

NO_NEW_SPEC_MESSAGE = <<~MSG
  You've made some app changes, but didn't add any tests.
  Please add tests covering added or changed logic.
MSG

has_app_changes = !git.modified_files.grep(%r{\A(app|lib|db/migrate)/}).empty?
has_spec_changes = !git.modified_files.grep(%r{\Aspec/}).empty?

if has_app_changes && !has_spec_changes
  failure format(NO_NEW_SPEC_MESSAGE), sticky: false
end
