# frozen_string_literal: true

jira_keys = 'IMC'

# JIRA tickets
jira.check(
  key: [jira_keys],
  url: 'https://itsmycargo.atlassian.net/browse',
  search_title: true,
  search_commits: true,
  fail_on_warning: false,
  report_missing: false
)

# Support multiple JIRA projects
jira_keys_regexp = Regexp.new(/((?:#{jira_keys})-[0-9]+)/)

# Search Commits
jira_issues = git.commits.map { |commit| commit.message.scan(jira_keys_regexp) }.flatten.compact.uniq
fix_chore_commits = git.commits.any? { |commit| !commit.message.scan(/\A(chore|fix|hotfix):/i).empty? }

# MR Tickets
pr_title_issues = github.pr_title.scan(jira_keys_regexp).flatten.uniq
fix_chore_pr = !github.pr_title.scan(/(chore|fix|hotfix):/i).empty?

message = ''
if jira_issues.empty? && !fix_chore_commits
  message += <<~MESSAGE
    This Merge Request does not mention any JIRA tickets in any of its commit messages.

    Please consider to rebase and rewording your commit messages to start with JIRA Ticket, as
    it helps to pinpoint reasoning for any changes in the future, especially if there is regression.
  MESSAGE
end

if pr_title_issues.empty? && !fix_chore_pr
  message += <<~MESSAGE
    This Merge Request does not mention JIRA Ticket in its title.

    Please consider to editing Merge Request and adding JIRA Ticket to its title
    as this makes it easy to track open merge requests and keep JIRA Board in sync,
    as well to make sure we always deploy most important code to production at right time.
  MESSAGE
end

if !pr_title_issues.empty? && !(pr_title_issues - jira_issues).empty?
  message += <<-MESSAGE
    This Merge Request mentions different JIRA tickets in commit messages and title.
    Please make sure that correct ticket numbers are mentioned in commits and title.
  MESSAGE
end

unless message.empty?
  warn message
end
