apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "polaris.fullname" . }}-worker
  labels:
    {{- include "polaris.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  {{- if not .Values.worker.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "polaris.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      {{- with .Values.worker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "polaris.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "worker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.worker.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-migrations
          securityContext:
            {{- toYaml .Values.worker.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - bundle
          - exec
          - rails
          - db:abort_if_pending_migrations
          env:
            - name: RAILS_ENV
              value: production
            - name: RELEASE
              value: {{ .Values.version.release }}
            - name: STAGE
              value: {{ .Values.stage }}
          volumeMounts:
            - mountPath: /app/config/master.key
              name: config
              readOnly: true
              subPath: master.key
            - mountPath: /app/.env
              name: config
              readOnly: true
              subPath: env
      containers:
        - name: worker
          securityContext:
            {{- toYaml .Values.worker.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - bundle
            - exec
            - sidekiq
            - --config
            - config/sidekiq.yml
            - --timeout
            - "600"
          ports:
          - containerPort: 7433
          livenessProbe:
            httpGet:
              path: /healthz
              port: 7433
            periodSeconds: 10
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: /healthz
              port: 7433
            initialDelaySeconds: 10
            periodSeconds: 1
            timeoutSeconds: 5
            failureThreshold: 10
          resources:
            {{- toYaml .Values.worker.resources.default| nindent 12 }}
          env:
            - name: RAILS_ENV
              value: production
            - name: RELEASE
              value: {{ .Values.version.release }}
            - name: STAGE
              value: {{ .Values.stage }}
            - name: ENABLE_CLOUDWATCH
              value: "true"
          volumeMounts:
            - mountPath: /app/config/master.key
              name: config
              readOnly: true
              subPath: master.key
            - mountPath: /app/.env
              name: config
              readOnly: true
              subPath: env

      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml .worker | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "polaris.fullname" . }}
