# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in charge_calculator.gemspec
gemspec

gem 'rule_engine', git: 'https://github.com/itsmycargo/rule-engine.git'
# gem 'rule_engine', git: 'git@github.com:itsmycargo/rule-engine.git'

gem 'pry'
