# frozen_string_literal: true

source "https://rubygems.org"

gemspec

eval_gemfile "Gemfile.runtime"

gem "shared-factory", path: "../../gems/shared-factory"

gem "legacy", path: "../legacy"
gem "organizations", path: "../organizations"
gem "profiles", path: "../profiles"
gem "users", path: "../users"
