# frozen_string_literal: true

FactoryBot.define do
  factory :excel_data_services_section_data, class: "Rover::DataFrame" do
    transient do
      types { {} }
      data { [] }
      organization { FactoryBot.create(:organizations_organization) }
      default_group { FactoryBot.create(:groups_group, :default, organization: organization) }
    end

    initialize_with do
      Rover::DataFrame.new(data, types: types)
    end

    trait :pricings do
      data do
        [{
          "carrier_code" => "msc",
          "row" => 2,
          "sheet_name" => "Sheet1",
          "service" => "standard",
          "group_id" => "1b536235-4bd4-49a7-874e-489ce9e2d251",
          "group_name" => "TEST_GROUP",
          "effective_date" => Date.parse("Wed, 30 Jun 2021"),
          "expiration_date" => Date.parse("Thu, 30 Dec 2021"),
          "origin_locode" => "SEGOT",
          "origin_hub" => nil,
          "origin_country" => nil,
          "destination_locode" => "CNSHA",
          "destination_hub" => nil,
          "destination_country" => nil,
          "mode_of_transport" => "ocean",
          "carrier" => "MSC",
          "service_level" => "standard",
          "cargo_class" => "lcl",
          "internal" => false,
          "transshipment" => "ZACPT",
          "wm_rate" => 1.0,
          "vm_rate" => 1.0,
          "origin_terminal" => nil,
          "destination_terminal" => nil,
          "fee_min" => 210.0,
          "fee_name" => "Ocean Freight",
          "fee_code" => "bas",
          "currency" => "USD",
          "rate" => 210.0,
          "rate_basis" => "PER_WM",
          "range_min" => nil,
          "range_max" => nil,
          "base" => nil,
          "remarks" => nil,
          "organization_id" => organization.id,
          "Dynamic:ofr" => nil,
          "Dynamic:lss" => nil
        },
          {
            "carrier_code" => "msc",
            "row" => 3,
            "sheet_name" => "Sheet1",
            "service" => "standard",
            "group_id" => "1b536235-4bd4-49a7-874e-489ce9e2d251",
            "group_name" => "TEST_GROUP",
            "effective_date" => Date.parse("Wed, 30 Jun 2021"),
            "expiration_date" => Date.parse("Thu, 30 Dec 2021"),
            "origin_locode" => nil,
            "origin_hub" => "Gothenburg",
            "origin_country" => "Sweden",
            "destination_locode" => nil,
            "destination_hub" => "Shanghai",
            "destination_country" => "China",
            "mode_of_transport" => "ocean",
            "carrier" => "MSC",
            "service_level" => "standard",
            "cargo_class" => "lcl",
            "internal" => false,
            "transshipment" => nil,
            "wm_rate" => 1.0,
            "vm_rate" => 1.0,
            "origin_terminal" => nil,
            "destination_terminal" => nil,
            "fee_name" => "IMO 2020",
            "fee_code" => "imo 2020",
            "currency" => "USD",
            "remarks" => nil,
            "rate" => 40.0,
            "rate_basis" => "PER_WM",
            "range_min" => nil,
            "range_max" => nil,
            "base" => nil,
            "fee_min" => 40.0,
            "organization_id" => organization.id,
            "Dynamic:ofr" => nil,
            "Dynamic:lss" => nil
          },
          {
            "carrier_code" => "msc",
            "row" => 4,
            "sheet_name" => "Sheet1",
            "service" => "standard",
            "group_id" => "1b536235-4bd4-49a7-874e-489ce9e2d251",
            "group_name" => "TEST_GROUP",
            "effective_date" => Date.parse("Wed, 30 Jun 2021"),
            "expiration_date" => Date.parse("Thu, 30 Dec 2021"),
            "origin_locode" => "SEGOT",
            "origin_hub" => "Gothenburg",
            "origin_country" => "Sweden",
            "destination_locode" => "CNSHA",
            "destination_hub" => "Shanghai",
            "destination_country" => "China",
            "mode_of_transport" => "ocean",
            "carrier" => "MSC",
            "service_level" => "standard",
            "cargo_class" => "lcl",
            "internal" => false,
            "transshipment" => nil,
            "wm_rate" => 1.0,
            "vm_rate" => 1.0,
            "origin_terminal" => nil,
            "destination_terminal" => nil,
            "fee_min" => 210.0,
            "fee_name" => "Bunker Adjustment Fee",
            "fee_code" => "baf",
            "currency" => "USD",
            "rate" => 210.0,
            "rate_basis" => "PER_WM",
            "range_min" => 0.0,
            "range_max" => 1e2,
            "base" => nil,
            "remarks" => nil,
            "organization_id" => organization.id,
            "Dynamic:ofr" => nil,
            "Dynamic:lss" => nil
          },
          {
            "carrier_code" => "msc",
            "row" => 5,
            "sheet_name" => "Sheet1",
            "service" => "standard",
            "group_id" => "1b536235-4bd4-49a7-874e-489ce9e2d251",
            "group_name" => "TEST_GROUP",
            "effective_date" => Date.parse("Wed, 30 Jun 2021"),
            "expiration_date" => Date.parse("Thu, 30 Dec 2021"),
            "origin_locode" => "SEGOT",
            "origin_hub" => "Gothenburg",
            "origin_country" => "Sweden",
            "destination_locode" => "CNSHA",
            "destination_hub" => "Shanghai",
            "destination_country" => "China",
            "mode_of_transport" => "ocean",
            "carrier" => "MSC",
            "service_level" => "standard",
            "cargo_class" => "lcl",
            "internal" => false,
            "transshipment" => nil,
            "wm_rate" => 1.0,
            "vm_rate" => 1.0,
            "origin_terminal" => nil,
            "destination_terminal" => nil,
            "fee_min" => 210.0,
            "fee_name" => "Bunker Adjustment Fee",
            "fee_code" => "baf",
            "currency" => "USD",
            "rate" => 110.0,
            "rate_basis" => "PER_WM",
            "range_min" => 1e2,
            "range_max" => 5e2,
            "base" => nil,
            "remarks" => nil,
            "organization_id" => organization.id,
            "Dynamic:ofr" => nil,
            "Dynamic:lss" => nil
          },
          {
            "carrier_code" => "msc",
            "row" => 2,
            "sheet_name" => "Sheet2",
            "service" => "standard",
            "group_id" => nil,
            "group_name" => nil,
            "effective_date" => Date.parse("Tue, 29 Dec 2020"),
            "expiration_date" => Date.parse("Fri, 31 Dec 2021"),
            "origin_locode" => "SEGOT",
            "origin_hub" => nil,
            "origin_country" => nil,
            "destination_locode" => "CNSHA",
            "destination_hub" => nil,
            "destination_country" => nil,
            "mode_of_transport" => "ocean",
            "carrier" => "MSC",
            "service_level" => "standard",
            "cargo_class" => "fcl_20",
            "internal" => false,
            "transshipment" => "ZACPT",
            "wm_rate" => nil,
            "vm_rate" => nil,
            "origin_terminal" => nil,
            "destination_terminal" => nil,
            "fee_min" => nil,
            "fee_name" => nil,
            "fee_code" => nil,
            "currency" => "USD",
            "rate" => nil,
            "rate_basis" => "PER_CONTAINER",
            "range_min" => nil,
            "range_max" => nil,
            "base" => nil,
            "remarks" => nil,
            "organization_id" => organization.id,
            "Dynamic:ofr" => "4330.0",
            "Dynamic:lss" => "200.0"
          },
          {
            "carrier_code" => "msc",
            "row" => 3,
            "sheet_name" => "Sheet2",
            "service" => "standard",
            "group_id" => nil,
            "group_name" => nil,
            "effective_date" => Date.parse("Tue, 29 Dec 2020"),
            "expiration_date" => Date.parse("Fri, 31 Dec 2021"),
            "origin_locode" => nil,
            "origin_hub" => "Gothenburg",
            "origin_country" => "Sweden",
            "destination_locode" => nil,
            "destination_hub" => "Shanghai",
            "destination_country" => "China",
            "mode_of_transport" => "ocean",
            "carrier" => "MSC",
            "service_level" => "standard",
            "cargo_class" => "fcl_40",
            "internal" => false,
            "transshipment" => nil,
            "wm_rate" => nil,
            "vm_rate" => nil,
            "origin_terminal" => nil,
            "destination_terminal" => nil,
            "fee_min" => nil,
            "fee_name" => nil,
            "fee_code" => nil,
            "currency" => "USD",
            "rate" => nil,
            "rate_basis" => "PER_CONTAINER",
            "range_min" => nil,
            "range_max" => nil,
            "base" => nil,
            "remarks" => nil,
            "organization_id" => organization.id,
            "Dynamic:ofr" => "4660.0",
            "Dynamic:lss" => "250.0"
          },
          {
            "carrier_code" => "msc",
            "row" => 4,
            "sheet_name" => "Sheet2",
            "service" => "standard",
            "group_id" => nil,
            "group_name" => nil,
            "effective_date" => Date.parse("Tue, 29 Dec 2020"),
            "expiration_date" => Date.parse("Fri, 31 Dec 2021"),
            "origin_locode" => "SEGOT",
            "origin_hub" => "Gothenburg",
            "origin_country" => "Sweden",
            "destination_locode" => "CNSHA",
            "destination_hub" => "Shanghai",
            "destination_country" => "China",
            "mode_of_transport" => "ocean",
            "carrier" => "MSC",
            "service_level" => "standard",
            "cargo_class" => "fcl_40_hq",
            "internal" => false,
            "transshipment" => nil,
            "wm_rate" => nil,
            "vm_rate" => nil,
            "origin_terminal" => nil,
            "fee_min" => nil,
            "destination_terminal" => nil,
            "fee_name" => nil,
            "fee_code" => nil,
            "currency" => "USD",
            "rate" => nil,
            "rate_basis" => "PER_CONTAINER",
            "range_min" => nil,
            "range_max" => nil,
            "base" => nil,
            "remarks" => nil,
            "organization_id" => organization.id,
            "Dynamic:ofr" => "5330.0",
            "Dynamic:lss" => "300.0"
          }]
      end
    end

    trait :charge_categories do
      data do
        [{ "fee_name" => "Ocean Freight",
           "row" => 2,
           "sheet_name" => "Sheet1",
           "fee_code" => "bas",
           "organization_id" => organization.id,
           "Dynamic:ofr" => nil,
           "Dynamic:lss" => nil },
          { "fee_name" => "IMO 2020",
            "row" => 3,
            "sheet_name" => "Sheet1",
            "fee_code" => "imo 2020",
            "organization_id" => organization.id,
            "Dynamic:ofr" => nil,
            "Dynamic:lss" => nil },
          { "fee_name" => "Bunker Adjustment Fee",
            "row" => 4,
            "sheet_name" => "Sheet1",
            "fee_code" => "baf",
            "organization_id" => organization.id,
            "Dynamic:ofr" => nil,
            "Dynamic:lss" => nil },
          { "fee_name" => "Bunker Adjustment Fee",
            "row" => 5,
            "sheet_name" => "Sheet1",
            "fee_code" => "baf",
            "organization_id" => organization.id,
            "Dynamic:ofr" => nil,
            "Dynamic:lss" => nil },
          { "fee_name" => nil,
            "row" => 2,
            "sheet_name" => "Sheet2",
            "fee_code" => nil,
            "organization_id" => organization.id,
            "Dynamic:ofr" => "4330.0",
            "Dynamic:lss" => "200.0" },
          { "fee_name" => nil,
            "row" => 3,
            "sheet_name" => "Sheet2",
            "fee_code" => nil,
            "organization_id" => organization.id,
            "Dynamic:ofr" => "4660.0",
            "Dynamic:lss" => "250.0" },
          { "fee_name" => nil,
            "row" => 4,
            "sheet_name" => "Sheet2",
            "fee_code" => nil,
            "organization_id" => organization.id,
            "Dynamic:ofr" => "5330.0",
            "Dynamic:lss" => "300.0" }]
      end
    end

    trait :tenant_vehicles do
      data do
        [
          {
            "carrier_code" => "msc",
            "row" => 2,
            "sheet_name" => "Sheet1",
            "service" => "standard",
            "carrier" => "MSC",
            "mode_of_transport" => "ocean",
            "organization_id" => organization.id
          },
          {
            "carrier_code" => "msc",
            "row" => 3,
            "sheet_name" => "Sheet1",
            "service" => "standard",
            "carrier" => "MSC",
            "mode_of_transport" => "ocean",
            "organization_id" => organization.id
          },
          {
            "carrier_code" => "msc",
            "row" => 4,
            "sheet_name" => "Sheet1",
            "service" => "standard",
            "carrier" => "MSC",
            "mode_of_transport" => "ocean",
            "organization_id" => organization.id
          },
          {
            "carrier_code" => "msc",
            "row" => 5,
            "sheet_name" => "Sheet1",
            "service" => "standard",
            "carrier" => "MSC",
            "mode_of_transport" => "ocean",
            "organization_id" => organization.id
          },
          {
            "carrier_code" => "msc",
            "row" => 2,
            "sheet_name" => "Sheet2",
            "service" => "standard",
            "carrier" => "MSC",
            "mode_of_transport" => "ocean",
            "organization_id" => organization.id
          },
          {
            "carrier_code" => "msc",
            "row" => 3,
            "sheet_name" => "Sheet2",
            "service" => "standard",
            "carrier" => "MSC",
            "mode_of_transport" => "ocean",
            "organization_id" => organization.id
          },
          {
            "carrier_code" => "msc",
            "row" => 4,
            "sheet_name" => "Sheet2",
            "service" => "standard",
            "carrier" => "MSC",
            "mode_of_transport" => "ocean",
            "organization_id" => organization.id
          }
        ]
      end
    end

    trait :carriers do
      data do
        [
          { "carrier" => "MSC",
            "row" => 2,
            "sheet_name" => "Sheet1",
            "carrier_code" => "msc",
            "organization_id" => organization.id },
          { "carrier" => "MSC",
            "row" => 3,
            "sheet_name" => "Sheet1",
            "carrier_code" => "msc",
            "organization_id" => organization.id },
          { "carrier" => "MSC",
            "row" => 4,
            "sheet_name" => "Sheet1",
            "carrier_code" => "msc",
            "organization_id" => organization.id },
          { "carrier" => "MSC",
            "row" => 5,
            "sheet_name" => "Sheet1",
            "carrier_code" => "msc",
            "organization_id" => organization.id },
          { "carrier" => "MSC",
            "row" => 2,
            "sheet_name" => "Sheet2",
            "carrier_code" => "msc",
            "organization_id" => organization.id },
          { "carrier" => "MSC",
            "row" => 3,
            "sheet_name" => "Sheet2",
            "carrier_code" => "msc",
            "organization_id" => organization.id },
          { "carrier" => "MSC",
            "row" => 4,
            "sheet_name" => "Sheet2",
            "carrier_code" => "msc",
            "organization_id" => organization.id }
        ]
      end
    end

    trait :itineraries do
      data do
        [{ "origin_locode" => "SEGOT",
           "row" => 2,
           "sheet_name" => "Sheet1",
           "origin_terminal" => nil,
           "origin_hub" => nil,
           "origin_country" => nil,
           "destination_locode" => "CNSHA",
           "destination_terminal" => nil,
           "destination_hub" => nil,
           "destination_country" => nil,
           "mode_of_transport" => "ocean",
           "transshipment" => "ZACPT",
           "organization_id" => organization.id },
          { "origin_locode" => nil,
            "row" => 3,
            "sheet_name" => "Sheet1",
            "origin_terminal" => nil,
            "origin_hub" => "Gothenburg",
            "origin_country" => "Sweden",
            "destination_locode" => nil,
            "destination_terminal" => nil,
            "destination_hub" => "Shanghai",
            "destination_country" => "China",
            "mode_of_transport" => "ocean",
            "transshipment" => nil,
            "organization_id" => organization.id },
          { "origin_locode" => "SEGOT",
            "row" => 4,
            "sheet_name" => "Sheet1",
            "origin_terminal" => nil,
            "origin_hub" => "Gothenburg",
            "origin_country" => "Sweden",
            "destination_locode" => "CNSHA",
            "destination_terminal" => nil,
            "destination_hub" => "Shanghai",
            "destination_country" => "China",
            "mode_of_transport" => "ocean",
            "transshipment" => nil,
            "organization_id" => organization.id },
          { "origin_locode" => "SEGOT",
            "row" => 5,
            "sheet_name" => "Sheet1",
            "origin_terminal" => nil,
            "origin_hub" => "Gothenburg",
            "origin_country" => "Sweden",
            "destination_locode" => "CNSHA",
            "destination_terminal" => nil,
            "destination_hub" => "Shanghai",
            "destination_country" => "China",
            "mode_of_transport" => "ocean",
            "transshipment" => nil,
            "organization_id" => organization.id },
          { "origin_locode" => "SEGOT",
            "row" => 2,
            "sheet_name" => "Sheet2",
            "origin_terminal" => nil,
            "origin_hub" => nil,
            "origin_country" => nil,
            "destination_locode" => "CNSHA",
            "destination_terminal" => nil,
            "destination_hub" => nil,
            "destination_country" => nil,
            "mode_of_transport" => "ocean",
            "transshipment" => "ZACPT",
            "organization_id" => organization.id },
          { "origin_locode" => nil,
            "row" => 3,
            "sheet_name" => "Sheet2",
            "origin_terminal" => nil,
            "origin_hub" => "Gothenburg",
            "origin_country" => "Sweden",
            "destination_locode" => nil,
            "destination_terminal" => nil,
            "destination_hub" => "Shanghai",
            "destination_country" => "China",
            "mode_of_transport" => "ocean",
            "transshipment" => nil,
            "organization_id" => organization.id },
          { "origin_locode" => "SEGOT",
            "row" => 4,
            "sheet_name" => "Sheet2",
            "origin_terminal" => nil,
            "origin_hub" => "Gothenburg",
            "origin_country" => "Sweden",
            "destination_locode" => "CNSHA",
            "destination_terminal" => nil,
            "destination_hub" => "Shanghai",
            "destination_country" => "China",
            "mode_of_transport" => "ocean",
            "transshipment" => nil,
            "organization_id" => organization.id }]
      end
    end

    trait :hubs do
      data do
        [{ "name" => "Sydney",
           "row" => 2,
           "sheet_name" => "Hubs",
           "locode" => "AUSYD",
           "hub_status" => "active",
           "hub_type" => "ocean",
           "terminal" => "North Harbour",
           "terminal_code" => "SYDNHH",
           "latitude" => -33.85,
           "longitude" => 151.2,
           "country" => "Australia",
           "full_address" => "Unnamed Road, New South Wales, Australia",
           "free_out" => false,
           "import_charges" => false,
           "export_charges" => false,
           "pre_carriage" => false,
           "on_carriage" => false,
           "alternative_names" => nil,
           "organization_id" => organization.id },
          { "name" => "Hamburg",
            "row" => 3,
            "sheet_name" => "Hubs",
            "locode" => "DEHAM",
            "hub_status" => "active",
            "hub_type" => "ocean",
            "terminal" => nil,
            "terminal_code" => nil,
            "latitude" => 53.531121,
            "longitude" => 10.020287,
            "country" => "Germany",
            "full_address" => "Flughafenstr. 1-3, 22335 Hamburg, Germany",
            "free_out" => false,
            "import_charges" => false,
            "export_charges" => false,
            "pre_carriage" => false,
            "on_carriage" => false,
            "alternative_names" => nil,
            "organization_id" => organization.id }]
      end
    end

    trait :nexuses do
      data do
        [{ "name" => "Sydney",
           "row" => 2,
           "sheet_name" => "Hubs",
           "locode" => "AUSYD",
           "latitude" => -33.85,
           "longitude" => 151.2,
           "country" => "Australia",
           "organization_id" => organization.id },
          { "name" => "Hamburg",
            "row" => 3,
            "sheet_name" => "Hubs",
            "locode" => "DEHAM",
            "latitude" => 53.531121,
            "longitude" => 10.020287,
            "country" => "Germany",
            "organization_id" => organization.id }]
      end
    end

    trait :local_charges do
      data do
        [{"carrier_code"=>"ssc",
          "row"=>2,
          "sheet_name"=>"Local Charges",
          "service"=>"standard",
          "group_id"=>nil,
          "group_name"=>"Local Charges Group One",
          "effective_date"=> Date.parse("Sat, 01 May 2021"),
          "expiration_date"=> Date.parse("Fri, 31 Dec 2021"),
          "locode"=>"DEHAM",
          "hub"=>"Hamburg",
          "country"=>"Germany",
          "counterpart_locode"=>nil,
          "counterpart_hub"=>nil,
          "counterpart_country"=>nil,
          "mode_of_transport"=>"ocean",
          "carrier"=>"SSC",
          "direction"=>"export",
          "service_level"=>"standard",
          "cargo_class"=>"lcl",
          "load_type"=>"lcl",
          "terminal"=>nil,
          "counterpart_terminal"=>nil,
          "min"=>nil,
          "max"=>nil,
          "fee_name"=>"B/L Fee",
          "fee_code"=>"bl",
          "currency"=>"EUR",
          "rate_basis"=>"PER_TON",
          "range_min"=>nil,
          "range_max"=>nil,
          "base"=>nil,
          "ton"=>0.4e1,
          "cbm"=>nil,
          "kg"=>nil,
          "item"=>nil,
          "shipment"=>nil,
          "bill"=>nil,
          "container"=>nil,
          "wm"=>nil,
          "percentage"=>nil,
          "dangerous"=>false,
          "internal"=>false,
          "organization_id"=> organization.id},
         {"carrier_code"=>"ssc",
          "row"=>3,
          "sheet_name"=>"Local Charges",
          "service"=>"standard",
          "group_id"=>nil,
          "group_name"=>"Local Charges Group One",
          "effective_date"=> Date.parse("Sat, 01 May 2021"),
          "expiration_date"=> Date.parse("Fri, 31 Dec 2021"),
          "locode"=>"DEHAM",
          "hub"=>"Hamburg",
          "country"=>"Germany",
          "counterpart_locode"=>nil,
          "counterpart_hub"=>nil,
          "counterpart_country"=>nil,
          "mode_of_transport"=>"ocean",
          "carrier"=>"SSC",
          "direction"=>"export",
          "service_level"=>"standard",
          "cargo_class"=>"lcl",
          "load_type"=>"lcl",
          "terminal"=>nil,
          "counterpart_terminal"=>nil,
          "min"=>nil,
          "max"=>nil,
          "fee_name"=>"CUSTOMS DOC",
          "fee_code"=>"customs doc",
          "currency"=>"EUR",
          "rate_basis"=>"PER_CBM",
          "range_min"=>nil,
          "range_max"=>nil,
          "base"=>nil,
          "ton"=>nil,
          "cbm"=>0.5e1,
          "kg"=>nil,
          "item"=>nil,
          "shipment"=>nil,
          "bill"=>nil,
          "container"=>nil,
          "wm"=>nil,
          "percentage"=>nil,
          "dangerous"=>false,
          "internal"=>false,
          "organization_id"=> organization.id},
         {"carrier_code"=>"ssc",
          "row"=>4,
          "sheet_name"=>"Local Charges",
          "service"=>"standard",
          "group_id"=>nil,
          "group_name"=>"Local Charges Group One",
          "effective_date"=> Date.parse("Sat, 01 May 2021"),
          "expiration_date"=> Date.parse("Fri, 31 Dec 2021"),
          "locode"=>"DEHAM",
          "hub"=>"Hamburg",
          "country"=>"Germany",
          "counterpart_locode"=>nil,
          "counterpart_hub"=>nil,
          "counterpart_country"=>nil,
          "mode_of_transport"=>"ocean",
          "carrier"=>"SSC",
          "direction"=>"export",
          "service_level"=>"standard",
          "cargo_class"=>"lcl",
          "load_type"=>"lcl",
          "terminal"=>nil,
          "counterpart_terminal"=>nil,
          "min"=>nil,
          "max"=>nil,
          "fee_name"=>"Handling Fee",
          "fee_code"=>"hdl",
          "currency"=>"EUR",
          "rate_basis"=>"PER_KG",
          "range_min"=>nil,
          "range_max"=>nil,
          "base"=>nil,
          "ton"=>nil,
          "cbm"=>nil,
          "kg"=>0.6e1,
          "item"=>nil,
          "shipment"=>nil,
          "bill"=>nil,
          "container"=>nil,
          "wm"=>nil,
          "percentage"=>nil,
          "dangerous"=>false,
          "internal"=>false,
          "organization_id"=> organization.id}]
      end
    end
  end
end
