name: "Linter"

on:
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: github/super-linter@v3
        env:
          LINTER_RULES_PATH: /
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_DOCKERFILE: false
          FILTER_REGEX_EXCLUDE: "^(.*/spec/api/api/.*|db/data_schema.rb|db/structure.sql)$"
          RUBY_CONFIG_FILE: .rubocop.yml
