name: "Linter"

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]

jobs:
  skip:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content'
          skip_after_successful_duplicate: 'true'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  build:
    name: Lint Code Base
    runs-on: ubuntu-20.04

    needs: skip
    if: ${{ needs.skip.outputs.should_skip != 'true' }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
