name: Lint

on: [pull_request]

jobs:
  rubocop:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
      - uses: reviewdog/action-rubocop@v1
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-github:gemfile rubocop-rspec:gemfile
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_on_error: true
          level: warning

  hadolint:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: reviewdog/action-hadolint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review

  detect-secrets:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: reviewdog/action-detect-secrets@master
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review

  reek:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
      - uses: reviewdog/action-reek@v1
        with:
          # reek_version: gemfile
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
