name: Review

concurrency:
  group: review-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [master]

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-20.04
    outputs:
      tag: ${{ steps.publish.outputs.tag }}
    steps:
      - uses: itsmycargo/action-docker-publish@main
        id: publish
        with:
          repository: 003688427525.dkr.ecr.eu-central-1.amazonaws.com/polaris
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
