name: "Sentry"

on:
  push:
    branches: [master]

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: polaris
