name: Style
on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize, ready_for_review, reopened]

jobs:
  danger:
    name: Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Danger
        uses: docker://itsmycargo/danger:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
