version: "2.4"

services:
  app:
    image: ruby:2.5
    volumes:
      - ./:/app
    environment:
      TARGET_URL: https://imcqa:shipmetimbers@demo.review-chore-qa-jttfc0.itsmycargo.tech
      DRIVER: remote_chrome
      SELENIUM_URL: http://selenium:4444/wd/hub
    stdin_open: true
    tty: true
    mem_limit: 256m
    command: ["bash", "-c", "cd /app && bundle install && bin/cucumber"]
    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-chrome:3
    expose:
      - 4444
    volumes:
      - /dev/shm:/dev/shm
