# frozen_string_literal: true

source 'https://rubygems.org'

gem 'capybara', '~> 3.9.0'
gem 'chromedriver-helper', '~> 2.1.0'
gem 'chronic'
gem 'cucumber'
gem 'pry'
gem 'rest-client'
gem 'rspec-expectations'
gem 'selenium-webdriver', '~> 3.14.0'
